<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\AcceptTermsOfServiceRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model AcceptTermsOfServiceRequest
 *
 * @see AcceptTermsOfServiceRequest
 */
class AcceptTermsOfServiceRequestBuilder
{
    /**
     * @var AcceptTermsOfServiceRequest
     */
    private $instance;

    private function __construct(AcceptTermsOfServiceRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Accept Terms Of Service Request Builder object.
     *
     * @param string $acceptedBy
     */
    public static function init(string $acceptedBy): self
    {
        return new self(new AcceptTermsOfServiceRequest($acceptedBy));
    }

    /**
     * Sets ip Address field.
     *
     * @param string|null $value
     */
    public function ipAddress(?string $value): self
    {
        $this->instance->setIpAddress($value);
        return $this;
    }

    /**
     * Initializes a new Accept Terms Of Service Request object.
     */
    public function build(): AcceptTermsOfServiceRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
