<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\AccountHolder1;
use Core\Utils\CoreHelper;

/**
 * Builder for model AccountHolder1
 *
 * @see AccountHolder1
 */
class AccountHolder1Builder
{
    /**
     * @var AccountHolder1
     */
    private $instance;

    private function __construct(AccountHolder1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Account Holder 1 Builder object.
     *
     * @param string $fullName
     */
    public static function init(string $fullName): self
    {
        return new self(new AccountHolder1($fullName));
    }

    /**
     * Initializes a new Account Holder 1 object.
     */
    public function build(): AccountHolder1
    {
        return CoreHelper::clone($this->instance);
    }
}
