<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\AccountHolderDetails2;
use AdyenLib\Models\BankAccountDetail;
use AdyenLib\Models\BusinessDetails3;
use AdyenLib\Models\IndividualDetails3;
use AdyenLib\Models\LegalArrangementDetail;
use AdyenLib\Models\PayoutMethod;
use AdyenLib\Models\StoreDetail;
use AdyenLib\Models\ViasAddress6;
use AdyenLib\Models\ViasAddress9;
use AdyenLib\Models\ViasPhoneNumber3;
use Core\Utils\CoreHelper;

/**
 * Builder for model AccountHolderDetails2
 *
 * @see AccountHolderDetails2
 */
class AccountHolderDetails2Builder
{
    /**
     * @var AccountHolderDetails2
     */
    private $instance;

    private function __construct(AccountHolderDetails2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Account Holder Details 2 Builder object.
     *
     * @param ViasAddress9 $address
     */
    public static function init(ViasAddress9 $address): self
    {
        return new self(new AccountHolderDetails2($address));
    }

    /**
     * Sets bank Account Details field.
     *
     * @param BankAccountDetail[]|null $value
     */
    public function bankAccountDetails(?array $value): self
    {
        $this->instance->setBankAccountDetails($value);
        return $this;
    }

    /**
     * Sets bank Aggregator Data Reference field.
     *
     * @param string|null $value
     */
    public function bankAggregatorDataReference(?string $value): self
    {
        $this->instance->setBankAggregatorDataReference($value);
        return $this;
    }

    /**
     * Sets business Details field.
     *
     * @param BusinessDetails3|null $value
     */
    public function businessDetails(?BusinessDetails3 $value): self
    {
        $this->instance->setBusinessDetails($value);
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets full Phone Number field.
     *
     * @param string|null $value
     */
    public function fullPhoneNumber(?string $value): self
    {
        $this->instance->setFullPhoneNumber($value);
        return $this;
    }

    /**
     * Sets individual Details field.
     *
     * @param IndividualDetails3|null $value
     */
    public function individualDetails(?IndividualDetails3 $value): self
    {
        $this->instance->setIndividualDetails($value);
        return $this;
    }

    /**
     * Sets last Review Date field.
     *
     * @param string|null $value
     */
    public function lastReviewDate(?string $value): self
    {
        $this->instance->setLastReviewDate($value);
        return $this;
    }

    /**
     * Sets legal Arrangements field.
     *
     * @param LegalArrangementDetail[]|null $value
     */
    public function legalArrangements(?array $value): self
    {
        $this->instance->setLegalArrangements($value);
        return $this;
    }

    /**
     * Sets merchant Category Code field.
     *
     * @param string|null $value
     */
    public function merchantCategoryCode(?string $value): self
    {
        $this->instance->setMerchantCategoryCode($value);
        return $this;
    }

    /**
     * Sets metadata field.
     *
     * @param array<string,string>|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets payout Methods field.
     *
     * @param PayoutMethod[]|null $value
     */
    public function payoutMethods(?array $value): self
    {
        $this->instance->setPayoutMethods($value);
        return $this;
    }

    /**
     * Sets phone Number field.
     *
     * @param ViasPhoneNumber3|null $value
     */
    public function phoneNumber(?ViasPhoneNumber3 $value): self
    {
        $this->instance->setPhoneNumber($value);
        return $this;
    }

    /**
     * Sets principal Business Address field.
     *
     * @param ViasAddress6|null $value
     */
    public function principalBusinessAddress(?ViasAddress6 $value): self
    {
        $this->instance->setPrincipalBusinessAddress($value);
        return $this;
    }

    /**
     * Sets store Details field.
     *
     * @param StoreDetail[]|null $value
     */
    public function storeDetails(?array $value): self
    {
        $this->instance->setStoreDetails($value);
        return $this;
    }

    /**
     * Sets web Address field.
     *
     * @param string|null $value
     */
    public function webAddress(?string $value): self
    {
        $this->instance->setWebAddress($value);
        return $this;
    }

    /**
     * Initializes a new Account Holder Details 2 object.
     */
    public function build(): AccountHolderDetails2
    {
        return CoreHelper::clone($this->instance);
    }
}
