<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Address6;
use Core\Utils\CoreHelper;

/**
 * Builder for model Address6
 *
 * @see Address6
 */
class Address6Builder
{
    /**
     * @var Address6
     */
    private $instance;

    private function __construct(Address6 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Address 6 Builder object.
     *
     * @param string $country
     */
    public static function init(string $country): self
    {
        return new self(new Address6($country));
    }

    /**
     * Sets city field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets line 1 field.
     *
     * @param string|null $value
     */
    public function line1(?string $value): self
    {
        $this->instance->setLine1($value);
        return $this;
    }

    /**
     * Sets line 2 field.
     *
     * @param string|null $value
     */
    public function line2(?string $value): self
    {
        $this->instance->setLine2($value);
        return $this;
    }

    /**
     * Sets postal Code field.
     *
     * @param string|null $value
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Sets state Or Province field.
     *
     * @param string|null $value
     */
    public function stateOrProvince(?string $value): self
    {
        $this->instance->setStateOrProvince($value);
        return $this;
    }

    /**
     * Initializes a new Address 6 object.
     */
    public function build(): Address6
    {
        return CoreHelper::clone($this->instance);
    }
}
