<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Address22;
use Core\Utils\CoreHelper;

/**
 * Builder for model Address22
 *
 * @see Address22
 */
class Address22Builder
{
    /**
     * @var Address22
     */
    private $instance;

    private function __construct(Address22 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Address 22 Builder object.
     *
     * @param string $country
     */
    public static function init(string $country): self
    {
        return new self(new Address22($country));
    }

    /**
     * Sets city field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets postal Code field.
     *
     * @param string|null $value
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Sets state Or Province field.
     *
     * @param string|null $value
     */
    public function stateOrProvince(?string $value): self
    {
        $this->instance->setStateOrProvince($value);
        return $this;
    }

    /**
     * Sets street field.
     *
     * @param string|null $value
     */
    public function street(?string $value): self
    {
        $this->instance->setStreet($value);
        return $this;
    }

    /**
     * Sets street 2 field.
     *
     * @param string|null $value
     */
    public function street2(?string $value): self
    {
        $this->instance->setStreet2($value);
        return $this;
    }

    /**
     * Initializes a new Address 22 object.
     */
    public function build(): Address22
    {
        return CoreHelper::clone($this->instance);
    }
}
