<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Amount18;
use Core\Utils\CoreHelper;

/**
 * Builder for model Amount18
 *
 * @see Amount18
 */
class Amount18Builder
{
    /**
     * @var Amount18
     */
    private $instance;

    private function __construct(Amount18 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Amount 18 Builder object.
     *
     * @param string $currency
     * @param int $value
     */
    public static function init(string $currency, int $value): self
    {
        return new self(new Amount18($currency, $value));
    }

    /**
     * Initializes a new Amount 18 object.
     */
    public function build(): Amount18
    {
        return CoreHelper::clone($this->instance);
    }
}
