<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\AmountsReq;
use Core\Utils\CoreHelper;

/**
 * Builder for model AmountsReq
 *
 * @see AmountsReq
 */
class AmountsReqBuilder
{
    /**
     * @var AmountsReq
     */
    private $instance;

    private function __construct(AmountsReq $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Amounts Req Builder object.
     *
     * @param string $currency
     * @param float $requestedAmount
     */
    public static function init(string $currency, float $requestedAmount): self
    {
        return new self(new AmountsReq($currency, $requestedAmount));
    }

    /**
     * Sets Cash Back Amount field.
     *
     * @param float|null $value
     */
    public function cashBackAmount(?float $value): self
    {
        $this->instance->setCashBackAmount($value);
        return $this;
    }

    /**
     * Sets Tip Amount field.
     *
     * @param float|null $value
     */
    public function tipAmount(?float $value): self
    {
        $this->instance->setTipAmount($value);
        return $this;
    }

    /**
     * Sets Paid Amount field.
     *
     * @param float|null $value
     */
    public function paidAmount(?float $value): self
    {
        $this->instance->setPaidAmount($value);
        return $this;
    }

    /**
     * Sets Minimum Amount To Deliver field.
     *
     * @param float|null $value
     */
    public function minimumAmountToDeliver(?float $value): self
    {
        $this->instance->setMinimumAmountToDeliver($value);
        return $this;
    }

    /**
     * Sets Maximum Cash Back Amount field.
     *
     * @param float|null $value
     */
    public function maximumCashBackAmount(?float $value): self
    {
        $this->instance->setMaximumCashBackAmount($value);
        return $this;
    }

    /**
     * Sets Minimum Split Amount field.
     *
     * @param float|null $value
     */
    public function minimumSplitAmount(?float $value): self
    {
        $this->instance->setMinimumSplitAmount($value);
        return $this;
    }

    /**
     * Initializes a new Amounts Req object.
     */
    public function build(): AmountsReq
    {
        return CoreHelper::clone($this->instance);
    }
}
