<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\AmountsResp1;
use Core\Utils\CoreHelper;

/**
 * Builder for model AmountsResp1
 *
 * @see AmountsResp1
 */
class AmountsResp1Builder
{
    /**
     * @var AmountsResp1
     */
    private $instance;

    private function __construct(AmountsResp1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Amounts Resp 1 Builder object.
     *
     * @param float $authorizedAmount
     */
    public static function init(float $authorizedAmount): self
    {
        return new self(new AmountsResp1($authorizedAmount));
    }

    /**
     * Sets Currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets Total Rebates Amount field.
     *
     * @param float|null $value
     */
    public function totalRebatesAmount(?float $value): self
    {
        $this->instance->setTotalRebatesAmount($value);
        return $this;
    }

    /**
     * Sets Total Fees Amount field.
     *
     * @param float|null $value
     */
    public function totalFeesAmount(?float $value): self
    {
        $this->instance->setTotalFeesAmount($value);
        return $this;
    }

    /**
     * Sets Cash Back Amount field.
     *
     * @param float|null $value
     */
    public function cashBackAmount(?float $value): self
    {
        $this->instance->setCashBackAmount($value);
        return $this;
    }

    /**
     * Sets Tip Amount field.
     *
     * @param float|null $value
     */
    public function tipAmount(?float $value): self
    {
        $this->instance->setTipAmount($value);
        return $this;
    }

    /**
     * Initializes a new Amounts Resp 1 object.
     */
    public function build(): AmountsResp1
    {
        return CoreHelper::clone($this->instance);
    }
}
