<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\BalanceWebhookSetting;
use AdyenLib\Models\Condition;
use AdyenLib\Models\Target3;
use Core\Utils\CoreHelper;

/**
 * Builder for model BalanceWebhookSetting
 *
 * @see BalanceWebhookSetting
 */
class BalanceWebhookSettingBuilder
{
    /**
     * @var BalanceWebhookSetting
     */
    private $instance;

    private function __construct(BalanceWebhookSetting $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Balance Webhook Setting Builder object.
     *
     * @param string $currency
     * @param string $id
     * @param string $status
     * @param Target3 $target
     */
    public static function init(string $currency, string $id, string $status, Target3 $target): self
    {
        return new self(new BalanceWebhookSetting($currency, $id, $status, $target));
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets conditions field.
     *
     * @param Condition[]|null $value
     */
    public function conditions(?array $value): self
    {
        $this->instance->setConditions($value);
        return $this;
    }

    /**
     * Initializes a new Balance Webhook Setting object.
     */
    public function build(): BalanceWebhookSetting
    {
        return CoreHelper::clone($this->instance);
    }
}
