<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\AULocalAccountIdentification;
use AdyenLib\Models\BankAccountInfo;
use AdyenLib\Models\CALocalAccountIdentification;
use AdyenLib\Models\CZLocalAccountIdentification;
use AdyenLib\Models\DKLocalAccountIdentification;
use AdyenLib\Models\HKLocalAccountIdentification;
use AdyenLib\Models\HULocalAccountIdentification;
use AdyenLib\Models\IbanAccountIdentification;
use AdyenLib\Models\NOLocalAccountIdentification;
use AdyenLib\Models\NumberAndBicAccountIdentification;
use AdyenLib\Models\NZLocalAccountIdentification;
use AdyenLib\Models\PLLocalAccountIdentification;
use AdyenLib\Models\SELocalAccountIdentification;
use AdyenLib\Models\SGLocalAccountIdentification;
use AdyenLib\Models\UKLocalAccountIdentification;
use AdyenLib\Models\USLocalAccountIdentification;
use Core\Utils\CoreHelper;

/**
 * Builder for model BankAccountInfo
 *
 * @see BankAccountInfo
 */
class BankAccountInfoBuilder
{
    /**
     * @var BankAccountInfo
     */
    private $instance;

    private function __construct(BankAccountInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bank Account Info Builder object.
     */
    public static function init(): self
    {
        return new self(new BankAccountInfo());
    }

    /**
     * Sets account Identification field.
     *
     * @param AULocalAccountIdentification|CALocalAccountIdentification|CZLocalAccountIdentification|DKLocalAccountIdentification|HKLocalAccountIdentification|HULocalAccountIdentification|IbanAccountIdentification|NOLocalAccountIdentification|NZLocalAccountIdentification|NumberAndBicAccountIdentification|PLLocalAccountIdentification|SELocalAccountIdentification|SGLocalAccountIdentification|UKLocalAccountIdentification|USLocalAccountIdentification|null $value
     */
    public function accountIdentification($value): self
    {
        $this->instance->setAccountIdentification($value);
        return $this;
    }

    /**
     * Sets account Type field.
     *
     * @param string|null $value
     */
    public function accountType(?string $value): self
    {
        $this->instance->setAccountType($value);
        return $this;
    }

    /**
     * Sets bank Name field.
     *
     * @param string|null $value
     */
    public function bankName(?string $value): self
    {
        $this->instance->setBankName($value);
        return $this;
    }

    /**
     * Sets country Code field.
     *
     * @param string|null $value
     */
    public function countryCode(?string $value): self
    {
        $this->instance->setCountryCode($value);
        return $this;
    }

    /**
     * Sets trusted Source field.
     *
     * @param bool|null $value
     */
    public function trustedSource(?bool $value): self
    {
        $this->instance->setTrustedSource($value);
        return $this;
    }

    /**
     * Initializes a new Bank Account Info object.
     */
    public function build(): BankAccountInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
