<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\BSBAccountIdentifier;
use Core\Utils\CoreHelper;

/**
 * Builder for model BSBAccountIdentifier
 *
 * @see BSBAccountIdentifier
 */
class BSBAccountIdentifierBuilder
{
    /**
     * @var BSBAccountIdentifier
     */
    private $instance;

    private function __construct(BSBAccountIdentifier $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new BSB Account Identifier Builder object.
     *
     * @param string $accountNumber
     * @param string $bsbCode
     */
    public static function init(string $accountNumber, string $bsbCode): self
    {
        return new self(new BSBAccountIdentifier($accountNumber, $bsbCode));
    }

    /**
     * Initializes a new BSB Account Identifier object.
     */
    public function build(): BSBAccountIdentifier
    {
        return CoreHelper::clone($this->instance);
    }
}
