<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\CalculateTermsOfServiceStatusResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model CalculateTermsOfServiceStatusResponse
 *
 * @see CalculateTermsOfServiceStatusResponse
 */
class CalculateTermsOfServiceStatusResponseBuilder
{
    /**
     * @var CalculateTermsOfServiceStatusResponse
     */
    private $instance;

    private function __construct(CalculateTermsOfServiceStatusResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Calculate Terms Of Service Status Response Builder object.
     */
    public static function init(): self
    {
        return new self(new CalculateTermsOfServiceStatusResponse());
    }

    /**
     * Sets terms Of Service Types field.
     *
     * @param string[]|null $value
     */
    public function termsOfServiceTypes(?array $value): self
    {
        $this->instance->setTermsOfServiceTypes($value);
        return $this;
    }

    /**
     * Initializes a new Calculate Terms Of Service Status Response object.
     */
    public function build(): CalculateTermsOfServiceStatusResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
