<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\CancelPaymentRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model CancelPaymentRequest
 *
 * @see CancelPaymentRequest
 */
class CancelPaymentRequestBuilder
{
    /**
     * @var CancelPaymentRequest
     */
    private $instance;

    private function __construct(CancelPaymentRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cancel Payment Request Builder object.
     *
     * @param string $token
     */
    public static function init(string $token): self
    {
        return new self(new CancelPaymentRequest($token));
    }

    /**
     * Initializes a new Cancel Payment Request object.
     */
    public function build(): CancelPaymentRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
