<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\CapabilityProblem1;
use AdyenLib\Models\CapabilityProblemEntity1;
use AdyenLib\Models\VerificationError1;
use Core\Utils\CoreHelper;

/**
 * Builder for model CapabilityProblem1
 *
 * @see CapabilityProblem1
 */
class CapabilityProblem1Builder
{
    /**
     * @var CapabilityProblem1
     */
    private $instance;

    private function __construct(CapabilityProblem1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Capability Problem 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new CapabilityProblem1());
    }

    /**
     * Sets entity field.
     *
     * @param CapabilityProblemEntity1|null $value
     */
    public function entity(?CapabilityProblemEntity1 $value): self
    {
        $this->instance->setEntity($value);
        return $this;
    }

    /**
     * Sets verification Errors field.
     *
     * @param VerificationError1[]|null $value
     */
    public function verificationErrors(?array $value): self
    {
        $this->instance->setVerificationErrors($value);
        return $this;
    }

    /**
     * Initializes a new Capability Problem 1 object.
     */
    public function build(): CapabilityProblem1
    {
        return CoreHelper::clone($this->instance);
    }
}
