<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\BulkAddress1;
use AdyenLib\Models\CardConfiguration;
use Core\Utils\CoreHelper;

/**
 * Builder for model CardConfiguration
 *
 * @see CardConfiguration
 */
class CardConfigurationBuilder
{
    /**
     * @var CardConfiguration
     */
    private $instance;

    private function __construct(CardConfiguration $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Configuration Builder object.
     *
     * @param string $configurationProfileId
     */
    public static function init(string $configurationProfileId): self
    {
        return new self(new CardConfiguration($configurationProfileId));
    }

    /**
     * Sets activation field.
     *
     * @param string|null $value
     */
    public function activation(?string $value): self
    {
        $this->instance->setActivation($value);
        return $this;
    }

    /**
     * Sets activation Url field.
     *
     * @param string|null $value
     */
    public function activationUrl(?string $value): self
    {
        $this->instance->setActivationUrl($value);
        return $this;
    }

    /**
     * Sets bulk Address field.
     *
     * @param BulkAddress1|null $value
     */
    public function bulkAddress(?BulkAddress1 $value): self
    {
        $this->instance->setBulkAddress($value);
        return $this;
    }

    /**
     * Sets card Image Id field.
     *
     * @param string|null $value
     */
    public function cardImageId(?string $value): self
    {
        $this->instance->setCardImageId($value);
        return $this;
    }

    /**
     * Sets carrier field.
     *
     * @param string|null $value
     */
    public function carrier(?string $value): self
    {
        $this->instance->setCarrier($value);
        return $this;
    }

    /**
     * Sets carrier Image Id field.
     *
     * @param string|null $value
     */
    public function carrierImageId(?string $value): self
    {
        $this->instance->setCarrierImageId($value);
        return $this;
    }

    /**
     * Sets currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets envelope field.
     *
     * @param string|null $value
     */
    public function envelope(?string $value): self
    {
        $this->instance->setEnvelope($value);
        return $this;
    }

    /**
     * Sets insert field.
     *
     * @param string|null $value
     */
    public function insert(?string $value): self
    {
        $this->instance->setInsert($value);
        return $this;
    }

    /**
     * Sets language field.
     *
     * @param string|null $value
     */
    public function language(?string $value): self
    {
        $this->instance->setLanguage($value);
        return $this;
    }

    /**
     * Sets logo Image Id field.
     *
     * @param string|null $value
     */
    public function logoImageId(?string $value): self
    {
        $this->instance->setLogoImageId($value);
        return $this;
    }

    /**
     * Sets pin Mailer field.
     *
     * @param string|null $value
     */
    public function pinMailer(?string $value): self
    {
        $this->instance->setPinMailer($value);
        return $this;
    }

    /**
     * Sets print Line field.
     *
     * @param string|null $value
     */
    public function printLine(?string $value): self
    {
        $this->instance->setPrintLine($value);
        return $this;
    }

    /**
     * Sets shipment Method field.
     *
     * @param string|null $value
     */
    public function shipmentMethod(?string $value): self
    {
        $this->instance->setShipmentMethod($value);
        return $this;
    }

    /**
     * Initializes a new Card Configuration object.
     */
    public function build(): CardConfiguration
    {
        return CoreHelper::clone($this->instance);
    }
}
