<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\CashOutInfoCounterparty1;
use Core\Utils\CoreHelper;

/**
 * Builder for model CashOutInfoCounterparty1
 *
 * @see CashOutInfoCounterparty1
 */
class CashOutInfoCounterparty1Builder
{
    /**
     * @var CashOutInfoCounterparty1
     */
    private $instance;

    private function __construct(CashOutInfoCounterparty1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cash Out Info Counterparty 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new CashOutInfoCounterparty1());
    }

    /**
     * Sets transfer Instrument Id field.
     *
     * @param string|null $value
     */
    public function transferInstrumentId(?string $value): self
    {
        $this->instance->setTransferInstrumentId($value);
        return $this;
    }

    /**
     * Initializes a new Cash Out Info Counterparty 1 object.
     */
    public function build(): CashOutInfoCounterparty1
    {
        return CoreHelper::clone($this->instance);
    }
}
