<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\CompanyBalances;
use AdyenLib\Models\MerchantBalance;
use Core\Utils\CoreHelper;

/**
 * Builder for model CompanyBalances
 *
 * @see CompanyBalances
 */
class CompanyBalancesBuilder
{
    /**
     * @var CompanyBalances
     */
    private $instance;

    private function __construct(CompanyBalances $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Company Balances Builder object.
     */
    public static function init(): self
    {
        return new self(new CompanyBalances());
    }

    /**
     * Sets merchant Balances Overview field.
     *
     * @param MerchantBalance[]|null $value
     */
    public function merchantBalancesOverview(?array $value): self
    {
        $this->instance->setMerchantBalancesOverview($value);
        return $this;
    }

    /**
     * Initializes a new Company Balances object.
     */
    public function build(): CompanyBalances
    {
        return CoreHelper::clone($this->instance);
    }
}
