<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Address;
use AdyenLib\Models\ContactDetails1;
use AdyenLib\Models\Phone31;
use Core\Utils\CoreHelper;

/**
 * Builder for model ContactDetails1
 *
 * @see ContactDetails1
 */
class ContactDetails1Builder
{
    /**
     * @var ContactDetails1
     */
    private $instance;

    private function __construct(ContactDetails1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Contact Details 1 Builder object.
     *
     * @param Address $address
     * @param string $email
     * @param Phone31 $phone
     */
    public static function init(Address $address, string $email, Phone31 $phone): self
    {
        return new self(new ContactDetails1($address, $email, $phone));
    }

    /**
     * Sets web Address field.
     *
     * @param string|null $value
     */
    public function webAddress(?string $value): self
    {
        $this->instance->setWebAddress($value);
        return $this;
    }

    /**
     * Initializes a new Contact Details 1 object.
     */
    public function build(): ContactDetails1
    {
        return CoreHelper::clone($this->instance);
    }
}
