<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Amount;
use AdyenLib\Models\CostEstimateAssumptions1;
use AdyenLib\Models\CostEstimateRequest;
use AdyenLib\Models\MerchantDetails2;
use AdyenLib\Models\Recurring;
use Core\Utils\CoreHelper;

/**
 * Builder for model CostEstimateRequest
 *
 * @see CostEstimateRequest
 */
class CostEstimateRequestBuilder
{
    /**
     * @var CostEstimateRequest
     */
    private $instance;

    private function __construct(CostEstimateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cost Estimate Request Builder object.
     *
     * @param Amount $amount
     * @param string $merchantAccount
     */
    public static function init(Amount $amount, string $merchantAccount): self
    {
        return new self(new CostEstimateRequest($amount, $merchantAccount));
    }

    /**
     * Sets assumptions field.
     *
     * @param CostEstimateAssumptions1|null $value
     */
    public function assumptions(?CostEstimateAssumptions1 $value): self
    {
        $this->instance->setAssumptions($value);
        return $this;
    }

    /**
     * Sets card Number field.
     *
     * @param string|null $value
     */
    public function cardNumber(?string $value): self
    {
        $this->instance->setCardNumber($value);
        return $this;
    }

    /**
     * Sets encrypted Card Number field.
     *
     * @param string|null $value
     */
    public function encryptedCardNumber(?string $value): self
    {
        $this->instance->setEncryptedCardNumber($value);
        return $this;
    }

    /**
     * Sets merchant Details field.
     *
     * @param MerchantDetails2|null $value
     */
    public function merchantDetails(?MerchantDetails2 $value): self
    {
        $this->instance->setMerchantDetails($value);
        return $this;
    }

    /**
     * Sets recurring field.
     *
     * @param Recurring|null $value
     */
    public function recurring(?Recurring $value): self
    {
        $this->instance->setRecurring($value);
        return $this;
    }

    /**
     * Sets selected Recurring Detail Reference field.
     *
     * @param string|null $value
     */
    public function selectedRecurringDetailReference(?string $value): self
    {
        $this->instance->setSelectedRecurringDetailReference($value);
        return $this;
    }

    /**
     * Sets shopper Interaction field.
     *
     * @param string|null $value
     */
    public function shopperInteraction(?string $value): self
    {
        $this->instance->setShopperInteraction($value);
        return $this;
    }

    /**
     * Sets shopper Reference field.
     *
     * @param string|null $value
     */
    public function shopperReference(?string $value): self
    {
        $this->instance->setShopperReference($value);
        return $this;
    }

    /**
     * Initializes a new Cost Estimate Request object.
     */
    public function build(): CostEstimateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
