<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\AllowedOrigin;
use AdyenLib\Models\ApiCredentialLinks2;
use AdyenLib\Models\CreateApiCredentialResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model CreateApiCredentialResponse
 *
 * @see CreateApiCredentialResponse
 */
class CreateApiCredentialResponseBuilder
{
    /**
     * @var CreateApiCredentialResponse
     */
    private $instance;

    private function __construct(CreateApiCredentialResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Api Credential Response Builder object.
     *
     * @param bool $active
     * @param string[] $allowedIpAddresses
     * @param string $apiKey
     * @param string $clientKey
     * @param string $id
     * @param string $password
     * @param string[] $roles
     * @param string $username
     */
    public static function init(
        bool $active,
        array $allowedIpAddresses,
        string $apiKey,
        string $clientKey,
        string $id,
        string $password,
        array $roles,
        string $username
    ): self {
        return new self(new CreateApiCredentialResponse(
            $active,
            $allowedIpAddresses,
            $apiKey,
            $clientKey,
            $id,
            $password,
            $roles,
            $username
        ));
    }

    /**
     * Sets links field.
     *
     * @param ApiCredentialLinks2|null $value
     */
    public function links(?ApiCredentialLinks2 $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Sets allowed Origins field.
     *
     * @param AllowedOrigin[]|null $value
     */
    public function allowedOrigins(?array $value): self
    {
        $this->instance->setAllowedOrigins($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets subject DN field.
     *
     * @param string|null $value
     */
    public function subjectDN(?string $value): self
    {
        $this->instance->setSubjectDN($value);
        return $this;
    }

    /**
     * Initializes a new Create Api Credential Response object.
     */
    public function build(): CreateApiCredentialResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
