<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Amount17;
use AdyenLib\Models\CreateScaInformation1;
use AdyenLib\Models\CreateTransferLimitRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model CreateTransferLimitRequest
 *
 * @see CreateTransferLimitRequest
 */
class CreateTransferLimitRequestBuilder
{
    /**
     * @var CreateTransferLimitRequest
     */
    private $instance;

    private function __construct(CreateTransferLimitRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Transfer Limit Request Builder object.
     *
     * @param Amount17 $amount
     * @param string $scope
     * @param string $transferType
     */
    public static function init(Amount17 $amount, string $scope, string $transferType): self
    {
        return new self(new CreateTransferLimitRequest($amount, $scope, $transferType));
    }

    /**
     * Sets ends At field.
     *
     * @param \DateTime|null $value
     */
    public function endsAt(?\DateTime $value): self
    {
        $this->instance->setEndsAt($value);
        return $this;
    }

    /**
     * Sets reference field.
     *
     * @param string|null $value
     */
    public function reference(?string $value): self
    {
        $this->instance->setReference($value);
        return $this;
    }

    /**
     * Sets sca Information field.
     *
     * @param CreateScaInformation1|null $value
     */
    public function scaInformation(?CreateScaInformation1 $value): self
    {
        $this->instance->setScaInformation($value);
        return $this;
    }

    /**
     * Sets starts At field.
     *
     * @param \DateTime|null $value
     */
    public function startsAt(?\DateTime $value): self
    {
        $this->instance->setStartsAt($value);
        return $this;
    }

    /**
     * Initializes a new Create Transfer Limit Request object.
     */
    public function build(): CreateTransferLimitRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
