<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\CZLocalAccountIdentification;
use Core\Utils\CoreHelper;

/**
 * Builder for model CZLocalAccountIdentification
 *
 * @see CZLocalAccountIdentification
 */
class CZLocalAccountIdentificationBuilder
{
    /**
     * @var CZLocalAccountIdentification
     */
    private $instance;

    private function __construct(CZLocalAccountIdentification $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new CZ Local Account Identification Builder object.
     *
     * @param string $accountNumber
     * @param string $bankCode
     */
    public static function init(string $accountNumber, string $bankCode): self
    {
        return new self(new CZLocalAccountIdentification($accountNumber, $bankCode));
    }

    /**
     * Initializes a new CZ Local Account Identification object.
     */
    public function build(): CZLocalAccountIdentification
    {
        return CoreHelper::clone($this->instance);
    }
}
