<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\DiscoverResponseInfo1;
use AdyenLib\Models\TransactionDescriptionResponseInfo1;
use Core\Utils\CoreHelper;

/**
 * Builder for model DiscoverResponseInfo1
 *
 * @see DiscoverResponseInfo1
 */
class DiscoverResponseInfo1Builder
{
    /**
     * @var DiscoverResponseInfo1
     */
    private $instance;

    private function __construct(DiscoverResponseInfo1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Discover Response Info 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new DiscoverResponseInfo1());
    }

    /**
     * Sets transaction Description field.
     *
     * @param TransactionDescriptionResponseInfo1|null $value
     */
    public function transactionDescription(?TransactionDescriptionResponseInfo1 $value): self
    {
        $this->instance->setTransactionDescription($value);
        return $this;
    }

    /**
     * Initializes a new Discover Response Info 1 object.
     */
    public function build(): DiscoverResponseInfo1
    {
        return CoreHelper::clone($this->instance);
    }
}
