<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\DonationCampaignRequest;
use AdyenLib\Models\InPersonDonationSettings2;
use AdyenLib\Models\OnlineDonationSettings2;
use Core\Utils\CoreHelper;

/**
 * Builder for model DonationCampaignRequest
 *
 * @see DonationCampaignRequest
 */
class DonationCampaignRequestBuilder
{
    /**
     * @var DonationCampaignRequest
     */
    private $instance;

    private function __construct(DonationCampaignRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Donation Campaign Request Builder object.
     *
     * @param string $name
     * @param string $nonprofitCauseId
     */
    public static function init(string $name, string $nonprofitCauseId): self
    {
        return new self(new DonationCampaignRequest($name, $nonprofitCauseId));
    }

    /**
     * Sets account Holder Ids field.
     *
     * @param string[]|null $value
     */
    public function accountHolderIds(?array $value): self
    {
        $this->instance->setAccountHolderIds($value);
        return $this;
    }

    /**
     * Sets in Person field.
     *
     * @param InPersonDonationSettings2|null $value
     */
    public function inPerson(?InPersonDonationSettings2 $value): self
    {
        $this->instance->setInPerson($value);
        return $this;
    }

    /**
     * Sets online field.
     *
     * @param OnlineDonationSettings2|null $value
     */
    public function online(?OnlineDonationSettings2 $value): self
    {
        $this->instance->setOnline($value);
        return $this;
    }

    /**
     * Initializes a new Donation Campaign Request object.
     */
    public function build(): DonationCampaignRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
