<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\DuplicateInfo;
use Core\Utils\CoreHelper;

/**
 * Builder for model DuplicateInfo
 *
 * @see DuplicateInfo
 */
class DuplicateInfoBuilder
{
    /**
     * @var DuplicateInfo
     */
    private $instance;

    private function __construct(DuplicateInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Duplicate Info Builder object.
     *
     * @param string $duplicateTransactionId
     * @param bool $sameCard
     */
    public static function init(string $duplicateTransactionId, bool $sameCard): self
    {
        return new self(new DuplicateInfo($duplicateTransactionId, $sameCard));
    }

    /**
     * Sets same Issuer field.
     *
     * @param bool|null $value
     */
    public function sameIssuer(?bool $value): self
    {
        $this->instance->setSameIssuer($value);
        return $this;
    }

    /**
     * Initializes a new Duplicate Info object.
     */
    public function build(): DuplicateInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
