<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Duration;
use Core\Utils\CoreHelper;

/**
 * Builder for model Duration
 *
 * @see Duration
 */
class DurationBuilder
{
    /**
     * @var Duration
     */
    private $instance;

    private function __construct(Duration $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Duration Builder object.
     */
    public static function init(): self
    {
        return new self(new Duration());
    }

    /**
     * Sets unit field.
     *
     * @param string|null $value
     */
    public function unit(?string $value): self
    {
        $this->instance->setUnit($value);
        return $this;
    }

    /**
     * Sets value field.
     *
     * @param int|null $value
     */
    public function value(?int $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Initializes a new Duration object.
     */
    public function build(): Duration
    {
        return CoreHelper::clone($this->instance);
    }
}
