<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\EventUrl3;
use AdyenLib\Models\Url;
use Core\Utils\CoreHelper;

/**
 * Builder for model EventUrl3
 *
 * @see EventUrl3
 */
class EventUrl3Builder
{
    /**
     * @var EventUrl3
     */
    private $instance;

    private function __construct(EventUrl3 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Event Url 3 Builder object.
     */
    public static function init(): self
    {
        return new self(new EventUrl3());
    }

    /**
     * Sets event Local Urls field.
     *
     * @param Url[]|null $value
     */
    public function eventLocalUrls(?array $value): self
    {
        $this->instance->setEventLocalUrls($value);
        return $this;
    }

    /**
     * Sets event Public Urls field.
     *
     * @param Url[]|null $value
     */
    public function eventPublicUrls(?array $value): self
    {
        $this->instance->setEventPublicUrls($value);
        return $this;
    }

    /**
     * Initializes a new Event Url 3 object.
     */
    public function build(): EventUrl3
    {
        return CoreHelper::clone($this->instance);
    }
}
