<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\GrantCounterparty2;
use Core\Utils\CoreHelper;

/**
 * Builder for model GrantCounterparty2
 *
 * @see GrantCounterparty2
 */
class GrantCounterparty2Builder
{
    /**
     * @var GrantCounterparty2
     */
    private $instance;

    private function __construct(GrantCounterparty2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Grant Counterparty 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new GrantCounterparty2());
    }

    /**
     * Sets account Holder Id field.
     *
     * @param string|null $value
     */
    public function accountHolderId(?string $value): self
    {
        $this->instance->setAccountHolderId($value);
        return $this;
    }

    /**
     * Sets balance Account Id field.
     *
     * @param string|null $value
     */
    public function balanceAccountId(?string $value): self
    {
        $this->instance->setBalanceAccountId($value);
        return $this;
    }

    /**
     * Sets transfer Instrument Id field.
     *
     * @param string|null $value
     */
    public function transferInstrumentId(?string $value): self
    {
        $this->instance->setTransferInstrumentId($value);
        return $this;
    }

    /**
     * Initializes a new Grant Counterparty 2 object.
     */
    public function build(): GrantCounterparty2
    {
        return CoreHelper::clone($this->instance);
    }
}
