<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\HostStatus;
use Core\Utils\CoreHelper;

/**
 * Builder for model HostStatus
 *
 * @see HostStatus
 */
class HostStatusBuilder
{
    /**
     * @var HostStatus
     */
    private $instance;

    private function __construct(HostStatus $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Host Status Builder object.
     *
     * @param int $acquirerID
     */
    public static function init(int $acquirerID): self
    {
        return new self(new HostStatus($acquirerID));
    }

    /**
     * Sets Is Reachable Flag field.
     *
     * @param bool|null $value
     */
    public function isReachableFlag(?bool $value): self
    {
        $this->instance->setIsReachableFlag($value);
        return $this;
    }

    /**
     * Initializes a new Host Status object.
     */
    public function build(): HostStatus
    {
        return CoreHelper::clone($this->instance);
    }
}
