<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\HULocalAccountIdentification1;
use Core\Utils\CoreHelper;

/**
 * Builder for model HULocalAccountIdentification1
 *
 * @see HULocalAccountIdentification1
 */
class HULocalAccountIdentification1Builder
{
    /**
     * @var HULocalAccountIdentification1
     */
    private $instance;

    private function __construct(HULocalAccountIdentification1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new HU Local Account Identification 1 Builder object.
     *
     * @param string $accountNumber
     */
    public static function init(string $accountNumber): self
    {
        return new self(new HULocalAccountIdentification1($accountNumber));
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Initializes a new HU Local Account Identification 1 object.
     */
    public function build(): HULocalAccountIdentification1
    {
        return CoreHelper::clone($this->instance);
    }
}
