<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\IdealResponseInfo;
use AdyenLib\Models\TransactionDescriptionResponseInfo1;
use Core\Utils\CoreHelper;

/**
 * Builder for model IdealResponseInfo
 *
 * @see IdealResponseInfo
 */
class IdealResponseInfoBuilder
{
    /**
     * @var IdealResponseInfo
     */
    private $instance;

    private function __construct(IdealResponseInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Ideal Response Info Builder object.
     */
    public static function init(): self
    {
        return new self(new IdealResponseInfo());
    }

    /**
     * Sets transaction Description field.
     *
     * @param TransactionDescriptionResponseInfo1|null $value
     */
    public function transactionDescription(?TransactionDescriptionResponseInfo1 $value): self
    {
        $this->instance->setTransactionDescription($value);
        return $this;
    }

    /**
     * Initializes a new Ideal Response Info object.
     */
    public function build(): IdealResponseInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
