<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Identity2;
use Core\Utils\CoreHelper;

/**
 * Builder for model Identity2
 *
 * @see Identity2
 */
class Identity2Builder
{
    /**
     * @var Identity2
     */
    private $instance;

    private function __construct(Identity2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Identity 2 Builder object.
     *
     * @param string $fullLegalName
     * @param string $name
     */
    public static function init(string $fullLegalName, string $name): self
    {
        return new self(new Identity2($fullLegalName, $name));
    }

    /**
     * Initializes a new Identity 2 object.
     */
    public function build(): Identity2
    {
        return CoreHelper::clone($this->instance);
    }
}
