<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\IndividualDetails;
use AdyenLib\Models\ViasName2;
use AdyenLib\Models\ViasPersonalData2;
use Core\Utils\CoreHelper;

/**
 * Builder for model IndividualDetails
 *
 * @see IndividualDetails
 */
class IndividualDetailsBuilder
{
    /**
     * @var IndividualDetails
     */
    private $instance;

    private function __construct(IndividualDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Individual Details Builder object.
     */
    public static function init(): self
    {
        return new self(new IndividualDetails());
    }

    /**
     * Sets name field.
     *
     * @param ViasName2|null $value
     */
    public function name(?ViasName2 $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets personal Data field.
     *
     * @param ViasPersonalData2|null $value
     */
    public function personalData(?ViasPersonalData2 $value): self
    {
        $this->instance->setPersonalData($value);
        return $this;
    }

    /**
     * Initializes a new Individual Details object.
     */
    public function build(): IndividualDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
