<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\DonationAmount1;
use AdyenLib\Models\InPersonDonationSettings2;
use Core\Utils\CoreHelper;

/**
 * Builder for model InPersonDonationSettings2
 *
 * @see InPersonDonationSettings2
 */
class InPersonDonationSettings2Builder
{
    /**
     * @var InPersonDonationSettings2
     */
    private $instance;

    private function __construct(InPersonDonationSettings2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new In Person Donation Settings 2 Builder object.
     *
     * @param string $displayTextField
     * @param string $donationFlow
     */
    public static function init(string $displayTextField, string $donationFlow): self
    {
        return new self(new InPersonDonationSettings2($displayTextField, $donationFlow));
    }

    /**
     * Sets default Amount field.
     *
     * @param DonationAmount1|null $value
     */
    public function defaultAmount(?DonationAmount1 $value): self
    {
        $this->instance->setDefaultAmount($value);
        return $this;
    }

    /**
     * Sets donation Type field.
     *
     * @param string|null $value
     */
    public function donationType(?string $value): self
    {
        $this->instance->setDonationType($value);
        return $this;
    }

    /**
     * Sets merchant Accounts field.
     *
     * @param string[]|null $value
     */
    public function merchantAccounts(?array $value): self
    {
        $this->instance->setMerchantAccounts($value);
        return $this;
    }

    /**
     * Sets present Card Timeout Ms field.
     *
     * @param int|null $value
     */
    public function presentCardTimeoutMs(?int $value): self
    {
        $this->instance->setPresentCardTimeoutMs($value);
        return $this;
    }

    /**
     * Sets prompt Timeout Ms field.
     *
     * @param int|null $value
     */
    public function promptTimeoutMs(?int $value): self
    {
        $this->instance->setPromptTimeoutMs($value);
        return $this;
    }

    /**
     * Sets store Ids field.
     *
     * @param string[]|null $value
     */
    public function storeIds(?array $value): self
    {
        $this->instance->setStoreIds($value);
        return $this;
    }

    /**
     * Initializes a new In Person Donation Settings 2 object.
     */
    public function build(): InPersonDonationSettings2
    {
        return CoreHelper::clone($this->instance);
    }
}
