<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\InputResponse;
use AdyenLib\Models\InputResult2;
use AdyenLib\Models\OutputResult1;
use Core\Utils\CoreHelper;

/**
 * Builder for model InputResponse
 *
 * @see InputResponse
 */
class InputResponseBuilder
{
    /**
     * @var InputResponse
     */
    private $instance;

    private function __construct(InputResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Input Response Builder object.
     *
     * @param InputResult2 $inputResult
     */
    public static function init(InputResult2 $inputResult): self
    {
        return new self(new InputResponse($inputResult));
    }

    /**
     * Sets Output Result field.
     *
     * @param OutputResult1|null $value
     */
    public function outputResult(?OutputResult1 $value): self
    {
        $this->instance->setOutputResult($value);
        return $this;
    }

    /**
     * Initializes a new Input Response object.
     */
    public function build(): InputResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
