<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\InteracCardResponseInfo1;
use AdyenLib\Models\TransactionDescriptionResponseInfo1;
use Core\Utils\CoreHelper;

/**
 * Builder for model InteracCardResponseInfo1
 *
 * @see InteracCardResponseInfo1
 */
class InteracCardResponseInfo1Builder
{
    /**
     * @var InteracCardResponseInfo1
     */
    private $instance;

    private function __construct(InteracCardResponseInfo1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Interac Card Response Info 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new InteracCardResponseInfo1());
    }

    /**
     * Sets transaction Description field.
     *
     * @param TransactionDescriptionResponseInfo1|null $value
     */
    public function transactionDescription(?TransactionDescriptionResponseInfo1 $value): self
    {
        $this->instance->setTransactionDescription($value);
        return $this;
    }

    /**
     * Initializes a new Interac Card Response Info 1 object.
     */
    public function build(): InteracCardResponseInfo1
    {
        return CoreHelper::clone($this->instance);
    }
}
