<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\KYCCheckStatusData;
use AdyenLib\Models\KYCLegalArrangementCheckResult;
use Core\Utils\CoreHelper;

/**
 * Builder for model KYCLegalArrangementCheckResult
 *
 * @see KYCLegalArrangementCheckResult
 */
class KYCLegalArrangementCheckResultBuilder
{
    /**
     * @var KYCLegalArrangementCheckResult
     */
    private $instance;

    private function __construct(KYCLegalArrangementCheckResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new KYC Legal Arrangement Check Result Builder object.
     */
    public static function init(): self
    {
        return new self(new KYCLegalArrangementCheckResult());
    }

    /**
     * Sets checks field.
     *
     * @param KYCCheckStatusData[]|null $value
     */
    public function checks(?array $value): self
    {
        $this->instance->setChecks($value);
        return $this;
    }

    /**
     * Sets legal Arrangement Code field.
     *
     * @param string|null $value
     */
    public function legalArrangementCode(?string $value): self
    {
        $this->instance->setLegalArrangementCode($value);
        return $this;
    }

    /**
     * Initializes a new KYC Legal Arrangement Check Result object.
     */
    public function build(): KYCLegalArrangementCheckResult
    {
        return CoreHelper::clone($this->instance);
    }
}
