<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\KYCCheckStatusData;
use AdyenLib\Models\KYCPayoutMethodCheckResult;
use Core\Utils\CoreHelper;

/**
 * Builder for model KYCPayoutMethodCheckResult
 *
 * @see KYCPayoutMethodCheckResult
 */
class KYCPayoutMethodCheckResultBuilder
{
    /**
     * @var KYCPayoutMethodCheckResult
     */
    private $instance;

    private function __construct(KYCPayoutMethodCheckResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new KYC Payout Method Check Result Builder object.
     */
    public static function init(): self
    {
        return new self(new KYCPayoutMethodCheckResult());
    }

    /**
     * Sets checks field.
     *
     * @param KYCCheckStatusData[]|null $value
     */
    public function checks(?array $value): self
    {
        $this->instance->setChecks($value);
        return $this;
    }

    /**
     * Sets payout Method Code field.
     *
     * @param string|null $value
     */
    public function payoutMethodCode(?string $value): self
    {
        $this->instance->setPayoutMethodCode($value);
        return $this;
    }

    /**
     * Initializes a new KYC Payout Method Check Result object.
     */
    public function build(): KYCPayoutMethodCheckResult
    {
        return CoreHelper::clone($this->instance);
    }
}
