<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\MerchantAcquirerPair;
use Core\Utils\CoreHelper;

/**
 * Builder for model MerchantAcquirerPair
 *
 * @see MerchantAcquirerPair
 */
class MerchantAcquirerPairBuilder
{
    /**
     * @var MerchantAcquirerPair
     */
    private $instance;

    private function __construct(MerchantAcquirerPair $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Merchant Acquirer Pair Builder object.
     */
    public static function init(): self
    {
        return new self(new MerchantAcquirerPair());
    }

    /**
     * Sets acquirer Id field.
     *
     * @param string|null $value
     */
    public function acquirerId(?string $value): self
    {
        $this->instance->setAcquirerId($value);
        return $this;
    }

    /**
     * Sets merchant Id field.
     *
     * @param string|null $value
     */
    public function merchantId(?string $value): self
    {
        $this->instance->setMerchantId($value);
        return $this;
    }

    /**
     * Initializes a new Merchant Acquirer Pair object.
     */
    public function build(): MerchantAcquirerPair
    {
        return CoreHelper::clone($this->instance);
    }
}
