<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\MOLPay;
use Core\Utils\CoreHelper;

/**
 * Builder for model MOLPay
 *
 * @see MOLPay
 */
class MOLPayBuilder
{
    /**
     * @var MOLPay
     */
    private $instance;

    private function __construct(MOLPay $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new MOL Pay Builder object.
     *
     * @param string $issuer
     * @param string $type
     */
    public static function init(string $issuer, string $type): self
    {
        return new self(new MOLPay($issuer, $type));
    }

    /**
     * Sets checkout Attempt Id field.
     *
     * @param string|null $value
     */
    public function checkoutAttemptId(?string $value): self
    {
        $this->instance->setCheckoutAttemptId($value);
        return $this;
    }

    /**
     * Sets sdk Data field.
     *
     * @param string|null $value
     */
    public function sdkData(?string $value): self
    {
        $this->instance->setSdkData($value);
        return $this;
    }

    /**
     * Initializes a new MOL Pay object.
     */
    public function build(): MOLPay
    {
        return CoreHelper::clone($this->instance);
    }
}
