<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\OtherInfo1;
use Core\Utils\CoreHelper;

/**
 * Builder for model OtherInfo1
 *
 * @see OtherInfo1
 */
class OtherInfo1Builder
{
    /**
     * @var OtherInfo1
     */
    private $instance;

    private function __construct(OtherInfo1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Other Info 1 Builder object.
     *
     * @param string $descriptionOfIssue
     * @param string $subType
     * @param string $whatWasPurchased
     */
    public static function init(string $descriptionOfIssue, string $subType, string $whatWasPurchased): self
    {
        return new self(new OtherInfo1($descriptionOfIssue, $subType, $whatWasPurchased));
    }

    /**
     * Initializes a new Other Info 1 object.
     */
    public function build(): OtherInfo1
    {
        return CoreHelper::clone($this->instance);
    }
}
