<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\CardOrderItem;
use AdyenLib\Models\PaginatedGetCardOrderItemResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model PaginatedGetCardOrderItemResponse
 *
 * @see PaginatedGetCardOrderItemResponse
 */
class PaginatedGetCardOrderItemResponseBuilder
{
    /**
     * @var PaginatedGetCardOrderItemResponse
     */
    private $instance;

    private function __construct(PaginatedGetCardOrderItemResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Paginated Get Card Order Item Response Builder object.
     *
     * @param CardOrderItem[] $data
     * @param bool $hasNext
     * @param bool $hasPrevious
     */
    public static function init(array $data, bool $hasNext, bool $hasPrevious): self
    {
        return new self(new PaginatedGetCardOrderItemResponse($data, $hasNext, $hasPrevious));
    }

    /**
     * Initializes a new Paginated Get Card Order Item Response object.
     */
    public function build(): PaginatedGetCardOrderItemResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
