<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\PatchableAmountDTO;
use AdyenLib\Models\PatchableTopUpAmount;
use Core\Utils\CoreHelper;

/**
 * Builder for model PatchableTopUpAmount
 *
 * @see PatchableTopUpAmount
 */
class PatchableTopUpAmountBuilder
{
    /**
     * @var PatchableTopUpAmount
     */
    private $instance;

    private function __construct(PatchableTopUpAmount $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Patchable Top Up Amount Builder object.
     */
    public static function init(): self
    {
        return new self(new PatchableTopUpAmount());
    }

    /**
     * Sets fixed field.
     *
     * @param PatchableAmountDTO|null $value
     */
    public function fixed(?PatchableAmountDTO $value): self
    {
        $this->instance->setFixed($value);
        return $this;
    }

    /**
     * Unsets fixed field.
     */
    public function unsetFixed(): self
    {
        $this->instance->unsetFixed();
        return $this;
    }

    /**
     * Sets target field.
     *
     * @param PatchableAmountDTO|null $value
     */
    public function target(?PatchableAmountDTO $value): self
    {
        $this->instance->setTarget($value);
        return $this;
    }

    /**
     * Unsets target field.
     */
    public function unsetTarget(): self
    {
        $this->instance->unsetTarget();
        return $this;
    }

    /**
     * Initializes a new Patchable Top Up Amount object.
     */
    public function build(): PatchableTopUpAmount
    {
        return CoreHelper::clone($this->instance);
    }
}
