<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Amount33;
use AdyenLib\Models\LineItem;
use AdyenLib\Models\PaymentCaptureResponse;
use AdyenLib\Models\PlatformChargebackLogic;
use AdyenLib\Models\Split;
use AdyenLib\Models\SubMerchantInfo;
use Core\Utils\CoreHelper;

/**
 * Builder for model PaymentCaptureResponse
 *
 * @see PaymentCaptureResponse
 */
class PaymentCaptureResponseBuilder
{
    /**
     * @var PaymentCaptureResponse
     */
    private $instance;

    private function __construct(PaymentCaptureResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Capture Response Builder object.
     *
     * @param Amount33 $amount
     * @param string $merchantAccount
     * @param string $paymentPspReference
     * @param string $pspReference
     */
    public static function init(
        Amount33 $amount,
        string $merchantAccount,
        string $paymentPspReference,
        string $pspReference
    ): self {
        return new self(new PaymentCaptureResponse($amount, $merchantAccount, $paymentPspReference, $pspReference));
    }

    /**
     * Sets line Items field.
     *
     * @param LineItem[]|null $value
     */
    public function lineItems(?array $value): self
    {
        $this->instance->setLineItems($value);
        return $this;
    }

    /**
     * Sets platform Chargeback Logic field.
     *
     * @param PlatformChargebackLogic|null $value
     */
    public function platformChargebackLogic(?PlatformChargebackLogic $value): self
    {
        $this->instance->setPlatformChargebackLogic($value);
        return $this;
    }

    /**
     * Sets reference field.
     *
     * @param string|null $value
     */
    public function reference(?string $value): self
    {
        $this->instance->setReference($value);
        return $this;
    }

    /**
     * Sets splits field.
     *
     * @param Split[]|null $value
     */
    public function splits(?array $value): self
    {
        $this->instance->setSplits($value);
        return $this;
    }

    /**
     * Sets sub Merchants field.
     *
     * @param SubMerchantInfo[]|null $value
     */
    public function subMerchants(?array $value): self
    {
        $this->instance->setSubMerchants($value);
        return $this;
    }

    /**
     * Initializes a new Payment Capture Response object.
     */
    public function build(): PaymentCaptureResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
