<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\CardData1;
use AdyenLib\Models\CheckData1;
use AdyenLib\Models\MobileData1;
use AdyenLib\Models\PaymentInstrumentData1;
use AdyenLib\Models\StoredValueAccountID;
use Core\Utils\CoreHelper;

/**
 * Builder for model PaymentInstrumentData1
 *
 * @see PaymentInstrumentData1
 */
class PaymentInstrumentData1Builder
{
    /**
     * @var PaymentInstrumentData1
     */
    private $instance;

    private function __construct(PaymentInstrumentData1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Instrument Data 1 Builder object.
     *
     * @param string $paymentInstrumentType
     */
    public static function init(string $paymentInstrumentType): self
    {
        return new self(new PaymentInstrumentData1($paymentInstrumentType));
    }

    /**
     * Sets Protected Card Data field.
     *
     * @param string|null $value
     */
    public function protectedCardData(?string $value): self
    {
        $this->instance->setProtectedCardData($value);
        return $this;
    }

    /**
     * Sets Card Data field.
     *
     * @param CardData1|null $value
     */
    public function cardData(?CardData1 $value): self
    {
        $this->instance->setCardData($value);
        return $this;
    }

    /**
     * Sets Check Data field.
     *
     * @param CheckData1|null $value
     */
    public function checkData(?CheckData1 $value): self
    {
        $this->instance->setCheckData($value);
        return $this;
    }

    /**
     * Sets Mobile Data field.
     *
     * @param MobileData1|null $value
     */
    public function mobileData(?MobileData1 $value): self
    {
        $this->instance->setMobileData($value);
        return $this;
    }

    /**
     * Sets Stored Value Account ID field.
     *
     * @param StoredValueAccountID|null $value
     */
    public function storedValueAccountID(?StoredValueAccountID $value): self
    {
        $this->instance->setStoredValueAccountID($value);
        return $this;
    }

    /**
     * Initializes a new Payment Instrument Data 1 object.
     */
    public function build(): PaymentInstrumentData1
    {
        return CoreHelper::clone($this->instance);
    }
}
