<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\PayoutScheduleResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model PayoutScheduleResponse
 *
 * @see PayoutScheduleResponse
 */
class PayoutScheduleResponseBuilder
{
    /**
     * @var PayoutScheduleResponse
     */
    private $instance;

    private function __construct(PayoutScheduleResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payout Schedule Response Builder object.
     */
    public static function init(): self
    {
        return new self(new PayoutScheduleResponse());
    }

    /**
     * Sets next Scheduled Payout field.
     *
     * @param \DateTime|null $value
     */
    public function nextScheduledPayout(?\DateTime $value): self
    {
        $this->instance->setNextScheduledPayout($value);
        return $this;
    }

    /**
     * Sets schedule field.
     *
     * @param string|null $value
     */
    public function schedule(?string $value): self
    {
        $this->instance->setSchedule($value);
        return $this;
    }

    /**
     * Initializes a new Payout Schedule Response object.
     */
    public function build(): PayoutScheduleResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
