<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\PhoneInfo2;
use Core\Utils\CoreHelper;

/**
 * Builder for model PhoneInfo2
 *
 * @see PhoneInfo2
 */
class PhoneInfo2Builder
{
    /**
     * @var PhoneInfo2
     */
    private $instance;

    private function __construct(PhoneInfo2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Phone Info 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new PhoneInfo2());
    }

    /**
     * Sets hashed Number field.
     *
     * @param string|null $value
     */
    public function hashedNumber(?string $value): self
    {
        $this->instance->setHashedNumber($value);
        return $this;
    }

    /**
     * Sets last Four Digits field.
     *
     * @param string|null $value
     */
    public function lastFourDigits(?string $value): self
    {
        $this->instance->setLastFourDigits($value);
        return $this;
    }

    /**
     * Sets number field.
     *
     * @param string|null $value
     */
    public function number(?string $value): self
    {
        $this->instance->setNumber($value);
        return $this;
    }

    /**
     * Initializes a new Phone Info 2 object.
     */
    public function build(): PhoneInfo2
    {
        return CoreHelper::clone($this->instance);
    }
}
