<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\PSELatam;
use Core\Utils\CoreHelper;

/**
 * Builder for model PSELatam
 *
 * @see PSELatam
 */
class PSELatamBuilder
{
    /**
     * @var PSELatam
     */
    private $instance;

    private function __construct(PSELatam $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new PSE Latam Builder object.
     *
     * @param string $bank
     * @param string $clientType
     * @param string $identification
     * @param string $identificationType
     */
    public static function init(
        string $bank,
        string $clientType,
        string $identification,
        string $identificationType
    ): self {
        return new self(new PSELatam($bank, $clientType, $identification, $identificationType));
    }

    /**
     * Sets checkout Attempt Id field.
     *
     * @param string|null $value
     */
    public function checkoutAttemptId(?string $value): self
    {
        $this->instance->setCheckoutAttemptId($value);
        return $this;
    }

    /**
     * Sets sdk Data field.
     *
     * @param string|null $value
     */
    public function sdkData(?string $value): self
    {
        $this->instance->setSdkData($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Initializes a new PSE Latam object.
     */
    public function build(): PSELatam
    {
        return CoreHelper::clone($this->instance);
    }
}
