<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\DelegatedAuthenticationData1;
use AdyenLib\Models\RegisterSCARequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model RegisterSCARequest
 *
 * @see RegisterSCARequest
 */
class RegisterSCARequestBuilder
{
    /**
     * @var RegisterSCARequest
     */
    private $instance;

    private function __construct(RegisterSCARequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Register SCA Request Builder object.
     *
     * @param string $paymentInstrumentId
     * @param DelegatedAuthenticationData1 $strongCustomerAuthentication
     */
    public static function init(
        string $paymentInstrumentId,
        DelegatedAuthenticationData1 $strongCustomerAuthentication
    ): self {
        return new self(new RegisterSCARequest($paymentInstrumentId, $strongCustomerAuthentication));
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new Register SCA Request object.
     */
    public function build(): RegisterSCARequest
    {
        return CoreHelper::clone($this->instance);
    }
}
