<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\RegisterSCAFinalResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model RegisterSCAFinalResponse
 *
 * @see RegisterSCAFinalResponse
 */
class RegisterSCAFinalResponseBuilder
{
    /**
     * @var RegisterSCAFinalResponse
     */
    private $instance;

    private function __construct(RegisterSCAFinalResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Register SCA Final Response Builder object.
     */
    public static function init(): self
    {
        return new self(new RegisterSCAFinalResponse());
    }

    /**
     * Sets success field.
     *
     * @param bool|null $value
     */
    public function success(?bool $value): self
    {
        $this->instance->setSuccess($value);
        return $this;
    }

    /**
     * Initializes a new Register SCA Final Response object.
     */
    public function build(): RegisterSCAFinalResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
