<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\SaleTerminalData1;
use Core\Utils\CoreHelper;

/**
 * Builder for model SaleTerminalData1
 *
 * @see SaleTerminalData1
 */
class SaleTerminalData1Builder
{
    /**
     * @var SaleTerminalData1
     */
    private $instance;

    private function __construct(SaleTerminalData1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Sale Terminal Data 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new SaleTerminalData1());
    }

    /**
     * Sets Totals Group ID field.
     *
     * @param string|null $value
     */
    public function totalsGroupID(?string $value): self
    {
        $this->instance->setTotalsGroupID($value);
        return $this;
    }

    /**
     * Initializes a new Sale Terminal Data 1 object.
     */
    public function build(): SaleTerminalData1
    {
        return CoreHelper::clone($this->instance);
    }
}
