<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\SGLocalAccountIdentification1;
use Core\Utils\CoreHelper;

/**
 * Builder for model SGLocalAccountIdentification1
 *
 * @see SGLocalAccountIdentification1
 */
class SGLocalAccountIdentification1Builder
{
    /**
     * @var SGLocalAccountIdentification1
     */
    private $instance;

    private function __construct(SGLocalAccountIdentification1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new SG Local Account Identification 1 Builder object.
     *
     * @param string $accountNumber
     * @param string $bic
     */
    public static function init(string $accountNumber, string $bic): self
    {
        return new self(new SGLocalAccountIdentification1($accountNumber, $bic));
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Initializes a new SG Local Account Identification 1 object.
     */
    public function build(): SGLocalAccountIdentification1
    {
        return CoreHelper::clone($this->instance);
    }
}
