<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\ShopperTaxInfo2;
use Core\Utils\CoreHelper;

/**
 * Builder for model ShopperTaxInfo2
 *
 * @see ShopperTaxInfo2
 */
class ShopperTaxInfo2Builder
{
    /**
     * @var ShopperTaxInfo2
     */
    private $instance;

    private function __construct(ShopperTaxInfo2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Shopper Tax Info 2 Builder object.
     *
     * @param string $taxCountryCode
     * @param string $taxIdentificationNumber
     */
    public static function init(string $taxCountryCode, string $taxIdentificationNumber): self
    {
        return new self(new ShopperTaxInfo2($taxCountryCode, $taxIdentificationNumber));
    }

    /**
     * Initializes a new Shopper Tax Info 2 object.
     */
    public function build(): ShopperTaxInfo2
    {
        return CoreHelper::clone($this->instance);
    }
}
