<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Address14;
use AdyenLib\Models\Store1;
use Core\Utils\CoreHelper;

/**
 * Builder for model Store1
 *
 * @see Store1
 */
class Store1Builder
{
    /**
     * @var Store1
     */
    private $instance;

    private function __construct(Store1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Store 1 Builder object.
     *
     * @param string $store
     */
    public static function init(string $store): self
    {
        return new self(new Store1($store));
    }

    /**
     * Sets address field.
     *
     * @param Address14|null $value
     */
    public function address(?Address14 $value): self
    {
        $this->instance->setAddress($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets in Store Terminals field.
     *
     * @param string[]|null $value
     */
    public function inStoreTerminals(?array $value): self
    {
        $this->instance->setInStoreTerminals($value);
        return $this;
    }

    /**
     * Sets merchant Account Code field.
     *
     * @param string|null $value
     */
    public function merchantAccountCode(?string $value): self
    {
        $this->instance->setMerchantAccountCode($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new Store 1 object.
     */
    public function build(): Store1
    {
        return CoreHelper::clone($this->instance);
    }
}
