<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\SaleData1;
use AdyenLib\Models\StoredValueData;
use AdyenLib\Models\StoredValueRequest2;
use Core\Utils\CoreHelper;

/**
 * Builder for model StoredValueRequest2
 *
 * @see StoredValueRequest2
 */
class StoredValueRequest2Builder
{
    /**
     * @var StoredValueRequest2
     */
    private $instance;

    private function __construct(StoredValueRequest2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Stored Value Request 2 Builder object.
     *
     * @param SaleData1 $saleData
     * @param StoredValueData[] $storedValueData
     */
    public static function init(SaleData1 $saleData, array $storedValueData): self
    {
        return new self(new StoredValueRequest2($saleData, $storedValueData));
    }

    /**
     * Initializes a new Stored Value Request 2 object.
     */
    public function build(): StoredValueRequest2
    {
        return CoreHelper::clone($this->instance);
    }
}
