<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\SubjectErasureByPspReferenceRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model SubjectErasureByPspReferenceRequest
 *
 * @see SubjectErasureByPspReferenceRequest
 */
class SubjectErasureByPspReferenceRequestBuilder
{
    /**
     * @var SubjectErasureByPspReferenceRequest
     */
    private $instance;

    private function __construct(SubjectErasureByPspReferenceRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Subject Erasure By Psp Reference Request Builder object.
     */
    public static function init(): self
    {
        return new self(new SubjectErasureByPspReferenceRequest());
    }

    /**
     * Sets force Erasure field.
     *
     * @param bool|null $value
     */
    public function forceErasure(?bool $value): self
    {
        $this->instance->setForceErasure($value);
        return $this;
    }

    /**
     * Sets merchant Account field.
     *
     * @param string|null $value
     */
    public function merchantAccount(?string $value): self
    {
        $this->instance->setMerchantAccount($value);
        return $this;
    }

    /**
     * Sets psp Reference field.
     *
     * @param string|null $value
     */
    public function pspReference(?string $value): self
    {
        $this->instance->setPspReference($value);
        return $this;
    }

    /**
     * Initializes a new Subject Erasure By Psp Reference Request object.
     */
    public function build(): SubjectErasureByPspReferenceRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
