<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Association;
use AdyenLib\Models\SubmitScaAssociationResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model SubmitScaAssociationResponse
 *
 * @see SubmitScaAssociationResponse
 */
class SubmitScaAssociationResponseBuilder
{
    /**
     * @var SubmitScaAssociationResponse
     */
    private $instance;

    private function __construct(SubmitScaAssociationResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Submit Sca Association Response Builder object.
     *
     * @param Association[] $scaAssociations
     */
    public static function init(array $scaAssociations): self
    {
        return new self(new SubmitScaAssociationResponse($scaAssociations));
    }

    /**
     * Initializes a new Submit Sca Association Response object.
     */
    public function build(): SubmitScaAssociationResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
