<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\SuspendAccountHolderRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model SuspendAccountHolderRequest
 *
 * @see SuspendAccountHolderRequest
 */
class SuspendAccountHolderRequestBuilder
{
    /**
     * @var SuspendAccountHolderRequest
     */
    private $instance;

    private function __construct(SuspendAccountHolderRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Suspend Account Holder Request Builder object.
     *
     * @param string $accountHolderCode
     */
    public static function init(string $accountHolderCode): self
    {
        return new self(new SuspendAccountHolderRequest($accountHolderCode));
    }

    /**
     * Initializes a new Suspend Account Holder Request object.
     */
    public function build(): SuspendAccountHolderRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
