<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\SweepSchedule;
use Core\Utils\CoreHelper;

/**
 * Builder for model SweepSchedule
 *
 * @see SweepSchedule
 */
class SweepScheduleBuilder
{
    /**
     * @var SweepSchedule
     */
    private $instance;

    private function __construct(SweepSchedule $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Sweep Schedule Builder object.
     *
     * @param string $type
     */
    public static function init(string $type): self
    {
        return new self(new SweepSchedule($type));
    }

    /**
     * Sets cron Expression field.
     *
     * @param string|null $value
     */
    public function cronExpression(?string $value): self
    {
        $this->instance->setCronExpression($value);
        return $this;
    }

    /**
     * Initializes a new Sweep Schedule object.
     */
    public function build(): SweepSchedule
    {
        return CoreHelper::clone($this->instance);
    }
}
