<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\SwishInfo2;
use Core\Utils\CoreHelper;

/**
 * Builder for model SwishInfo2
 *
 * @see SwishInfo2
 */
class SwishInfo2Builder
{
    /**
     * @var SwishInfo2
     */
    private $instance;

    private function __construct(SwishInfo2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Swish Info 2 Builder object.
     *
     * @param string $swishNumber
     */
    public static function init(string $swishNumber): self
    {
        return new self(new SwishInfo2($swishNumber));
    }

    /**
     * Initializes a new Swish Info 2 object.
     */
    public function build(): SwishInfo2
    {
        return CoreHelper::clone($this->instance);
    }
}
