<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\SwishResponseInfo2;
use Core\Utils\CoreHelper;

/**
 * Builder for model SwishResponseInfo2
 *
 * @see SwishResponseInfo2
 */
class SwishResponseInfo2Builder
{
    /**
     * @var SwishResponseInfo2
     */
    private $instance;

    private function __construct(SwishResponseInfo2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Swish Response Info 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new SwishResponseInfo2());
    }

    /**
     * Sets swish Number field.
     *
     * @param string|null $value
     */
    public function swishNumber(?string $value): self
    {
        $this->instance->setSwishNumber($value);
        return $this;
    }

    /**
     * Initializes a new Swish Response Info 2 object.
     */
    public function build(): SwishResponseInfo2
    {
        return CoreHelper::clone($this->instance);
    }
}
