<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\TokenRequestorsRestriction;
use Core\Utils\CoreHelper;

/**
 * Builder for model TokenRequestorsRestriction
 *
 * @see TokenRequestorsRestriction
 */
class TokenRequestorsRestrictionBuilder
{
    /**
     * @var TokenRequestorsRestriction
     */
    private $instance;

    private function __construct(TokenRequestorsRestriction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Token Requestors Restriction Builder object.
     *
     * @param string $operation
     */
    public static function init(string $operation): self
    {
        return new self(new TokenRequestorsRestriction($operation));
    }

    /**
     * Sets value field.
     *
     * @param string[]|null $value
     */
    public function value(?array $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Initializes a new Token Requestors Restriction object.
     */
    public function build(): TokenRequestorsRestriction
    {
        return CoreHelper::clone($this->instance);
    }
}
