<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Amount17;
use AdyenLib\Models\TotalAmountRestriction1;
use Core\Utils\CoreHelper;

/**
 * Builder for model TotalAmountRestriction1
 *
 * @see TotalAmountRestriction1
 */
class TotalAmountRestriction1Builder
{
    /**
     * @var TotalAmountRestriction1
     */
    private $instance;

    private function __construct(TotalAmountRestriction1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Total Amount Restriction 1 Builder object.
     *
     * @param string $operation
     */
    public static function init(string $operation): self
    {
        return new self(new TotalAmountRestriction1($operation));
    }

    /**
     * Sets value field.
     *
     * @param Amount17|null $value
     */
    public function value(?Amount17 $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Initializes a new Total Amount Restriction 1 object.
     */
    public function build(): TotalAmountRestriction1
    {
        return CoreHelper::clone($this->instance);
    }
}
