<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Amount17;
use AdyenLib\Models\BankCategoryData;
use AdyenLib\Models\CounterpartyV31;
use AdyenLib\Models\DirectDebitInformation1;
use AdyenLib\Models\ExecutionDate1;
use AdyenLib\Models\InternalCategoryData;
use AdyenLib\Models\IssuedCard;
use AdyenLib\Models\PaymentInstrument3;
use AdyenLib\Models\PlatformPayment;
use AdyenLib\Models\ResourceReference1;
use AdyenLib\Models\ResourceReference5;
use AdyenLib\Models\Transfer;
use AdyenLib\Models\TransferReview1;
use AdyenLib\Models\UltimatePartyIdentification1;
use Core\Utils\CoreHelper;

/**
 * Builder for model Transfer
 *
 * @see Transfer
 */
class TransferBuilder
{
    /**
     * @var Transfer
     */
    private $instance;

    private function __construct(Transfer $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transfer Builder object.
     *
     * @param Amount17 $amount
     * @param string $category
     * @param CounterpartyV31 $counterparty
     * @param string $status
     */
    public static function init(
        Amount17 $amount,
        string $category,
        CounterpartyV31 $counterparty,
        string $status
    ): self {
        return new self(new Transfer($amount, $category, $counterparty, $status));
    }

    /**
     * Sets account Holder field.
     *
     * @param ResourceReference5|null $value
     */
    public function accountHolder(?ResourceReference5 $value): self
    {
        $this->instance->setAccountHolder($value);
        return $this;
    }

    /**
     * Sets balance Account field.
     *
     * @param ResourceReference1|null $value
     */
    public function balanceAccount(?ResourceReference1 $value): self
    {
        $this->instance->setBalanceAccount($value);
        return $this;
    }

    /**
     * Sets category Data field.
     *
     * @param BankCategoryData|InternalCategoryData|IssuedCard|PlatformPayment|null $value
     */
    public function categoryData($value): self
    {
        $this->instance->setCategoryData($value);
        return $this;
    }

    /**
     * Sets created At field.
     *
     * @param \DateTime|null $value
     */
    public function createdAt(?\DateTime $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets creation Date field.
     *
     * @param \DateTime|null $value
     */
    public function creationDate(?\DateTime $value): self
    {
        $this->instance->setCreationDate($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets direct Debit Information field.
     *
     * @param DirectDebitInformation1|null $value
     */
    public function directDebitInformation(?DirectDebitInformation1 $value): self
    {
        $this->instance->setDirectDebitInformation($value);
        return $this;
    }

    /**
     * Sets direction field.
     *
     * @param string|null $value
     */
    public function direction(?string $value): self
    {
        $this->instance->setDirection($value);
        return $this;
    }

    /**
     * Sets execution Date field.
     *
     * @param ExecutionDate1|null $value
     */
    public function executionDate(?ExecutionDate1 $value): self
    {
        $this->instance->setExecutionDate($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets payment Instrument field.
     *
     * @param PaymentInstrument3|null $value
     */
    public function paymentInstrument(?PaymentInstrument3 $value): self
    {
        $this->instance->setPaymentInstrument($value);
        return $this;
    }

    /**
     * Sets reason field.
     *
     * @param string|null $value
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Sets reference field.
     *
     * @param string|null $value
     */
    public function reference(?string $value): self
    {
        $this->instance->setReference($value);
        return $this;
    }

    /**
     * Sets reference For Beneficiary field.
     *
     * @param string|null $value
     */
    public function referenceForBeneficiary(?string $value): self
    {
        $this->instance->setReferenceForBeneficiary($value);
        return $this;
    }

    /**
     * Sets review field.
     *
     * @param TransferReview1|null $value
     */
    public function review(?TransferReview1 $value): self
    {
        $this->instance->setReview($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets ultimate Party field.
     *
     * @param UltimatePartyIdentification1|null $value
     */
    public function ultimateParty(?UltimatePartyIdentification1 $value): self
    {
        $this->instance->setUltimateParty($value);
        return $this;
    }

    /**
     * Initializes a new Transfer object.
     */
    public function build(): Transfer
    {
        return CoreHelper::clone($this->instance);
    }
}
