<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Links21;
use AdyenLib\Models\Transaction;
use AdyenLib\Models\TransactionSearchResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model TransactionSearchResponse
 *
 * @see TransactionSearchResponse
 */
class TransactionSearchResponseBuilder
{
    /**
     * @var TransactionSearchResponse
     */
    private $instance;

    private function __construct(TransactionSearchResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transaction Search Response Builder object.
     */
    public static function init(): self
    {
        return new self(new TransactionSearchResponse());
    }

    /**
     * Sets links field.
     *
     * @param Links21|null $value
     */
    public function links(?Links21 $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Sets data field.
     *
     * @param Transaction[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new Transaction Search Response object.
     */
    public function build(): TransactionSearchResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
