<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\BankCategoryData;
use AdyenLib\Models\InternalCategoryData;
use AdyenLib\Models\IssuedCard;
use AdyenLib\Models\PlatformPayment;
use AdyenLib\Models\TransferView;
use Core\Utils\CoreHelper;

/**
 * Builder for model TransferView
 *
 * @see TransferView
 */
class TransferViewBuilder
{
    /**
     * @var TransferView
     */
    private $instance;

    private function __construct(TransferView $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transfer View Builder object.
     *
     * @param string $reference
     */
    public static function init(string $reference): self
    {
        return new self(new TransferView($reference));
    }

    /**
     * Sets category Data field.
     *
     * @param BankCategoryData|InternalCategoryData|IssuedCard|PlatformPayment|null $value
     */
    public function categoryData($value): self
    {
        $this->instance->setCategoryData($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Initializes a new Transfer View object.
     */
    public function build(): TransferView
    {
        return CoreHelper::clone($this->instance);
    }
}
