<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\Address41;
use AdyenLib\Models\Address51;
use AdyenLib\Models\TaxInformation;
use AdyenLib\Models\Trust;
use AdyenLib\Models\UndefinedBeneficiary;
use Core\Utils\CoreHelper;

/**
 * Builder for model Trust
 *
 * @see Trust
 */
class TrustBuilder
{
    /**
     * @var Trust
     */
    private $instance;

    private function __construct(Trust $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Trust Builder object.
     *
     * @param string $countryOfGoverningLaw
     * @param string $name
     * @param Address51 $registeredAddress
     * @param string $type
     */
    public static function init(
        string $countryOfGoverningLaw,
        string $name,
        Address51 $registeredAddress,
        string $type
    ): self {
        return new self(new Trust($countryOfGoverningLaw, $name, $registeredAddress, $type));
    }

    /**
     * Sets date Of Incorporation field.
     *
     * @param string|null $value
     */
    public function dateOfIncorporation(?string $value): self
    {
        $this->instance->setDateOfIncorporation($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets doing Business As field.
     *
     * @param string|null $value
     */
    public function doingBusinessAs(?string $value): self
    {
        $this->instance->setDoingBusinessAs($value);
        return $this;
    }

    /**
     * Sets doing Business As Absent field.
     *
     * @param bool|null $value
     */
    public function doingBusinessAsAbsent(?bool $value): self
    {
        $this->instance->setDoingBusinessAsAbsent($value);
        return $this;
    }

    /**
     * Unsets doing Business As Absent field.
     */
    public function unsetDoingBusinessAsAbsent(): self
    {
        $this->instance->unsetDoingBusinessAsAbsent();
        return $this;
    }

    /**
     * Sets principal Place Of Business field.
     *
     * @param Address41|null $value
     */
    public function principalPlaceOfBusiness(?Address41 $value): self
    {
        $this->instance->setPrincipalPlaceOfBusiness($value);
        return $this;
    }

    /**
     * Sets registration Number field.
     *
     * @param string|null $value
     */
    public function registrationNumber(?string $value): self
    {
        $this->instance->setRegistrationNumber($value);
        return $this;
    }

    /**
     * Sets tax Information field.
     *
     * @param TaxInformation[]|null $value
     */
    public function taxInformation(?array $value): self
    {
        $this->instance->setTaxInformation($value);
        return $this;
    }

    /**
     * Sets undefined Beneficiary Info field.
     *
     * @param UndefinedBeneficiary[]|null $value
     */
    public function undefinedBeneficiaryInfo(?array $value): self
    {
        $this->instance->setUndefinedBeneficiaryInfo($value);
        return $this;
    }

    /**
     * Sets vat Absence Reason field.
     *
     * @param string|null $value
     */
    public function vatAbsenceReason(?string $value): self
    {
        $this->instance->setVatAbsenceReason($value);
        return $this;
    }

    /**
     * Sets vat Number field.
     *
     * @param string|null $value
     */
    public function vatNumber(?string $value): self
    {
        $this->instance->setVatNumber($value);
        return $this;
    }

    /**
     * Initializes a new Trust object.
     */
    public function build(): Trust
    {
        return CoreHelper::clone($this->instance);
    }
}
