<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\UKLocalAccountIdentification1;
use Core\Utils\CoreHelper;

/**
 * Builder for model UKLocalAccountIdentification1
 *
 * @see UKLocalAccountIdentification1
 */
class UKLocalAccountIdentification1Builder
{
    /**
     * @var UKLocalAccountIdentification1
     */
    private $instance;

    private function __construct(UKLocalAccountIdentification1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new UK Local Account Identification 1 Builder object.
     *
     * @param string $accountNumber
     * @param string $sortCode
     */
    public static function init(string $accountNumber, string $sortCode): self
    {
        return new self(new UKLocalAccountIdentification1($accountNumber, $sortCode));
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Initializes a new UK Local Account Identification 1 object.
     */
    public function build(): UKLocalAccountIdentification1
    {
        return CoreHelper::clone($this->instance);
    }
}
