<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\RemediatingAction;
use AdyenLib\Models\VerificationErrorRecursive;
use Core\Utils\CoreHelper;

/**
 * Builder for model VerificationErrorRecursive
 *
 * @see VerificationErrorRecursive
 */
class VerificationErrorRecursiveBuilder
{
    /**
     * @var VerificationErrorRecursive
     */
    private $instance;

    private function __construct(VerificationErrorRecursive $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Verification Error Recursive Builder object.
     */
    public static function init(): self
    {
        return new self(new VerificationErrorRecursive());
    }

    /**
     * Sets capabilities field.
     *
     * @param string[]|null $value
     */
    public function capabilities(?array $value): self
    {
        $this->instance->setCapabilities($value);
        return $this;
    }

    /**
     * Sets code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets remediating Actions field.
     *
     * @param RemediatingAction[]|null $value
     */
    public function remediatingActions(?array $value): self
    {
        $this->instance->setRemediatingActions($value);
        return $this;
    }

    /**
     * Initializes a new Verification Error Recursive object.
     */
    public function build(): VerificationErrorRecursive
    {
        return CoreHelper::clone($this->instance);
    }
}
