<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\VerificationDeadline;
use Core\Utils\CoreHelper;

/**
 * Builder for model VerificationDeadline
 *
 * @see VerificationDeadline
 */
class VerificationDeadlineBuilder
{
    /**
     * @var VerificationDeadline
     */
    private $instance;

    private function __construct(VerificationDeadline $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Verification Deadline Builder object.
     *
     * @param string[] $capabilities
     * @param \DateTime $expiresAt
     */
    public static function init(array $capabilities, \DateTime $expiresAt): self
    {
        return new self(new VerificationDeadline($capabilities, $expiresAt));
    }

    /**
     * Sets entity Ids field.
     *
     * @param string[]|null $value
     */
    public function entityIds(?array $value): self
    {
        $this->instance->setEntityIds($value);
        return $this;
    }

    /**
     * Initializes a new Verification Deadline object.
     */
    public function build(): VerificationDeadline
    {
        return CoreHelper::clone($this->instance);
    }
}
