<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\ViasAddress2;
use Core\Utils\CoreHelper;

/**
 * Builder for model ViasAddress2
 *
 * @see ViasAddress2
 */
class ViasAddress2Builder
{
    /**
     * @var ViasAddress2
     */
    private $instance;

    private function __construct(ViasAddress2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Vias Address 2 Builder object.
     *
     * @param string $country
     */
    public static function init(string $country): self
    {
        return new self(new ViasAddress2($country));
    }

    /**
     * Sets city field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets house Number Or Name field.
     *
     * @param string|null $value
     */
    public function houseNumberOrName(?string $value): self
    {
        $this->instance->setHouseNumberOrName($value);
        return $this;
    }

    /**
     * Sets postal Code field.
     *
     * @param string|null $value
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Sets state Or Province field.
     *
     * @param string|null $value
     */
    public function stateOrProvince(?string $value): self
    {
        $this->instance->setStateOrProvince($value);
        return $this;
    }

    /**
     * Sets street field.
     *
     * @param string|null $value
     */
    public function street(?string $value): self
    {
        $this->instance->setStreet($value);
        return $this;
    }

    /**
     * Initializes a new Vias Address 2 object.
     */
    public function build(): ViasAddress2
    {
        return CoreHelper::clone($this->instance);
    }
}
