<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models\Builders;

use AdyenLib\Models\WebDataExemption;
use Core\Utils\CoreHelper;

/**
 * Builder for model WebDataExemption
 *
 * @see WebDataExemption
 */
class WebDataExemptionBuilder
{
    /**
     * @var WebDataExemption
     */
    private $instance;

    private function __construct(WebDataExemption $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Web Data Exemption Builder object.
     */
    public static function init(): self
    {
        return new self(new WebDataExemption());
    }

    /**
     * Sets reason field.
     *
     * @param string|null $value
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Initializes a new Web Data Exemption object.
     */
    public function build(): WebDataExemption
    {
        return CoreHelper::clone($this->instance);
    }
}
