<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Apis;

use AdyenLib\Exceptions\ApiException;
use AdyenLib\Exceptions\DefaultErrorResponseEntityException;
use AdyenLib\Models\BalanceTransferRequest;
use AdyenLib\Models\BalanceTransferResponse;
use AdyenLib\Server;
use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;

class BalanceTransfersApi extends BaseApi
{
    /**
     * Performs a balance transfer between merchant accounts. The following conditions must be met before
     * you can successfully transfer balances:
     * * The source and destination merchant accounts must be under the same company account and legal
     * entity.
     * * The source merchant account must have sufficient funds.
     * * The source and destination merchant accounts must have at least one common processing currency.
     * \n\n
     * When sending multiple API requests with the same source and destination merchant accounts, send the
     * requests sequentially and *not* in parallel. Some requests may not be processed if the requests are
     * sent in parallel.
     *
     *
     * @param BalanceTransferRequest $body
     *
     * @return BalanceTransferResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function postBalanceTransfers(BalanceTransferRequest $body): BalanceTransferResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/balanceTransfers')
            ->server(Server::DEFAULT11)
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('401', ErrorType::init('Unauthorized', DefaultErrorResponseEntityException::class))
            ->throwErrorOn(
                '422',
                ErrorType::init(
                    'Unprocessable Content - A request validation error.',
                    DefaultErrorResponseEntityException::class
                )
            )
            ->type(BalanceTransferResponse::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
