<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Apis;

use AdyenLib\Exceptions\ApiException;
use AdyenLib\Exceptions\RestServiceErrorException;
use AdyenLib\Models\ListNetworkTokensResponse;
use AdyenLib\Models\NetworkTokenActivationDataRequest;
use AdyenLib\Models\NetworkTokenActivationDataResponse;
use AdyenLib\Models\PaymentInstrument1;
use AdyenLib\Models\PaymentInstrumentInfo;
use AdyenLib\Models\PaymentInstrumentRevealInfo;
use AdyenLib\Models\PaymentInstrumentRevealRequest;
use AdyenLib\Models\PaymentInstrumentRevealResponse;
use AdyenLib\Models\PaymentInstrumentUpdateRequest;
use AdyenLib\Models\TransactionRulesResponse;
use AdyenLib\Models\UpdatePaymentInstrument;
use AdyenLib\Server;
use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use Core\Request\Parameters\TemplateParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;

class PaymentInstrumentsApi extends BaseApi
{
    /**
     * Creates a payment instrument to issue a physical card, a virtual card, or a business account to your
     * user.
     *
     * For more information, refer to [Issue cards](https://docs.adyen.com/issuing/create-cards) or [Issue
     * business accounts](https://docs.adyen.com/platforms/business-accounts).
     *
     * @param PaymentInstrumentInfo|null $body
     *
     * @return PaymentInstrument1 Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function postPaymentInstruments(?PaymentInstrumentInfo $body = null): PaymentInstrument1
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/paymentInstruments')
            ->server(Server::DEFAULT13)
            ->auth('clientKey', 'BasicAuth', 'ApiKeyAuth')
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '400',
                ErrorType::init(
                    'Bad Request - a problem reading or understanding the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '401',
                ErrorType::init('Unauthorized - authentication required.', RestServiceErrorException::class)
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    'Forbidden - insufficient permissions to process the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '422',
                ErrorType::init(
                    'Unprocessable Entity - a request validation error.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '500',
                ErrorType::init(
                    'Internal Server Error - the server could not process the request.',
                    RestServiceErrorException::class
                )
            )
            ->type(PaymentInstrument1::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Returns the encrypted data of a specified payment instrument. These data include:
     *
     * - The primary account number (PAN)
     * - The card verification code (CVC)
     * - The expiry date
     *
     * You can decrypt the data to reveal it in your user interface.
     *
     * To make this request, your API credential must have the following role:
     * * Bank Issuing PAN Reveal Webservice role
     *
     * @param PaymentInstrumentRevealRequest|null $body
     *
     * @return PaymentInstrumentRevealResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function postPaymentInstrumentsReveal(
        ?PaymentInstrumentRevealRequest $body = null
    ): PaymentInstrumentRevealResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/paymentInstruments/reveal')
            ->server(Server::DEFAULT13)
            ->auth('clientKey', 'BasicAuth', 'ApiKeyAuth')
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '400',
                ErrorType::init(
                    'Bad Request - a problem reading or understanding the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '401',
                ErrorType::init('Unauthorized - authentication required.', RestServiceErrorException::class)
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    'Forbidden - insufficient permissions to process the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '422',
                ErrorType::init(
                    'Unprocessable Entity - a request validation error.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '500',
                ErrorType::init(
                    'Internal Server Error - the server could not process the request.',
                    RestServiceErrorException::class
                )
            )
            ->type(PaymentInstrumentRevealResponse::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Returns the details of a payment instrument.
     *
     * @param string $id The unique identifier of the payment instrument.
     *
     * @return PaymentInstrument1 Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getPaymentInstrumentsId(string $id): PaymentInstrument1
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/paymentInstruments/{id}')
            ->server(Server::DEFAULT13)
            ->auth('clientKey', 'BasicAuth', 'ApiKeyAuth')
            ->parameters(TemplateParam::init('id', $id));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '400',
                ErrorType::init(
                    'Bad Request - a problem reading or understanding the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '401',
                ErrorType::init('Unauthorized - authentication required.', RestServiceErrorException::class)
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    'Forbidden - insufficient permissions to process the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '422',
                ErrorType::init(
                    'Unprocessable Entity - a request validation error.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '500',
                ErrorType::init(
                    'Internal Server Error - the server could not process the request.',
                    RestServiceErrorException::class
                )
            )
            ->type(PaymentInstrument1::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Updates a payment instrument. Once a payment instrument is already active, you can only update its
     * status. However, for cards created with **inactive** status, you can still update the balance
     * account associated with the card.
     *
     * @param string $id The unique identifier of the payment instrument.
     * @param PaymentInstrumentUpdateRequest|null $body
     *
     * @return UpdatePaymentInstrument Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function patchPaymentInstrumentsId(
        string $id,
        ?PaymentInstrumentUpdateRequest $body = null
    ): UpdatePaymentInstrument {
        $_reqBuilder = $this->requestBuilder(RequestMethod::PATCH, '/paymentInstruments/{id}')
            ->server(Server::DEFAULT13)
            ->auth('clientKey', 'BasicAuth', 'ApiKeyAuth')
            ->parameters(
                TemplateParam::init('id', $id),
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '400',
                ErrorType::init(
                    'Bad Request - a problem reading or understanding the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '401',
                ErrorType::init('Unauthorized - authentication required.', RestServiceErrorException::class)
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    'Forbidden - insufficient permissions to process the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '422',
                ErrorType::init(
                    'Unprocessable Entity - a request validation error.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '500',
                ErrorType::init(
                    'Internal Server Error - the server could not process the request.',
                    RestServiceErrorException::class
                )
            )
            ->type(UpdatePaymentInstrument::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Get the network token activation data for a payment instrument.
     *
     * @param string $id The unique identifier of the payment instrument.
     *
     * @return NetworkTokenActivationDataResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getPaymentInstrumentsIdNetworkTokenActivationData(string $id): NetworkTokenActivationDataResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::GET,
            '/paymentInstruments/{id}/networkTokenActivationData'
        )
            ->server(Server::DEFAULT13)
            ->auth('clientKey', 'BasicAuth', 'ApiKeyAuth')
            ->parameters(TemplateParam::init('id', $id));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '400',
                ErrorType::init(
                    'Bad Request - a problem reading or understanding the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '401',
                ErrorType::init('Unauthorized - authentication required.', RestServiceErrorException::class)
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    'Forbidden - insufficient permissions to process the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '422',
                ErrorType::init(
                    'Unprocessable Entity - a request validation error.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '500',
                ErrorType::init(
                    'Internal Server Error - the server could not process the request.',
                    RestServiceErrorException::class
                )
            )
            ->type(NetworkTokenActivationDataResponse::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Create provisioning data for a network token. Use the provisioning data to add a user's payment
     * instrument to their digital wallet.
     *
     * @param string $id The unique identifier of the payment instrument.
     * @param NetworkTokenActivationDataRequest|null $body
     *
     * @return NetworkTokenActivationDataResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function postPaymentInstrumentsIdNetworkTokenActivationData(
        string $id,
        ?NetworkTokenActivationDataRequest $body = null
    ): NetworkTokenActivationDataResponse {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/paymentInstruments/{id}/networkTokenActivationData'
        )
            ->server(Server::DEFAULT13)
            ->auth('clientKey', 'BasicAuth', 'ApiKeyAuth')
            ->parameters(
                TemplateParam::init('id', $id),
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '400',
                ErrorType::init(
                    'Bad Request - a problem reading or understanding the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '401',
                ErrorType::init('Unauthorized - authentication required.', RestServiceErrorException::class)
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    'Forbidden - insufficient permissions to process the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '422',
                ErrorType::init(
                    'Unprocessable Entity - a request validation error.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '500',
                ErrorType::init(
                    'Internal Server Error - the server could not process the request.',
                    RestServiceErrorException::class
                )
            )
            ->type(NetworkTokenActivationDataResponse::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * List the network tokens connected to a payment instrument.
     *
     * @param string $id The unique identifier of the payment instrument.
     *
     * @return ListNetworkTokensResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getPaymentInstrumentsIdNetworkTokens(string $id): ListNetworkTokensResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/paymentInstruments/{id}/networkTokens')
            ->server(Server::DEFAULT13)
            ->auth('clientKey', 'BasicAuth', 'ApiKeyAuth')
            ->parameters(TemplateParam::init('id', $id));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '400',
                ErrorType::init(
                    'Bad Request - a problem reading or understanding the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '401',
                ErrorType::init('Unauthorized - authentication required.', RestServiceErrorException::class)
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    'Forbidden - insufficient permissions to process the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '422',
                ErrorType::init(
                    'Unprocessable Entity - a request validation error.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '500',
                ErrorType::init(
                    'Internal Server Error - the server could not process the request.',
                    RestServiceErrorException::class
                )
            )
            ->type(ListNetworkTokensResponse::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Returns the primary account number (PAN) of a payment instrument.
     *
     * To make this request, your API credential must have the following [role](https://docs.adyen.
     * com/issuing/manage-access/api-credentials-web-service#api-permissions):
     *
     * * Balance Platform BCL PCI role
     *
     * @param string $id The unique identifier of the payment instrument.
     *
     * @return PaymentInstrumentRevealInfo Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getPaymentInstrumentsIdReveal(string $id): PaymentInstrumentRevealInfo
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/paymentInstruments/{id}/reveal')
            ->server(Server::DEFAULT13)
            ->auth('clientKey', 'BasicAuth', 'ApiKeyAuth')
            ->parameters(TemplateParam::init('id', $id));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '400',
                ErrorType::init(
                    'Bad Request - a problem reading or understanding the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '401',
                ErrorType::init('Unauthorized - authentication required.', RestServiceErrorException::class)
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    'Forbidden - insufficient permissions to process the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '422',
                ErrorType::init(
                    'Unprocessable Entity - a request validation error.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '500',
                ErrorType::init(
                    'Internal Server Error - the server could not process the request.',
                    RestServiceErrorException::class
                )
            )
            ->type(PaymentInstrumentRevealInfo::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Returns a list of transaction rules associated with a payment instrument.
     *
     * @param string $id The unique identifier of the payment instrument.
     *
     * @return TransactionRulesResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getPaymentInstrumentsIdTransactionRules(string $id): TransactionRulesResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/paymentInstruments/{id}/transactionRules')
            ->server(Server::DEFAULT13)
            ->auth('clientKey', 'BasicAuth', 'ApiKeyAuth')
            ->parameters(TemplateParam::init('id', $id));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '400',
                ErrorType::init(
                    'Bad Request - a problem reading or understanding the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '401',
                ErrorType::init('Unauthorized - authentication required.', RestServiceErrorException::class)
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    'Forbidden - insufficient permissions to process the request.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '422',
                ErrorType::init(
                    'Unprocessable Entity - a request validation error.',
                    RestServiceErrorException::class
                )
            )
            ->throwErrorOn(
                '500',
                ErrorType::init(
                    'Internal Server Error - the server could not process the request.',
                    RestServiceErrorException::class
                )
            )
            ->type(TransactionRulesResponse::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
