<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class AccountParty implements \JsonSerializable
{
    /**
     * @var Identity2
     */
    private $identity;

    /**
     * @var string
     */
    private $role;

    /**
     * @param Identity2 $identity
     * @param string $role
     */
    public function __construct(Identity2 $identity, string $role)
    {
        $this->identity = $identity;
        $this->role = $role;
    }

    /**
     * Returns Identity.
     * Contains the identity details of the party.
     */
    public function getIdentity(): Identity2
    {
        return $this->identity;
    }

    /**
     * Sets Identity.
     * Contains the identity details of the party.
     *
     * @required
     * @maps identity
     */
    public function setIdentity(Identity2 $identity): void
    {
        $this->identity = $identity;
    }

    /**
     * Returns Role.
     * Specifies a role or capacity of the party in relation to the bank account.
     */
    public function getRole(): string
    {
        return $this->role;
    }

    /**
     * Sets Role.
     * Specifies a role or capacity of the party in relation to the bank account.
     *
     * @required
     * @maps role
     * @factory \AdyenLib\Models\PartyRole2Enum::checkValue
     */
    public function setRole(string $role): void
    {
        $this->role = $role;
    }

    /**
     * Converts the AccountParty object to a human-readable string representation.
     *
     * @return string The string representation of the AccountParty object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('AccountParty', ['identity' => $this->identity, 'role' => $this->role]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['identity'] = $this->identity;
        $json['role']     = PartyRole2Enum::checkValue($this->role);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
