<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The capability level that is allowed for the account holder.
 *
 * Possible values: **notApplicable**, **low**, **medium**, **high**., The capability level that is
 * allowed for the legal entity.
 *
 * Possible values: **notApplicable**, **low**, **medium**, **high**., The requested level of the
 * capability. Some capabilities, such as those used in [card issuing](https://docs.adyen.
 * com/issuing/add-capabilities#capability-levels), have different levels. Levels increase the
 * capability, but also require additional checks and increased monitoring.
 *
 * Possible values: **notApplicable**, **low**, **medium**, **high**.
 */
class AllowedLevelEnum
{
    public const HIGH = 'high';

    public const LOW = 'low';

    public const MEDIUM = 'medium';

    public const NOTAPPLICABLE = 'notApplicable';

    private const _ALL_VALUES = [self::HIGH, self::LOW, self::MEDIUM, self::NOTAPPLICABLE];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for AllowedLevelEnum.");
    }
}
