<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class AmountAdjustment implements \JsonSerializable
{
    /**
     * @var Amount17|null
     */
    private $amount;

    /**
     * @var string|null
     */
    private $amountAdjustmentType;

    /**
     * @var int|null
     */
    private $basepoints;

    /**
     * Returns Amount.
     * The adjustment amount.
     */
    public function getAmount(): ?Amount17
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * The adjustment amount.
     *
     * @maps amount
     */
    public function setAmount(?Amount17 $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Amount Adjustment Type.
     * The type of markup that is applied to an authorised payment.
     *
     * Possible values: **exchange**, **forexMarkup**, **authHoldReserve**, **atmMarkup**.
     */
    public function getAmountAdjustmentType(): ?string
    {
        return $this->amountAdjustmentType;
    }

    /**
     * Sets Amount Adjustment Type.
     * The type of markup that is applied to an authorised payment.
     *
     * Possible values: **exchange**, **forexMarkup**, **authHoldReserve**, **atmMarkup**.
     *
     * @maps amountAdjustmentType
     * @factory \AdyenLib\Models\AmountAdjustmentTypeEnum::checkValue
     */
    public function setAmountAdjustmentType(?string $amountAdjustmentType): void
    {
        $this->amountAdjustmentType = $amountAdjustmentType;
    }

    /**
     * Returns Basepoints.
     * The basepoints associated with the applied markup.
     */
    public function getBasepoints(): ?int
    {
        return $this->basepoints;
    }

    /**
     * Sets Basepoints.
     * The basepoints associated with the applied markup.
     *
     * @maps basepoints
     */
    public function setBasepoints(?int $basepoints): void
    {
        $this->basepoints = $basepoints;
    }

    /**
     * Converts the AmountAdjustment object to a human-readable string representation.
     *
     * @return string The string representation of the AmountAdjustment object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AmountAdjustment',
            [
                'amount' => $this->amount,
                'amountAdjustmentType' => $this->amountAdjustmentType,
                'basepoints' => $this->basepoints
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->amount)) {
            $json['amount']               = $this->amount;
        }
        if (isset($this->amountAdjustmentType)) {
            $json['amountAdjustmentType'] = AmountAdjustmentTypeEnum::checkValue($this->amountAdjustmentType);
        }
        if (isset($this->basepoints)) {
            $json['basepoints']           = $this->basepoints;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
