<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class AssociationInitiateResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $sdkInput;

    /**
     * Returns Sdk Input.
     * A string that you must pass to the authentication SDK to continue with the association process.
     */
    public function getSdkInput(): ?string
    {
        return $this->sdkInput;
    }

    /**
     * Sets Sdk Input.
     * A string that you must pass to the authentication SDK to continue with the association process.
     *
     * @maps sdkInput
     */
    public function setSdkInput(?string $sdkInput): void
    {
        $this->sdkInput = $sdkInput;
    }

    /**
     * Converts the AssociationInitiateResponse object to a human-readable string representation.
     *
     * @return string The string representation of the AssociationInitiateResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('AssociationInitiateResponse', ['sdkInput' => $this->sdkInput]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->sdkInput)) {
            $json['sdkInput'] = $this->sdkInput;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
