<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class BalanceMutation implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $balance;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var int|null
     */
    private $received;

    /**
     * @var int|null
     */
    private $reserved;

    /**
     * Returns Balance.
     * The amount in the payment's currency that is debited or credited on the balance accounting register.
     */
    public function getBalance(): ?int
    {
        return $this->balance;
    }

    /**
     * Sets Balance.
     * The amount in the payment's currency that is debited or credited on the balance accounting register.
     *
     * @maps balance
     */
    public function setBalance(?int $balance): void
    {
        $this->balance = $balance;
    }

    /**
     * Returns Currency.
     * The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes).
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     * The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes).
     *
     * @maps currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Received.
     * The amount in the payment's currency that is debited or credited on the received accounting register.
     */
    public function getReceived(): ?int
    {
        return $this->received;
    }

    /**
     * Sets Received.
     * The amount in the payment's currency that is debited or credited on the received accounting register.
     *
     * @maps received
     */
    public function setReceived(?int $received): void
    {
        $this->received = $received;
    }

    /**
     * Returns Reserved.
     * The amount in the payment's currency that is debited or credited on the reserved accounting register.
     */
    public function getReserved(): ?int
    {
        return $this->reserved;
    }

    /**
     * Sets Reserved.
     * The amount in the payment's currency that is debited or credited on the reserved accounting register.
     *
     * @maps reserved
     */
    public function setReserved(?int $reserved): void
    {
        $this->reserved = $reserved;
    }

    /**
     * Converts the BalanceMutation object to a human-readable string representation.
     *
     * @return string The string representation of the BalanceMutation object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BalanceMutation',
            [
                'balance' => $this->balance,
                'currency' => $this->currency,
                'received' => $this->received,
                'reserved' => $this->reserved
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->balance)) {
            $json['balance']  = $this->balance;
        }
        if (isset($this->currency)) {
            $json['currency'] = $this->currency;
        }
        if (isset($this->received)) {
            $json['received'] = $this->received;
        }
        if (isset($this->reserved)) {
            $json['reserved'] = $this->reserved;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
