<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class BalanceWebhookSettingInfoUpdate implements \JsonSerializable
{
    /**
     * @var array
     */
    private $conditions = [];

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var TargetUpdate2|null
     */
    private $target;

    /**
     * @var string|null
     */
    private $type;

    /**
     * Returns Conditions.
     * The array of conditions a balance change must meet for Adyen to send the webhook.
     *
     * @return Condition[]|null
     */
    public function getConditions(): ?array
    {
        if (count($this->conditions) == 0) {
            return null;
        }
        return $this->conditions['value'];
    }

    /**
     * Sets Conditions.
     * The array of conditions a balance change must meet for Adyen to send the webhook.
     *
     * @maps conditions
     *
     * @param Condition[]|null $conditions
     */
    public function setConditions(?array $conditions): void
    {
        $this->conditions['value'] = $conditions;
    }

    /**
     * Unsets Conditions.
     * The array of conditions a balance change must meet for Adyen to send the webhook.
     */
    public function unsetConditions(): void
    {
        $this->conditions = [];
    }

    /**
     * Returns Currency.
     * The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes)
     * of the balance.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     * The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes)
     * of the balance.
     *
     * @maps currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Status.
     * The status of the webhook setting. Possible values:
     *
     * * **active**: You receive a balance webhook if any of the conditions in this setting are met.
     * * **inactive**: You do not receive a balance webhook even if the conditions in this settings are met.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status of the webhook setting. Possible values:
     *
     * * **active**: You receive a balance webhook if any of the conditions in this setting are met.
     * * **inactive**: You do not receive a balance webhook even if the conditions in this settings are met.
     *
     * @maps status
     * @factory \AdyenLib\Models\Status6Enum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Target.
     * The type and ID of the resource about whose balance changes you want to be notified.
     */
    public function getTarget(): ?TargetUpdate2
    {
        return $this->target;
    }

    /**
     * Sets Target.
     * The type and ID of the resource about whose balance changes you want to be notified.
     *
     * @maps target
     */
    public function setTarget(?TargetUpdate2 $target): void
    {
        $this->target = $target;
    }

    /**
     * Returns Type.
     * The type of the webhook you are configuring. Set to **balance**.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of the webhook you are configuring. Set to **balance**.
     *
     * @maps type
     * @factory \AdyenLib\Models\Type201Enum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the BalanceWebhookSettingInfoUpdate object to a human-readable string representation.
     *
     * @return string The string representation of the BalanceWebhookSettingInfoUpdate object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BalanceWebhookSettingInfoUpdate',
            [
                'conditions' => $this->getConditions(),
                'currency' => $this->currency,
                'status' => $this->status,
                'target' => $this->target,
                'type' => $this->type
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->conditions)) {
            $json['conditions'] = $this->conditions['value'];
        }
        if (isset($this->currency)) {
            $json['currency']   = $this->currency;
        }
        if (isset($this->status)) {
            $json['status']     = Status6Enum::checkValue($this->status);
        }
        if (isset($this->target)) {
            $json['target']     = $this->target;
        }
        if (isset($this->type)) {
            $json['type']       = Type201Enum::checkValue($this->type);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
