<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

/**
 * The request parameters required to calculate an amount in a different currency.
 */
class CalculateRateRequestItem implements \JsonSerializable
{
    /**
     * @var string
     */
    private $exchangeSide;

    /**
     * @var Amount19
     */
    private $sourceAmount;

    /**
     * @var string
     */
    private $targetCurrency;

    /**
     * @var string
     */
    private $type;

    /**
     * @param string $exchangeSide
     * @param Amount19 $sourceAmount
     * @param string $targetCurrency
     * @param string $type
     */
    public function __construct(string $exchangeSide, Amount19 $sourceAmount, string $targetCurrency, string $type)
    {
        $this->exchangeSide = $exchangeSide;
        $this->sourceAmount = $sourceAmount;
        $this->targetCurrency = $targetCurrency;
        $this->type = $type;
    }

    /**
     * Returns Exchange Side.
     * The operation performed on the source amount. Possible values:
     * * **buy**
     * * **sell**
     */
    public function getExchangeSide(): string
    {
        return $this->exchangeSide;
    }

    /**
     * Sets Exchange Side.
     * The operation performed on the source amount. Possible values:
     * * **buy**
     * * **sell**
     *
     * @required
     * @maps exchangeSide
     * @factory \AdyenLib\Models\ExchangeSide2Enum::checkValue
     */
    public function setExchangeSide(string $exchangeSide): void
    {
        $this->exchangeSide = $exchangeSide;
    }

    /**
     * Returns Source Amount.
     * An object specifying the currency and value for which you want to perform an exchange calculation.
     */
    public function getSourceAmount(): Amount19
    {
        return $this->sourceAmount;
    }

    /**
     * Sets Source Amount.
     * An object specifying the currency and value for which you want to perform an exchange calculation.
     *
     * @required
     * @maps sourceAmount
     */
    public function setSourceAmount(Amount19 $sourceAmount): void
    {
        $this->sourceAmount = $sourceAmount;
    }

    /**
     * Returns Target Currency.
     * The currency to which you want to convert the source amount.
     */
    public function getTargetCurrency(): string
    {
        return $this->targetCurrency;
    }

    /**
     * Sets Target Currency.
     * The currency to which you want to convert the source amount.
     *
     * @required
     * @maps targetCurrency
     */
    public function setTargetCurrency(string $targetCurrency): void
    {
        $this->targetCurrency = $targetCurrency;
    }

    /**
     * Returns Type.
     * The type of transaction. Possible values:
     * * **splitPayment**: for payments
     * * **splitRefund**: for refunds
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of transaction. Possible values:
     * * **splitPayment**: for payments
     * * **splitRefund**: for refunds
     *
     * @required
     * @maps type
     * @factory \AdyenLib\Models\RateType2Enum::checkValue
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the CalculateRateRequestItem object to a human-readable string representation.
     *
     * @return string The string representation of the CalculateRateRequestItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CalculateRateRequestItem',
            [
                'exchangeSide' => $this->exchangeSide,
                'sourceAmount' => $this->sourceAmount,
                'targetCurrency' => $this->targetCurrency,
                'type' => $this->type
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['exchangeSide']   = ExchangeSide2Enum::checkValue($this->exchangeSide);
        $json['sourceAmount']   = $this->sourceAmount;
        $json['targetCurrency'] = $this->targetCurrency;
        $json['type']           = RateType2Enum::checkValue($this->type);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
