<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

/**
 * The request to calculate an amount in a different currency.
 */
class CalculateRateRequest implements \JsonSerializable
{
    /**
     * @var CalculateRateRequestItem[]
     */
    private $exchangeCalculations;

    /**
     * @param CalculateRateRequestItem[] $exchangeCalculations
     */
    public function __construct(array $exchangeCalculations)
    {
        $this->exchangeCalculations = $exchangeCalculations;
    }

    /**
     * Returns Exchange Calculations.
     * An array of objects, where each object defines a currency and value for which you want to perform an
     * exchange calculation.
     *
     * @return CalculateRateRequestItem[]
     */
    public function getExchangeCalculations(): array
    {
        return $this->exchangeCalculations;
    }

    /**
     * Sets Exchange Calculations.
     * An array of objects, where each object defines a currency and value for which you want to perform an
     * exchange calculation.
     *
     * @required
     * @maps exchangeCalculations
     *
     * @param CalculateRateRequestItem[] $exchangeCalculations
     */
    public function setExchangeCalculations(array $exchangeCalculations): void
    {
        $this->exchangeCalculations = $exchangeCalculations;
    }

    /**
     * Converts the CalculateRateRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CalculateRateRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CalculateRateRequest',
            ['exchangeCalculations' => $this->exchangeCalculations]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['exchangeCalculations'] = $this->exchangeCalculations;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
