<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

/**
 * Information related to the payment card used for the transaction.
 * If PaymentInstrumentType is Card.
 */
class CardData1 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $paymentBrand;

    /**
     * @var string|null
     */
    private $maskedPan;

    /**
     * @var string|null
     */
    private $paymentAccountRef;

    /**
     * @var string[]|null
     */
    private $entryMode;

    /**
     * @var int|null
     */
    private $cardCountryCode;

    /**
     * @var string|null
     */
    private $protectedCardData;

    /**
     * @var SensitiveCardData1|null
     */
    private $sensitiveCardData;

    /**
     * @var PaymentToken1|null
     */
    private $paymentToken;

    /**
     * Returns Payment Brand.
     * Type of payment card.
     * If card PAN is readable.
     * Indicates the card used to pay in the PaymentResponse. Sent in the CardAcquisitionResponse, to leave
     * the Cashier to choose between several applications in a smartcard, or several brand in a co-branded
     * card. In this case, the CardAcquisitionRequest.ForceCustomerSelectionFlag must contain the value
     * False. Brands are part of the POI and Sale Systems configurations.
     */
    public function getPaymentBrand(): ?string
    {
        return $this->paymentBrand;
    }

    /**
     * Sets Payment Brand.
     * Type of payment card.
     * If card PAN is readable.
     * Indicates the card used to pay in the PaymentResponse. Sent in the CardAcquisitionResponse, to leave
     * the Cashier to choose between several applications in a smartcard, or several brand in a co-branded
     * card. In this case, the CardAcquisitionRequest.ForceCustomerSelectionFlag must contain the value
     * False. Brands are part of the POI and Sale Systems configurations.
     *
     * @maps PaymentBrand
     */
    public function setPaymentBrand(?string $paymentBrand): void
    {
        $this->paymentBrand = $paymentBrand;
    }

    /**
     * Returns Masked Pan.
     * Masked Primary Account Number
     * Part of the PAN is replaced by a string of * characters, to identify a customer account or
     * relationship. Presence of this data element, which replace the PAN when SensitiveCardData is
     * protected and replaced by ProtectedCardData. Alternatively the MaskedPAN can be used as a token to
     * identify a customer.
     */
    public function getMaskedPan(): ?string
    {
        return $this->maskedPan;
    }

    /**
     * Sets Masked Pan.
     * Masked Primary Account Number
     * Part of the PAN is replaced by a string of * characters, to identify a customer account or
     * relationship. Presence of this data element, which replace the PAN when SensitiveCardData is
     * protected and replaced by ProtectedCardData. Alternatively the MaskedPAN can be used as a token to
     * identify a customer.
     *
     * @maps MaskedPan
     */
    public function setMaskedPan(?string $maskedPan): void
    {
        $this->maskedPan = $maskedPan;
    }

    /**
     * Returns Payment Account Ref.
     * Reference of the PAN, which identifies the PAN or the card uniquely, named also PAR (Payment Account
     * Reference). This reference may be defined by the card issuer or by a token service provider under
     * the control of the card issuer, and cannot be used for a payment transaction.
     */
    public function getPaymentAccountRef(): ?string
    {
        return $this->paymentAccountRef;
    }

    /**
     * Sets Payment Account Ref.
     * Reference of the PAN, which identifies the PAN or the card uniquely, named also PAR (Payment Account
     * Reference). This reference may be defined by the card issuer or by a token service provider under
     * the control of the card issuer, and cannot be used for a payment transaction.
     *
     * @maps PaymentAccountRef
     */
    public function setPaymentAccountRef(?string $paymentAccountRef): void
    {
        $this->paymentAccountRef = $paymentAccountRef;
    }

    /**
     * Returns Entry Mode.
     * Entry mode of the payment instrument information. In the Payment, Loyalty or StoredValue Request
     * messages, it informs the POI System the entry mode of the payment instrument information when read
     * by the Sale Terminal. In the Payment, Loyalty or StoredValue Response messages, it informs the Sale
     * System the entry mode of the payment instrument.
     * Possible values:
     * * **Contactless**
     * * **File**
     * * **ICC**
     * * **Keyed**
     * * **MagStripe**
     * * **Manual**
     * * **Mobile**
     * * **RFID**
     * * **Scanned**
     * * **SynchronousICC**
     * * **Tapped**
     *
     * @return string[]|null
     */
    public function getEntryMode(): ?array
    {
        return $this->entryMode;
    }

    /**
     * Sets Entry Mode.
     * Entry mode of the payment instrument information. In the Payment, Loyalty or StoredValue Request
     * messages, it informs the POI System the entry mode of the payment instrument information when read
     * by the Sale Terminal. In the Payment, Loyalty or StoredValue Response messages, it informs the Sale
     * System the entry mode of the payment instrument.
     * Possible values:
     * * **Contactless**
     * * **File**
     * * **ICC**
     * * **Keyed**
     * * **MagStripe**
     * * **Manual**
     * * **Mobile**
     * * **RFID**
     * * **Scanned**
     * * **SynchronousICC**
     * * **Tapped**
     *
     * @maps EntryMode
     * @factory \AdyenLib\Models\EntryModeEnum::checkValue
     *
     * @param string[]|null $entryMode
     */
    public function setEntryMode(?array $entryMode): void
    {
        $this->entryMode = $entryMode;
    }

    /**
     * Returns Card Country Code.
     * Country Code attached to the card (3 numerics).
     * If available in the card.
     */
    public function getCardCountryCode(): ?int
    {
        return $this->cardCountryCode;
    }

    /**
     * Sets Card Country Code.
     * Country Code attached to the card (3 numerics).
     * If available in the card.
     *
     * @maps CardCountryCode
     */
    public function setCardCountryCode(?int $cardCountryCode): void
    {
        $this->cardCountryCode = $cardCountryCode;
    }

    /**
     * Returns Protected Card Data.
     * Sensitive information related to the payment card, protected by CMS.
     * SensitiveCardData protected by CMS EnvelopedData.
     */
    public function getProtectedCardData(): ?string
    {
        return $this->protectedCardData;
    }

    /**
     * Sets Protected Card Data.
     * Sensitive information related to the payment card, protected by CMS.
     * SensitiveCardData protected by CMS EnvelopedData.
     *
     * @maps ProtectedCardData
     */
    public function setProtectedCardData(?string $protectedCardData): void
    {
        $this->protectedCardData = $protectedCardData;
    }

    /**
     * Returns Sensitive Card Data.
     * Sensitive information related to the payment card, entered or read by the Sale System.
     * If structure non empty and unprotected.
     */
    public function getSensitiveCardData(): ?SensitiveCardData1
    {
        return $this->sensitiveCardData;
    }

    /**
     * Sets Sensitive Card Data.
     * Sensitive information related to the payment card, entered or read by the Sale System.
     * If structure non empty and unprotected.
     *
     * @maps SensitiveCardData
     */
    public function setSensitiveCardData(?SensitiveCardData1 $sensitiveCardData): void
    {
        $this->sensitiveCardData = $sensitiveCardData;
    }

    /**
     * Returns Payment Token.
     * Surrogate of the PAN (Primary Account Number) of the payment card to identify the payment mean of
     * the customer. It allows, for a merchant, to identify the customer.
     * Restriction of product payable by a card.
     */
    public function getPaymentToken(): ?PaymentToken1
    {
        return $this->paymentToken;
    }

    /**
     * Sets Payment Token.
     * Surrogate of the PAN (Primary Account Number) of the payment card to identify the payment mean of
     * the customer. It allows, for a merchant, to identify the customer.
     * Restriction of product payable by a card.
     *
     * @maps PaymentToken
     */
    public function setPaymentToken(?PaymentToken1 $paymentToken): void
    {
        $this->paymentToken = $paymentToken;
    }

    /**
     * Converts the CardData1 object to a human-readable string representation.
     *
     * @return string The string representation of the CardData1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CardData1',
            [
                'paymentBrand' => $this->paymentBrand,
                'maskedPan' => $this->maskedPan,
                'paymentAccountRef' => $this->paymentAccountRef,
                'entryMode' => $this->entryMode,
                'cardCountryCode' => $this->cardCountryCode,
                'protectedCardData' => $this->protectedCardData,
                'sensitiveCardData' => $this->sensitiveCardData,
                'paymentToken' => $this->paymentToken
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->paymentBrand)) {
            $json['PaymentBrand']      = $this->paymentBrand;
        }
        if (isset($this->maskedPan)) {
            $json['MaskedPan']         = $this->maskedPan;
        }
        if (isset($this->paymentAccountRef)) {
            $json['PaymentAccountRef'] = $this->paymentAccountRef;
        }
        if (isset($this->entryMode)) {
            $json['EntryMode']         = EntryModeEnum::checkValue($this->entryMode);
        }
        if (isset($this->cardCountryCode)) {
            $json['CardCountryCode']   = $this->cardCountryCode;
        }
        if (isset($this->protectedCardData)) {
            $json['ProtectedCardData'] = $this->protectedCardData;
        }
        if (isset($this->sensitiveCardData)) {
            $json['SensitiveCardData'] = $this->sensitiveCardData;
        }
        if (isset($this->paymentToken)) {
            $json['PaymentToken']      = $this->paymentToken;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
