<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Typographic style of the sequence of characters to display or print. Absence of this data element
 * means the characters have normal style.
 * Possible values:
 * * **Bold**
 * * **Italic**
 * * **Normal**
 * * **Underline**
 */
class CharacterStyle1Enum
{
    public const NORMAL = 'Normal';

    public const BOLD = 'Bold';

    public const ITALIC = 'Italic';

    public const UNDERLINE = 'Underline';

    private const _ALL_VALUES = [self::NORMAL, self::BOLD, self::ITALIC, self::UNDERLINE];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for CharacterStyle1Enum.");
    }
}
