<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Define when you want to get notified about a balance change. Possible values:
 *
 * * **greaterThan**: the balance in the account(s) exceeds the specified `value`.
 *
 * * **greaterThanOrEqual**: the balance in the account(s) reaches or exceeds the specified `value`.
 *
 * * **lessThan**: the balance in the account(s) drops below the specified `value`.
 *
 * * **lessThanOrEqual**: the balance in the account(s) reaches to drops below the specified `value`.
 */
class ConditionTypeEnum
{
    public const GREATERTHAN = 'greaterThan';

    public const GREATERTHANOREQUAL = 'greaterThanOrEqual';

    public const LESSTHAN = 'lessThan';

    public const LESSTHANOREQUAL = 'lessThanOrEqual';

    private const _ALL_VALUES = [self::GREATERTHAN, self::GREATERTHANOREQUAL, self::LESSTHAN, self::LESSTHANOREQUAL];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for ConditionTypeEnum.");
    }
}
