<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class ConvertedAmount implements \JsonSerializable
{
    /**
     * @var float
     */
    private $amountValue;

    /**
     * @var string
     */
    private $currency;

    /**
     * @param float $amountValue
     * @param string $currency
     */
    public function __construct(float $amountValue, string $currency)
    {
        $this->amountValue = $amountValue;
        $this->currency = $currency;
    }

    /**
     * Returns Amount Value.
     * Value of an amount.
     */
    public function getAmountValue(): float
    {
        return $this->amountValue;
    }

    /**
     * Sets Amount Value.
     * Value of an amount.
     *
     * @required
     * @maps AmountValue
     */
    public function setAmountValue(float $amountValue): void
    {
        $this->amountValue = $amountValue;
    }

    /**
     * Returns Currency.
     * Currency of a monetary amount.
     */
    public function getCurrency(): string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     * Currency of a monetary amount.
     *
     * @required
     * @maps Currency
     */
    public function setCurrency(string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Converts the ConvertedAmount object to a human-readable string representation.
     *
     * @return string The string representation of the ConvertedAmount object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConvertedAmount',
            ['amountValue' => $this->amountValue, 'currency' => $this->currency]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['AmountValue'] = $this->amountValue;
        $json['Currency']    = $this->currency;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
