<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class CreateSweepConfigurationV2 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $category;

    /**
     * @var SweepCounterparty1
     */
    private $counterparty;

    /**
     * @var string
     */
    private $currency;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string[]|null
     */
    private $priorities;

    /**
     * @var string|null
     */
    private $reason;

    /**
     * @var string|null
     */
    private $reasonDetail;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var string|null
     */
    private $referenceForBeneficiary;

    /**
     * @var SweepSchedule1
     */
    private $schedule;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var Amount17|null
     */
    private $sweepAmount;

    /**
     * @var Amount17|null
     */
    private $targetAmount;

    /**
     * @var Amount17|null
     */
    private $triggerAmount;

    /**
     * @var string|null
     */
    private $type = Type72Enum::PUSH;

    /**
     * @param SweepCounterparty1 $counterparty
     * @param string $currency
     * @param SweepSchedule1 $schedule
     */
    public function __construct(SweepCounterparty1 $counterparty, string $currency, SweepSchedule1 $schedule)
    {
        $this->counterparty = $counterparty;
        $this->currency = $currency;
        $this->schedule = $schedule;
    }

    /**
     * Returns Category.
     * The type of transfer that results from the sweep.
     *
     * Possible values:
     *
     * - **bank**: Sweep to a [transfer instrument](https://docs.adyen.com/api-
     * explorer/#/legalentity/latest/post/transferInstruments__resParam_id).
     *
     * - **internal**: Transfer to another [balance account](https://docs.adyen.com/api-
     * explorer/#/balanceplatform/latest/post/balanceAccounts__resParam_id) within your platform.
     *
     * Required when setting `priorities`.
     */
    public function getCategory(): ?string
    {
        return $this->category;
    }

    /**
     * Sets Category.
     * The type of transfer that results from the sweep.
     *
     * Possible values:
     *
     * - **bank**: Sweep to a [transfer instrument](https://docs.adyen.com/api-
     * explorer/#/legalentity/latest/post/transferInstruments__resParam_id).
     *
     * - **internal**: Transfer to another [balance account](https://docs.adyen.com/api-
     * explorer/#/balanceplatform/latest/post/balanceAccounts__resParam_id) within your platform.
     *
     * Required when setting `priorities`.
     *
     * @maps category
     * @factory \AdyenLib\Models\Category1Enum::checkValue
     */
    public function setCategory(?string $category): void
    {
        $this->category = $category;
    }

    /**
     * Returns Counterparty.
     * The destination or the source of the funds, depending on the sweep `type`.
     *
     * Either a `balanceAccountId`, `transferInstrumentId`, or `merchantAccount` is required.
     */
    public function getCounterparty(): SweepCounterparty1
    {
        return $this->counterparty;
    }

    /**
     * Sets Counterparty.
     * The destination or the source of the funds, depending on the sweep `type`.
     *
     * Either a `balanceAccountId`, `transferInstrumentId`, or `merchantAccount` is required.
     *
     * @required
     * @maps counterparty
     */
    public function setCounterparty(SweepCounterparty1 $counterparty): void
    {
        $this->counterparty = $counterparty;
    }

    /**
     * Returns Currency.
     * The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes)
     * in uppercase. For example, **EUR**.
     *
     * The sweep currency must match any of the [balances currencies](https://docs.adyen.com/api-
     * explorer/#/balanceplatform/latest/get/balanceAccounts/{id}__resParam_balances).
     */
    public function getCurrency(): string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     * The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes)
     * in uppercase. For example, **EUR**.
     *
     * The sweep currency must match any of the [balances currencies](https://docs.adyen.com/api-
     * explorer/#/balanceplatform/latest/get/balanceAccounts/{id}__resParam_balances).
     *
     * @required
     * @maps currency
     */
    public function setCurrency(string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Description.
     * The message that will be used in the sweep transfer's description body with a maximum length of 140
     * characters.
     *
     * If the message is longer after replacing placeholders, the message will be cut off at 140 characters.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * The message that will be used in the sweep transfer's description body with a maximum length of 140
     * characters.
     *
     * If the message is longer after replacing placeholders, the message will be cut off at 140 characters.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Priorities.
     * The list of priorities for the bank transfer. This sets the speed at which the transfer is sent and
     * the fees that you have to pay. You can provide multiple priorities, ordered by your preference.
     * Adyen will try to pay out using the priorities in the given order. If the first priority is not
     * currently supported or enabled for your platform, the system will try the next one, and so on.
     *
     * The request will be accepted as long as **at least one** of the provided priorities is valid (i.e.,
     * supported by Adyen and activated for your platform). For example, if you provide `["wire",
     * "regular"]`, and `wire` is not supported but `regular` is, the request will still be accepted and
     * processed.
     *
     * Possible values:
     *
     * * **regular**: For normal, low-value transactions.
     *
     * * **fast**: A faster way to transfer funds, but the fees are higher. Recommended for high-priority,
     * low-value transactions.
     *
     * * **wire**: The fastest way to transfer funds, but this has the highest fees. Recommended for high-
     * priority, high-value transactions.
     *
     * * **instant**: For instant funds transfers within the United States and in [SEPA locations](https:
     * //www.ecb.europa.eu/paym/integration/retail/sepa/html/index.en.html).
     *
     * * **crossBorder**: For high-value transfers to a recipient in a different country.
     *
     * * **internal**: For transfers to an Adyen-issued business bank account (by bank account number/IBAN).
     *
     * Set `category` to **bank**. For more details, see optional priorities setup for [marketplaces](https:
     * //docs.adyen.com/marketplaces/payout-to-users/scheduled-payouts#optional-priorities-setup) or
     * [platforms](https://docs.adyen.com/platforms/payout-to-users/scheduled-payouts#optional-priorities-
     * setup).
     *
     * @return string[]|null
     */
    public function getPriorities(): ?array
    {
        return $this->priorities;
    }

    /**
     * Sets Priorities.
     * The list of priorities for the bank transfer. This sets the speed at which the transfer is sent and
     * the fees that you have to pay. You can provide multiple priorities, ordered by your preference.
     * Adyen will try to pay out using the priorities in the given order. If the first priority is not
     * currently supported or enabled for your platform, the system will try the next one, and so on.
     *
     * The request will be accepted as long as **at least one** of the provided priorities is valid (i.e.,
     * supported by Adyen and activated for your platform). For example, if you provide `["wire",
     * "regular"]`, and `wire` is not supported but `regular` is, the request will still be accepted and
     * processed.
     *
     * Possible values:
     *
     * * **regular**: For normal, low-value transactions.
     *
     * * **fast**: A faster way to transfer funds, but the fees are higher. Recommended for high-priority,
     * low-value transactions.
     *
     * * **wire**: The fastest way to transfer funds, but this has the highest fees. Recommended for high-
     * priority, high-value transactions.
     *
     * * **instant**: For instant funds transfers within the United States and in [SEPA locations](https:
     * //www.ecb.europa.eu/paym/integration/retail/sepa/html/index.en.html).
     *
     * * **crossBorder**: For high-value transfers to a recipient in a different country.
     *
     * * **internal**: For transfers to an Adyen-issued business bank account (by bank account number/IBAN).
     *
     * Set `category` to **bank**. For more details, see optional priorities setup for [marketplaces](https:
     * //docs.adyen.com/marketplaces/payout-to-users/scheduled-payouts#optional-priorities-setup) or
     * [platforms](https://docs.adyen.com/platforms/payout-to-users/scheduled-payouts#optional-priorities-
     * setup).
     *
     * @maps priorities
     * @factory \AdyenLib\Models\Priority1Enum::checkValue
     *
     * @param string[]|null $priorities
     */
    public function setPriorities(?array $priorities): void
    {
        $this->priorities = $priorities;
    }

    /**
     * Returns Reason.
     * The reason for disabling the sweep.
     */
    public function getReason(): ?string
    {
        return $this->reason;
    }

    /**
     * Sets Reason.
     * The reason for disabling the sweep.
     *
     * @maps reason
     * @factory \AdyenLib\Models\ReasonEnum::checkValue
     */
    public function setReason(?string $reason): void
    {
        $this->reason = $reason;
    }

    /**
     * Returns Reason Detail.
     * The human readable reason for disabling the sweep.
     */
    public function getReasonDetail(): ?string
    {
        return $this->reasonDetail;
    }

    /**
     * Sets Reason Detail.
     * The human readable reason for disabling the sweep.
     *
     * @maps reasonDetail
     */
    public function setReasonDetail(?string $reasonDetail): void
    {
        $this->reasonDetail = $reasonDetail;
    }

    /**
     * Returns Reference.
     * Your reference for the sweep configuration.
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * Your reference for the sweep configuration.
     *
     * @maps reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Reference for Beneficiary.
     * The reference sent to or received from the counterparty. Only alphanumeric characters are allowed.
     */
    public function getReferenceForBeneficiary(): ?string
    {
        return $this->referenceForBeneficiary;
    }

    /**
     * Sets Reference for Beneficiary.
     * The reference sent to or received from the counterparty. Only alphanumeric characters are allowed.
     *
     * @maps referenceForBeneficiary
     */
    public function setReferenceForBeneficiary(?string $referenceForBeneficiary): void
    {
        $this->referenceForBeneficiary = $referenceForBeneficiary;
    }

    /**
     * Returns Schedule.
     * The schedule when the `triggerAmount` is evaluated. If the balance meets the threshold, funds are
     * pushed out of or pulled in to the balance account.
     */
    public function getSchedule(): SweepSchedule1
    {
        return $this->schedule;
    }

    /**
     * Sets Schedule.
     * The schedule when the `triggerAmount` is evaluated. If the balance meets the threshold, funds are
     * pushed out of or pulled in to the balance account.
     *
     * @required
     * @maps schedule
     */
    public function setSchedule(SweepSchedule1 $schedule): void
    {
        $this->schedule = $schedule;
    }

    /**
     * Returns Status.
     * The status of the sweep. If not provided, by default, this is set to **active**.
     *
     * Possible values:
     *
     * * **active**:  the sweep is enabled and funds will be pulled in or pushed out based on the defined
     * configuration.
     *
     * * **inactive**: the sweep is disabled and cannot be triggered.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status of the sweep. If not provided, by default, this is set to **active**.
     *
     * Possible values:
     *
     * * **active**:  the sweep is enabled and funds will be pulled in or pushed out based on the defined
     * configuration.
     *
     * * **inactive**: the sweep is disabled and cannot be triggered.
     *
     * @maps status
     * @factory \AdyenLib\Models\Status6Enum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Sweep Amount.
     * The amount that must be pushed out or pulled in. You can configure either `sweepAmount` or
     * `targetAmount`, not both.
     */
    public function getSweepAmount(): ?Amount17
    {
        return $this->sweepAmount;
    }

    /**
     * Sets Sweep Amount.
     * The amount that must be pushed out or pulled in. You can configure either `sweepAmount` or
     * `targetAmount`, not both.
     *
     * @maps sweepAmount
     */
    public function setSweepAmount(?Amount17 $sweepAmount): void
    {
        $this->sweepAmount = $sweepAmount;
    }

    /**
     * Returns Target Amount.
     * The amount that must be available in the balance account after the sweep. You can configure either
     * `sweepAmount` or `targetAmount`, not both.
     */
    public function getTargetAmount(): ?Amount17
    {
        return $this->targetAmount;
    }

    /**
     * Sets Target Amount.
     * The amount that must be available in the balance account after the sweep. You can configure either
     * `sweepAmount` or `targetAmount`, not both.
     *
     * @maps targetAmount
     */
    public function setTargetAmount(?Amount17 $targetAmount): void
    {
        $this->targetAmount = $targetAmount;
    }

    /**
     * Returns Trigger Amount.
     * The threshold amount that triggers the sweep. If not provided, by default, the amount is set to zero.
     * The `triggerAmount` is evaluated according to the specified `schedule.type`.
     *
     * * For `type` **pull**, if the balance is less than or equal to the `triggerAmount`, funds are pulled
     * in to the balance account.
     *
     * * For `type` **push**, if the balance is more than or equal to the `triggerAmount`, funds are pushed
     * out of the balance account.
     */
    public function getTriggerAmount(): ?Amount17
    {
        return $this->triggerAmount;
    }

    /**
     * Sets Trigger Amount.
     * The threshold amount that triggers the sweep. If not provided, by default, the amount is set to zero.
     * The `triggerAmount` is evaluated according to the specified `schedule.type`.
     *
     * * For `type` **pull**, if the balance is less than or equal to the `triggerAmount`, funds are pulled
     * in to the balance account.
     *
     * * For `type` **push**, if the balance is more than or equal to the `triggerAmount`, funds are pushed
     * out of the balance account.
     *
     * @maps triggerAmount
     */
    public function setTriggerAmount(?Amount17 $triggerAmount): void
    {
        $this->triggerAmount = $triggerAmount;
    }

    /**
     * Returns Type.
     * The direction of sweep, whether pushing out or pulling in funds to the balance account. If not
     * provided, by default, this is set to **push**.
     *
     * Possible values:
     *
     * * **push**: _push out funds_ to a destination balance account or transfer instrument.
     *
     * * **pull**: _pull in funds_ from a source merchant account, transfer instrument, or balance account.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The direction of sweep, whether pushing out or pulling in funds to the balance account. If not
     * provided, by default, this is set to **push**.
     *
     * Possible values:
     *
     * * **push**: _push out funds_ to a destination balance account or transfer instrument.
     *
     * * **pull**: _pull in funds_ from a source merchant account, transfer instrument, or balance account.
     *
     * @maps type
     * @factory \AdyenLib\Models\Type72Enum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the CreateSweepConfigurationV2 object to a human-readable string representation.
     *
     * @return string The string representation of the CreateSweepConfigurationV2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateSweepConfigurationV2',
            [
                'category' => $this->category,
                'counterparty' => $this->counterparty,
                'currency' => $this->currency,
                'description' => $this->description,
                'priorities' => $this->priorities,
                'reason' => $this->reason,
                'reasonDetail' => $this->reasonDetail,
                'reference' => $this->reference,
                'referenceForBeneficiary' => $this->referenceForBeneficiary,
                'schedule' => $this->schedule,
                'status' => $this->status,
                'sweepAmount' => $this->sweepAmount,
                'targetAmount' => $this->targetAmount,
                'triggerAmount' => $this->triggerAmount,
                'type' => $this->type
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->category)) {
            $json['category']                = Category1Enum::checkValue($this->category);
        }
        $json['counterparty']                = $this->counterparty;
        $json['currency']                    = $this->currency;
        if (isset($this->description)) {
            $json['description']             = $this->description;
        }
        if (isset($this->priorities)) {
            $json['priorities']              = Priority1Enum::checkValue($this->priorities);
        }
        if (isset($this->reason)) {
            $json['reason']                  = ReasonEnum::checkValue($this->reason);
        }
        if (isset($this->reasonDetail)) {
            $json['reasonDetail']            = $this->reasonDetail;
        }
        if (isset($this->reference)) {
            $json['reference']               = $this->reference;
        }
        if (isset($this->referenceForBeneficiary)) {
            $json['referenceForBeneficiary'] = $this->referenceForBeneficiary;
        }
        $json['schedule']                    = $this->schedule;
        if (isset($this->status)) {
            $json['status']                  = Status6Enum::checkValue($this->status);
        }
        if (isset($this->sweepAmount)) {
            $json['sweepAmount']             = $this->sweepAmount;
        }
        if (isset($this->targetAmount)) {
            $json['targetAmount']            = $this->targetAmount;
        }
        if (isset($this->triggerAmount)) {
            $json['triggerAmount']           = $this->triggerAmount;
        }
        if (isset($this->type)) {
            $json['type']                    = Type72Enum::checkValue($this->type);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
