<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class DeleteSignatoriesRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $accountHolderCode;

    /**
     * @var string[]
     */
    private $signatoryCodes;

    /**
     * @param string $accountHolderCode
     * @param string[] $signatoryCodes
     */
    public function __construct(string $accountHolderCode, array $signatoryCodes)
    {
        $this->accountHolderCode = $accountHolderCode;
        $this->signatoryCodes = $signatoryCodes;
    }

    /**
     * Returns Account Holder Code.
     * The code of the account holder from which to delete the signatories.
     */
    public function getAccountHolderCode(): string
    {
        return $this->accountHolderCode;
    }

    /**
     * Sets Account Holder Code.
     * The code of the account holder from which to delete the signatories.
     *
     * @required
     * @maps accountHolderCode
     */
    public function setAccountHolderCode(string $accountHolderCode): void
    {
        $this->accountHolderCode = $accountHolderCode;
    }

    /**
     * Returns Signatory Codes.
     * Array of codes of the signatories to be deleted.
     *
     * @return string[]
     */
    public function getSignatoryCodes(): array
    {
        return $this->signatoryCodes;
    }

    /**
     * Sets Signatory Codes.
     * Array of codes of the signatories to be deleted.
     *
     * @required
     * @maps signatoryCodes
     *
     * @param string[] $signatoryCodes
     */
    public function setSignatoryCodes(array $signatoryCodes): void
    {
        $this->signatoryCodes = $signatoryCodes;
    }

    /**
     * Converts the DeleteSignatoriesRequest object to a human-readable string representation.
     *
     * @return string The string representation of the DeleteSignatoriesRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'DeleteSignatoriesRequest',
            ['accountHolderCode' => $this->accountHolderCode, 'signatoryCodes' => $this->signatoryCodes]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['accountHolderCode'] = $this->accountHolderCode;
        $json['signatoryCodes']    = $this->signatoryCodes;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
