<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class DeliveryContact implements \JsonSerializable
{
    /**
     * @var StoreLocation
     */
    private $address;

    /**
     * @var string|null
     */
    private $company;

    /**
     * @var string|null
     */
    private $email;

    /**
     * @var string|null
     */
    private $fullPhoneNumber;

    /**
     * @var Name
     */
    private $name;

    /**
     * @var ViasPhoneNumber|null
     */
    private $phoneNumber;

    /**
     * @var string|null
     */
    private $webAddress;

    /**
     * @param StoreLocation $address
     * @param Name $name
     */
    public function __construct(StoreLocation $address, Name $name)
    {
        $this->address = $address;
        $this->name = $name;
    }

    /**
     * Returns Address.
     * The address of the contact.
     */
    public function getAddress(): StoreLocation
    {
        return $this->address;
    }

    /**
     * Sets Address.
     * The address of the contact.
     *
     * @required
     * @maps address
     */
    public function setAddress(StoreLocation $address): void
    {
        $this->address = $address;
    }

    /**
     * Returns Company.
     * The company name of the contact.
     */
    public function getCompany(): ?string
    {
        return $this->company;
    }

    /**
     * Sets Company.
     * The company name of the contact.
     *
     * @maps company
     */
    public function setCompany(?string $company): void
    {
        $this->company = $company;
    }

    /**
     * Returns Email.
     * The email address of the contact.
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     * The email address of the contact.
     *
     * @maps email
     */
    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Full Phone Number.
     * The full phone number of the contact provided as a single string. It will be handled as a landline
     * phone.
     * **Examples:** "0031 6 11 22 33 44", "+316/1122-3344", "(0031) 611223344"
     */
    public function getFullPhoneNumber(): ?string
    {
        return $this->fullPhoneNumber;
    }

    /**
     * Sets Full Phone Number.
     * The full phone number of the contact provided as a single string. It will be handled as a landline
     * phone.
     * **Examples:** "0031 6 11 22 33 44", "+316/1122-3344", "(0031) 611223344"
     *
     * @maps fullPhoneNumber
     */
    public function setFullPhoneNumber(?string $fullPhoneNumber): void
    {
        $this->fullPhoneNumber = $fullPhoneNumber;
    }

    /**
     * Returns Name.
     * The name of the contact.
     */
    public function getName(): Name
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of the contact.
     *
     * @required
     * @maps name
     */
    public function setName(Name $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Phone Number.
     * The phone number of the contact.
     */
    public function getPhoneNumber(): ?ViasPhoneNumber
    {
        return $this->phoneNumber;
    }

    /**
     * Sets Phone Number.
     * The phone number of the contact.
     *
     * @maps phoneNumber
     */
    public function setPhoneNumber(?ViasPhoneNumber $phoneNumber): void
    {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * Returns Web Address.
     * The URL of the contact's website.
     */
    public function getWebAddress(): ?string
    {
        return $this->webAddress;
    }

    /**
     * Sets Web Address.
     * The URL of the contact's website.
     *
     * @maps webAddress
     */
    public function setWebAddress(?string $webAddress): void
    {
        $this->webAddress = $webAddress;
    }

    /**
     * Converts the DeliveryContact object to a human-readable string representation.
     *
     * @return string The string representation of the DeliveryContact object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'DeliveryContact',
            [
                'address' => $this->address,
                'company' => $this->company,
                'email' => $this->email,
                'fullPhoneNumber' => $this->fullPhoneNumber,
                'name' => $this->name,
                'phoneNumber' => $this->phoneNumber,
                'webAddress' => $this->webAddress
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['address']             = $this->address;
        if (isset($this->company)) {
            $json['company']         = $this->company;
        }
        if (isset($this->email)) {
            $json['email']           = $this->email;
        }
        if (isset($this->fullPhoneNumber)) {
            $json['fullPhoneNumber'] = $this->fullPhoneNumber;
        }
        $json['name']                = $this->name;
        if (isset($this->phoneNumber)) {
            $json['phoneNumber']     = $this->phoneNumber;
        }
        if (isset($this->webAddress)) {
            $json['webAddress']      = $this->webAddress;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
