<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class DisputeAttachment implements \JsonSerializable
{
    /**
     * @var string
     */
    private $attachmentType;

    /**
     * @var string
     */
    private $content;

    /**
     * @var string
     */
    private $fileName;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @param string $attachmentType
     * @param string $content
     * @param string $fileName
     */
    public function __construct(string $attachmentType, string $content, string $fileName)
    {
        $this->attachmentType = $attachmentType;
        $this->content = $content;
        $this->fileName = $fileName;
    }

    /**
     * Returns Attachment Type.
     * The type of information contained in the attachment: **receipt**, **correspondence**, **other**.
     */
    public function getAttachmentType(): string
    {
        return $this->attachmentType;
    }

    /**
     * Sets Attachment Type.
     * The type of information contained in the attachment: **receipt**, **correspondence**, **other**.
     *
     * @required
     * @maps attachmentType
     * @factory \AdyenLib\Models\AttachmentType1Enum::checkValue
     */
    public function setAttachmentType(string $attachmentType): void
    {
        $this->attachmentType = $attachmentType;
    }

    /**
     * Returns Content.
     * The content of the image. An attachment must be base64-encoded data. Make sure that all base64-
     * encoded data strings are generated without line breaks or "wrapping". For example, do not use
     * `Base64.NO_WRAP` in Java, or its equivalent in other languages. Newline characters at the end of the
     * base64-encoded data string will also result in a malformed input error.
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * Sets Content.
     * The content of the image. An attachment must be base64-encoded data. Make sure that all base64-
     * encoded data strings are generated without line breaks or "wrapping". For example, do not use
     * `Base64.NO_WRAP` in Java, or its equivalent in other languages. Newline characters at the end of the
     * base64-encoded data string will also result in a malformed input error.
     *
     * @required
     * @maps content
     */
    public function setContent(string $content): void
    {
        $this->content = $content;
    }

    /**
     * Returns File Name.
     * The name of the attachment, including its filename extension. Supported filename extensions:
     * **jpeg**, **pdf**, **tiff**.
     */
    public function getFileName(): string
    {
        return $this->fileName;
    }

    /**
     * Sets File Name.
     * The name of the attachment, including its filename extension. Supported filename extensions:
     * **jpeg**, **pdf**, **tiff**.
     *
     * @required
     * @maps fileName
     */
    public function setFileName(string $fileName): void
    {
        $this->fileName = $fileName;
    }

    /**
     * Returns Id.
     * The unique identifier of the attachment.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The unique identifier of the attachment.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Converts the DisputeAttachment object to a human-readable string representation.
     *
     * @return string The string representation of the DisputeAttachment object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'DisputeAttachment',
            [
                'attachmentType' => $this->attachmentType,
                'content' => $this->content,
                'fileName' => $this->fileName,
                'id' => $this->id
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['attachmentType'] = AttachmentType1Enum::checkValue($this->attachmentType);
        $json['content']        = $this->content;
        $json['fileName']       = $this->fileName;
        if (isset($this->id)) {
            $json['id']         = $this->id;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
