<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

/**
 * It conveys the result of the Enable Service processing.
 * Content of the Enable Service Response message.
 */
class EnableServiceResponse implements \JsonSerializable
{
    /**
     * @var Response11
     */
    private $response;

    /**
     * @param Response11 $response
     */
    public function __construct(Response11 $response)
    {
        $this->response = $response;
    }

    /**
     * Returns Response.
     * Result of a message request processing.
     */
    public function getResponse(): Response11
    {
        return $this->response;
    }

    /**
     * Sets Response.
     * Result of a message request processing.
     *
     * @required
     * @maps Response
     */
    public function setResponse(Response11 $response): void
    {
        $this->response = $response;
    }

    /**
     * Converts the EnableServiceResponse object to a human-readable string representation.
     *
     * @return string The string representation of the EnableServiceResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('EnableServiceResponse', ['response' => $this->response]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Response'] = $this->response;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
