<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use AdyenLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Content of the EventNotification message.
 * It conveys Information related to the event, and possible action (maintenance, message to display).
 */
class EventNotification implements \JsonSerializable
{
    /**
     * @var \DateTime
     */
    private $timeStamp;

    /**
     * @var string
     */
    private $eventToNotify;

    /**
     * @var string|null
     */
    private $eventDetails;

    /**
     * @var string|null
     */
    private $rejectedMessage;

    /**
     * @var bool|null
     */
    private $maintenanceRequiredFlag = false;

    /**
     * @var DisplayOutput[]|null
     */
    private $displayOutput;

    /**
     * @param \DateTime $timeStamp
     * @param string $eventToNotify
     */
    public function __construct(\DateTime $timeStamp, string $eventToNotify)
    {
        $this->timeStamp = $timeStamp;
        $this->eventToNotify = $eventToNotify;
    }

    /**
     * Returns Time Stamp.
     * Date and time of a transaction for the Sale System, the POI System or the Acquirer.
     */
    public function getTimeStamp(): \DateTime
    {
        return $this->timeStamp;
    }

    /**
     * Sets Time Stamp.
     * Date and time of a transaction for the Sale System, the POI System or the Acquirer.
     *
     * @required
     * @maps TimeStamp
     * @factory \AdyenLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTimeStamp(\DateTime $timeStamp): void
    {
        $this->timeStamp = $timeStamp;
    }

    /**
     * Returns Event to Notify.
     * Event the POI notifies to the Sale System.
     * Possible values:
     * * **Abort**
     * * **BeginMaintenance**
     * * **CardInserted**
     * * **CardRemoved**
     * * **Completed**
     * * **CustomerLanguage**
     * * **EndMaintenance**
     * * **Initialised**
     * * **KeyPressed**
     * * **OutOfOrder**
     * * **Reject**
     * * **SaleAdmin**
     * * **SaleWakeUp**
     * * **ScanBarcodeResult**
     * * **SecurityAlarm**
     * * **Shutdown**
     * * **StopAssistance**
     * * **UseAnotherCardForPreauth**
     */
    public function getEventToNotify(): string
    {
        return $this->eventToNotify;
    }

    /**
     * Sets Event to Notify.
     * Event the POI notifies to the Sale System.
     * Possible values:
     * * **Abort**
     * * **BeginMaintenance**
     * * **CardInserted**
     * * **CardRemoved**
     * * **Completed**
     * * **CustomerLanguage**
     * * **EndMaintenance**
     * * **Initialised**
     * * **KeyPressed**
     * * **OutOfOrder**
     * * **Reject**
     * * **SaleAdmin**
     * * **SaleWakeUp**
     * * **ScanBarcodeResult**
     * * **SecurityAlarm**
     * * **Shutdown**
     * * **StopAssistance**
     * * **UseAnotherCardForPreauth**
     *
     * @required
     * @maps EventToNotify
     * @factory \AdyenLib\Models\EventToNotify1Enum::checkValue
     */
    public function setEventToNotify(string $eventToNotify): void
    {
        $this->eventToNotify = $eventToNotify;
    }

    /**
     * Returns Event Details.
     * Information about the event the POI notifies to the Sale System.
     * If present, the Sale logs it for further examination.
     */
    public function getEventDetails(): ?string
    {
        return $this->eventDetails;
    }

    /**
     * Sets Event Details.
     * Information about the event the POI notifies to the Sale System.
     * If present, the Sale logs it for further examination.
     *
     * @maps EventDetails
     */
    public function setEventDetails(?string $eventDetails): void
    {
        $this->eventDetails = $eventDetails;
    }

    /**
     * Returns Rejected Message.
     * Message request rejected by the receiver.
     * Mandatory if EventToNotify is Reject, absent in other cases.
     */
    public function getRejectedMessage(): ?string
    {
        return $this->rejectedMessage;
    }

    /**
     * Sets Rejected Message.
     * Message request rejected by the receiver.
     * Mandatory if EventToNotify is Reject, absent in other cases.
     *
     * @maps RejectedMessage
     */
    public function setRejectedMessage(?string $rejectedMessage): void
    {
        $this->rejectedMessage = $rejectedMessage;
    }

    /**
     * Returns Maintenance Required Flag.
     * Indicates if the occurred event requires maintenance call or action.
     */
    public function getMaintenanceRequiredFlag(): ?bool
    {
        return $this->maintenanceRequiredFlag;
    }

    /**
     * Sets Maintenance Required Flag.
     * Indicates if the occurred event requires maintenance call or action.
     *
     * @maps MaintenanceRequiredFlag
     */
    public function setMaintenanceRequiredFlag(?bool $maintenanceRequiredFlag): void
    {
        $this->maintenanceRequiredFlag = $maintenanceRequiredFlag;
    }

    /**
     * Returns Display Output.
     * Information to display and the way to process the display.
     * To display an event message.
     *
     * @return DisplayOutput[]|null
     */
    public function getDisplayOutput(): ?array
    {
        return $this->displayOutput;
    }

    /**
     * Sets Display Output.
     * Information to display and the way to process the display.
     * To display an event message.
     *
     * @maps DisplayOutput
     *
     * @param DisplayOutput[]|null $displayOutput
     */
    public function setDisplayOutput(?array $displayOutput): void
    {
        $this->displayOutput = $displayOutput;
    }

    /**
     * Converts the EventNotification object to a human-readable string representation.
     *
     * @return string The string representation of the EventNotification object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EventNotification',
            [
                'timeStamp' => $this->timeStamp,
                'eventToNotify' => $this->eventToNotify,
                'eventDetails' => $this->eventDetails,
                'rejectedMessage' => $this->rejectedMessage,
                'maintenanceRequiredFlag' => $this->maintenanceRequiredFlag,
                'displayOutput' => $this->displayOutput
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['TimeStamp']                   = DateTimeHelper::toRfc3339DateTime($this->timeStamp);
        $json['EventToNotify']               = EventToNotify1Enum::checkValue($this->eventToNotify);
        if (isset($this->eventDetails)) {
            $json['EventDetails']            = $this->eventDetails;
        }
        if (isset($this->rejectedMessage)) {
            $json['RejectedMessage']         = $this->rejectedMessage;
        }
        if (isset($this->maintenanceRequiredFlag)) {
            $json['MaintenanceRequiredFlag'] = $this->maintenanceRequiredFlag;
        }
        if (isset($this->displayOutput)) {
            $json['DisplayOutput']           = $this->displayOutput;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
