<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class GetPciUrlResponse implements \JsonSerializable
{
    /**
     * @var ErrorFieldType[]|null
     */
    private $invalidFields;

    /**
     * @var string|null
     */
    private $pspReference;

    /**
     * @var string|null
     */
    private $redirectUrl;

    /**
     * @var string|null
     */
    private $resultCode;

    /**
     * Returns Invalid Fields.
     * Information about any invalid fields.
     *
     * @return ErrorFieldType[]|null
     */
    public function getInvalidFields(): ?array
    {
        return $this->invalidFields;
    }

    /**
     * Sets Invalid Fields.
     * Information about any invalid fields.
     *
     * @maps invalidFields
     *
     * @param ErrorFieldType[]|null $invalidFields
     */
    public function setInvalidFields(?array $invalidFields): void
    {
        $this->invalidFields = $invalidFields;
    }

    /**
     * Returns Psp Reference.
     * The reference of a request. Can be used to uniquely identify the request.
     */
    public function getPspReference(): ?string
    {
        return $this->pspReference;
    }

    /**
     * Sets Psp Reference.
     * The reference of a request. Can be used to uniquely identify the request.
     *
     * @maps pspReference
     */
    public function setPspReference(?string $pspReference): void
    {
        $this->pspReference = $pspReference;
    }

    /**
     * Returns Redirect Url.
     * The URL to the PCI compliance questionnaire where you should redirect your account holder. This URL
     * must be used within 30 seconds and can only be used once.
     */
    public function getRedirectUrl(): ?string
    {
        return $this->redirectUrl;
    }

    /**
     * Sets Redirect Url.
     * The URL to the PCI compliance questionnaire where you should redirect your account holder. This URL
     * must be used within 30 seconds and can only be used once.
     *
     * @maps redirectUrl
     */
    public function setRedirectUrl(?string $redirectUrl): void
    {
        $this->redirectUrl = $redirectUrl;
    }

    /**
     * Returns Result Code.
     * The result code.
     */
    public function getResultCode(): ?string
    {
        return $this->resultCode;
    }

    /**
     * Sets Result Code.
     * The result code.
     *
     * @maps resultCode
     */
    public function setResultCode(?string $resultCode): void
    {
        $this->resultCode = $resultCode;
    }

    /**
     * Converts the GetPciUrlResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetPciUrlResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetPciUrlResponse',
            [
                'invalidFields' => $this->invalidFields,
                'pspReference' => $this->pspReference,
                'redirectUrl' => $this->redirectUrl,
                'resultCode' => $this->resultCode
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->invalidFields)) {
            $json['invalidFields'] = $this->invalidFields;
        }
        if (isset($this->pspReference)) {
            $json['pspReference']  = $this->pspReference;
        }
        if (isset($this->redirectUrl)) {
            $json['redirectUrl']   = $this->redirectUrl;
        }
        if (isset($this->resultCode)) {
            $json['resultCode']    = $this->resultCode;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
