<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class GetTerminalsUnderAccountRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $companyAccount;

    /**
     * @var string|null
     */
    private $merchantAccount;

    /**
     * @var string|null
     */
    private $store;

    /**
     * @param string $companyAccount
     */
    public function __construct(string $companyAccount)
    {
        $this->companyAccount = $companyAccount;
    }

    /**
     * Returns Company Account.
     * Your company account. If you only specify this parameter, the response includes all terminals at all
     * account levels.
     */
    public function getCompanyAccount(): string
    {
        return $this->companyAccount;
    }

    /**
     * Sets Company Account.
     * Your company account. If you only specify this parameter, the response includes all terminals at all
     * account levels.
     *
     * @required
     * @maps companyAccount
     */
    public function setCompanyAccount(string $companyAccount): void
    {
        $this->companyAccount = $companyAccount;
    }

    /**
     * Returns Merchant Account.
     * The merchant account. This is required if you are retrieving the terminals assigned to a store.If
     * you don't specify a `store` the response includes the terminals assigned to the specified merchant
     * account and the terminals assigned to the stores under this merchant account.
     */
    public function getMerchantAccount(): ?string
    {
        return $this->merchantAccount;
    }

    /**
     * Sets Merchant Account.
     * The merchant account. This is required if you are retrieving the terminals assigned to a store.If
     * you don't specify a `store` the response includes the terminals assigned to the specified merchant
     * account and the terminals assigned to the stores under this merchant account.
     *
     * @maps merchantAccount
     */
    public function setMerchantAccount(?string $merchantAccount): void
    {
        $this->merchantAccount = $merchantAccount;
    }

    /**
     * Returns Store.
     * The store code of the store. With this parameter, the response only includes the terminals assigned
     * to the specified store.
     */
    public function getStore(): ?string
    {
        return $this->store;
    }

    /**
     * Sets Store.
     * The store code of the store. With this parameter, the response only includes the terminals assigned
     * to the specified store.
     *
     * @maps store
     */
    public function setStore(?string $store): void
    {
        $this->store = $store;
    }

    /**
     * Converts the GetTerminalsUnderAccountRequest object to a human-readable string representation.
     *
     * @return string The string representation of the GetTerminalsUnderAccountRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetTerminalsUnderAccountRequest',
            [
                'companyAccount' => $this->companyAccount,
                'merchantAccount' => $this->merchantAccount,
                'store' => $this->store
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['companyAccount']      = $this->companyAccount;
        if (isset($this->merchantAccount)) {
            $json['merchantAccount'] = $this->merchantAccount;
        }
        if (isset($this->store)) {
            $json['store']           = $this->store;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
