<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class GetTaxFormResponse1 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $content;

    /**
     * @var string|null
     */
    private $contentType;

    /**
     * @param string $content
     */
    public function __construct(string $content)
    {
        $this->content = $content;
    }

    /**
     * Returns Content.
     * The content of the tax form in Base64 format.
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * Sets Content.
     * The content of the tax form in Base64 format.
     *
     * @required
     * @maps content
     */
    public function setContent(string $content): void
    {
        $this->content = $content;
    }

    /**
     * Returns Content Type.
     * The content type of the tax form.
     *
     * Possible values:
     * *  **application/pdf**
     */
    public function getContentType(): ?string
    {
        return $this->contentType;
    }

    /**
     * Sets Content Type.
     * The content type of the tax form.
     *
     * Possible values:
     * *  **application/pdf**
     *
     * @maps contentType
     * @factory \AdyenLib\Models\ContentTypeEnum::checkValue
     */
    public function setContentType(?string $contentType): void
    {
        $this->contentType = $contentType;
    }

    /**
     * Converts the GetTaxFormResponse1 object to a human-readable string representation.
     *
     * @return string The string representation of the GetTaxFormResponse1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetTaxFormResponse1',
            ['content' => $this->content, 'contentType' => $this->contentType]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['content']         = $this->content;
        if (isset($this->contentType)) {
            $json['contentType'] = ContentTypeEnum::checkValue($this->contentType);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
