<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

/**
 * Content of the Reconciliation Response message.
 * It conveys Information related to the Reconciliation transaction processed by the POI System.
 */
class GetTotalsResponse implements \JsonSerializable
{
    /**
     * @var Response11
     */
    private $response;

    /**
     * @var int
     */
    private $pOIReconciliationID;

    /**
     * @var TransactionTotals[]|null
     */
    private $transactionTotals;

    /**
     * @param Response11 $response
     * @param int $pOIReconciliationID
     */
    public function __construct(Response11 $response, int $pOIReconciliationID)
    {
        $this->response = $response;
        $this->pOIReconciliationID = $pOIReconciliationID;
    }

    /**
     * Returns Response.
     * Result of a message request processing.
     */
    public function getResponse(): Response11
    {
        return $this->response;
    }

    /**
     * Sets Response.
     * Result of a message request processing.
     *
     * @required
     * @maps Response
     */
    public function setResponse(Response11 $response): void
    {
        $this->response = $response;
    }

    /**
     * Returns P OI Reconciliation ID.
     * Identification of the reconciliation period between Sale and POI.
     */
    public function getPOIReconciliationID(): int
    {
        return $this->pOIReconciliationID;
    }

    /**
     * Sets P OI Reconciliation ID.
     * Identification of the reconciliation period between Sale and POI.
     *
     * @required
     * @maps POIReconciliationID
     */
    public function setPOIReconciliationID(int $pOIReconciliationID): void
    {
        $this->pOIReconciliationID = $pOIReconciliationID;
    }

    /**
     * Returns Transaction Totals.
     * Result of the Sale to POI Reconciliation processing.
     * If `Response.Result` is Success.
     *
     * @return TransactionTotals[]|null
     */
    public function getTransactionTotals(): ?array
    {
        return $this->transactionTotals;
    }

    /**
     * Sets Transaction Totals.
     * Result of the Sale to POI Reconciliation processing.
     * If `Response.Result` is Success.
     *
     * @maps TransactionTotals
     *
     * @param TransactionTotals[]|null $transactionTotals
     */
    public function setTransactionTotals(?array $transactionTotals): void
    {
        $this->transactionTotals = $transactionTotals;
    }

    /**
     * Converts the GetTotalsResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetTotalsResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetTotalsResponse',
            [
                'response' => $this->response,
                'pOIReconciliationID' => $this->pOIReconciliationID,
                'transactionTotals' => $this->transactionTotals
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Response']              = $this->response;
        $json['POIReconciliationID']   = $this->pOIReconciliationID;
        if (isset($this->transactionTotals)) {
            $json['TransactionTotals'] = $this->transactionTotals;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
