<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class HULocalAccountIdentification implements \JsonSerializable
{
    /**
     * @var string
     */
    private $accountNumber;

    /**
     * @var string
     */
    private $type;

    /**
     * @param string $accountNumber
     */
    public function __construct(string $accountNumber)
    {
        $this->accountNumber = $accountNumber;
    }

    /**
     * Returns Account Number.
     * The 24-digit bank account number, without separators or whitespace.
     */
    public function getAccountNumber(): string
    {
        return $this->accountNumber;
    }

    /**
     * Sets Account Number.
     * The 24-digit bank account number, without separators or whitespace.
     *
     * @required
     * @maps accountNumber
     */
    public function setAccountNumber(string $accountNumber): void
    {
        $this->accountNumber = $accountNumber;
    }

    /**
     * Returns Type.
     * **huLocal**
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * **huLocal**
     *
     * @maps type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the HULocalAccountIdentification object to a human-readable string representation.
     *
     * @return string The string representation of the HULocalAccountIdentification object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'HULocalAccountIdentification',
            ['accountNumber' => $this->accountNumber, 'type' => $this->type]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['accountNumber'] = $this->accountNumber;
        $json['type']          = $this->type;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
