<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

/**
 * The settings for in-person donations collected as part of the campaign.
 */
class InPersonDonationSettings2 implements \JsonSerializable
{
    /**
     * @var DonationAmount1|null
     */
    private $defaultAmount;

    /**
     * @var string
     */
    private $displayTextField;

    /**
     * @var string
     */
    private $donationFlow;

    /**
     * @var string|null
     */
    private $donationType;

    /**
     * @var string[]|null
     */
    private $merchantAccounts;

    /**
     * @var int|null
     */
    private $presentCardTimeoutMs;

    /**
     * @var int|null
     */
    private $promptTimeoutMs;

    /**
     * @var string[]|null
     */
    private $storeIds;

    /**
     * @param string $displayTextField
     * @param string $donationFlow
     */
    public function __construct(string $displayTextField, string $donationFlow)
    {
        $this->displayTextField = $displayTextField;
        $this->donationFlow = $donationFlow;
    }

    /**
     * Returns Default Amount.
     * The default amount for donations.
     */
    public function getDefaultAmount(): ?DonationAmount1
    {
        return $this->defaultAmount;
    }

    /**
     * Sets Default Amount.
     * The default amount for donations.
     *
     * @maps defaultAmount
     */
    public function setDefaultAmount(?DonationAmount1 $defaultAmount): void
    {
        $this->defaultAmount = $defaultAmount;
    }

    /**
     * Returns Display Text Field.
     * The text shown on the payment terminal, either the name or the cause of the nonprofit organization.
     */
    public function getDisplayTextField(): string
    {
        return $this->displayTextField;
    }

    /**
     * Sets Display Text Field.
     * The text shown on the payment terminal, either the name or the cause of the nonprofit organization.
     *
     * @required
     * @maps displayTextField
     * @factory \AdyenLib\Models\DisplayTextField2Enum::checkValue
     */
    public function setDisplayTextField(string $displayTextField): void
    {
        $this->displayTextField = $displayTextField;
    }

    /**
     * Returns Donation Flow.
     * The interaction flow for in-person donations. Possible values:
     *
     * - **oneStep**: The shopper presents their payment method for the payment and the donation in one go,
     * after the donation.
     *
     * - **twoStep**: The shopper presents their payment method twice: after the payment and after the
     * donation.
     */
    public function getDonationFlow(): string
    {
        return $this->donationFlow;
    }

    /**
     * Sets Donation Flow.
     * The interaction flow for in-person donations. Possible values:
     *
     * - **oneStep**: The shopper presents their payment method for the payment and the donation in one go,
     * after the donation.
     *
     * - **twoStep**: The shopper presents their payment method twice: after the payment and after the
     * donation.
     *
     * @required
     * @maps donationFlow
     * @factory \AdyenLib\Models\DonationFlow1Enum::checkValue
     */
    public function setDonationFlow(string $donationFlow): void
    {
        $this->donationFlow = $donationFlow;
    }

    /**
     * Returns Donation Type.
     * The type of donation to collect from the shopper. Possible values:
     *
     * - **roundup**: Round up the transaction amount.
     *
     * - **fixedAmounts**: Choose a fixed amount.
     *
     * - **fixedAmountsRoundup**: Round up, or choose a fixed amount.
     */
    public function getDonationType(): ?string
    {
        return $this->donationType;
    }

    /**
     * Sets Donation Type.
     * The type of donation to collect from the shopper. Possible values:
     *
     * - **roundup**: Round up the transaction amount.
     *
     * - **fixedAmounts**: Choose a fixed amount.
     *
     * - **fixedAmountsRoundup**: Round up, or choose a fixed amount.
     *
     * @maps donationType
     * @factory \AdyenLib\Models\DonationType1Enum::checkValue
     */
    public function setDonationType(?string $donationType): void
    {
        $this->donationType = $donationType;
    }

    /**
     * Returns Merchant Accounts.
     * The merchant accounts for this sales channel that are associated with the donation campaign.
     *
     * @return string[]|null
     */
    public function getMerchantAccounts(): ?array
    {
        return $this->merchantAccounts;
    }

    /**
     * Sets Merchant Accounts.
     * The merchant accounts for this sales channel that are associated with the donation campaign.
     *
     * @maps merchantAccounts
     *
     * @param string[]|null $merchantAccounts
     */
    public function setMerchantAccounts(?array $merchantAccounts): void
    {
        $this->merchantAccounts = $merchantAccounts;
    }

    /**
     * Returns Present Card Timeout Ms.
     * Required if `donationFlow` is set to **twoStep**. The time, in milliseconds, that the terminal waits
     * for the shopper to present their card. Defaults to **10000** (10 seconds). Range: 5000 to 15000.
     */
    public function getPresentCardTimeoutMs(): ?int
    {
        return $this->presentCardTimeoutMs;
    }

    /**
     * Sets Present Card Timeout Ms.
     * Required if `donationFlow` is set to **twoStep**. The time, in milliseconds, that the terminal waits
     * for the shopper to present their card. Defaults to **10000** (10 seconds). Range: 5000 to 15000.
     *
     * @maps presentCardTimeoutMs
     */
    public function setPresentCardTimeoutMs(?int $presentCardTimeoutMs): void
    {
        $this->presentCardTimeoutMs = $presentCardTimeoutMs;
    }

    /**
     * Returns Prompt Timeout Ms.
     * The time, in milliseconds, that the terminal waits for the shopper to make a selection on the
     * donation screen. Defaults to **10000** (10 seconds). Range: 5000 to 15000.
     */
    public function getPromptTimeoutMs(): ?int
    {
        return $this->promptTimeoutMs;
    }

    /**
     * Sets Prompt Timeout Ms.
     * The time, in milliseconds, that the terminal waits for the shopper to make a selection on the
     * donation screen. Defaults to **10000** (10 seconds). Range: 5000 to 15000.
     *
     * @maps promptTimeoutMs
     */
    public function setPromptTimeoutMs(?int $promptTimeoutMs): void
    {
        $this->promptTimeoutMs = $promptTimeoutMs;
    }

    /**
     * Returns Store Ids.
     * The Adyen-generated unique identifiers of stores for this sales channel that are associated with the
     * donation campaign.
     *
     * @return string[]|null
     */
    public function getStoreIds(): ?array
    {
        return $this->storeIds;
    }

    /**
     * Sets Store Ids.
     * The Adyen-generated unique identifiers of stores for this sales channel that are associated with the
     * donation campaign.
     *
     * @maps storeIds
     *
     * @param string[]|null $storeIds
     */
    public function setStoreIds(?array $storeIds): void
    {
        $this->storeIds = $storeIds;
    }

    /**
     * Converts the InPersonDonationSettings2 object to a human-readable string representation.
     *
     * @return string The string representation of the InPersonDonationSettings2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InPersonDonationSettings2',
            [
                'defaultAmount' => $this->defaultAmount,
                'displayTextField' => $this->displayTextField,
                'donationFlow' => $this->donationFlow,
                'donationType' => $this->donationType,
                'merchantAccounts' => $this->merchantAccounts,
                'presentCardTimeoutMs' => $this->presentCardTimeoutMs,
                'promptTimeoutMs' => $this->promptTimeoutMs,
                'storeIds' => $this->storeIds
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->defaultAmount)) {
            $json['defaultAmount']        = $this->defaultAmount;
        }
        $json['displayTextField']         = DisplayTextField2Enum::checkValue($this->displayTextField);
        $json['donationFlow']             = DonationFlow1Enum::checkValue($this->donationFlow);
        if (isset($this->donationType)) {
            $json['donationType']         = DonationType1Enum::checkValue($this->donationType);
        }
        if (isset($this->merchantAccounts)) {
            $json['merchantAccounts']     = $this->merchantAccounts;
        }
        if (isset($this->presentCardTimeoutMs)) {
            $json['presentCardTimeoutMs'] = $this->presentCardTimeoutMs;
        }
        if (isset($this->promptTimeoutMs)) {
            $json['promptTimeoutMs']      = $this->promptTimeoutMs;
        }
        if (isset($this->storeIds)) {
            $json['storeIds']             = $this->storeIds;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
