<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The institutional sector the organization operates within.
 */
class InstitutionalSectorEnum
{
    public const NONFINANCIALCORPORATION = 'nonFinancialCorporation';

    public const CENTRALBANK = 'centralBank';

    public const CREDITINSTITUTIONS = 'creditInstitutions';

    public const DEPOSITTAKINGCORPORATIONS = 'depositTakingCorporations';

    public const MONEYMARKETFUNDS = 'moneyMarketFunds';

    public const NONMMFINVESTMENTFUNDS = 'nonMMFInvestmentFunds';

    public const FINANCIALVEHICLECORPORATION = 'financialVehicleCorporation';

    public const OTHERFINANCIALINTERMEDIARIES = 'otherFinancialIntermediaries';

    public const FINANCIALAUXILIARIES = 'financialAuxiliaries';

    public const CAPTIVEFINANCIALINSTITUTIONSANDMONEYLENDERS = 'captiveFinancialInstitutionsAndMoneyLenders';

    public const INSURANCECORPORATIONS = 'insuranceCorporations';

    public const PENSIONFUNDS = 'pensionFunds';

    public const CENTRALGOVERNMENT = 'centralGovernment';

    public const STATEGOVERNMENT = 'stateGovernment';

    public const LOCALGOVERNMENT = 'localGovernment';

    public const SOCIALSECURITYFUNDS = 'socialSecurityFunds';

    public const NONPROFITINSTITUTIONSSERVINGHOUSEHOLDS = 'nonProfitInstitutionsServingHouseholds';

    private const _ALL_VALUES = [
        self::NONFINANCIALCORPORATION,
        self::CENTRALBANK,
        self::CREDITINSTITUTIONS,
        self::DEPOSITTAKINGCORPORATIONS,
        self::MONEYMARKETFUNDS,
        self::NONMMFINVESTMENTFUNDS,
        self::FINANCIALVEHICLECORPORATION,
        self::OTHERFINANCIALINTERMEDIARIES,
        self::FINANCIALAUXILIARIES,
        self::CAPTIVEFINANCIALINSTITUTIONSANDMONEYLENDERS,
        self::INSURANCECORPORATIONS,
        self::PENSIONFUNDS,
        self::CENTRALGOVERNMENT,
        self::STATEGOVERNMENT,
        self::LOCALGOVERNMENT,
        self::SOCIALSECURITYFUNDS,
        self::NONPROFITINSTITUTIONSSERVINGHOUSEHOLDS
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for InstitutionalSectorEnum.");
    }
}
