<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

/**
 * **klarna** or its variant details
 */
class KlarnaResponseInfo1 implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $autoCapture;

    /**
     * @var string|null
     */
    private $disputeEmail;

    /**
     * @var string|null
     */
    private $region;

    /**
     * @var string|null
     */
    private $supportEmail;

    /**
     * Returns Auto Capture.
     * Indicates the status of [Automatic capture](https://docs.adyen.com/online-payments/capture#automatic-
     * capture).
     */
    public function getAutoCapture(): ?bool
    {
        return $this->autoCapture;
    }

    /**
     * Sets Auto Capture.
     * Indicates the status of [Automatic capture](https://docs.adyen.com/online-payments/capture#automatic-
     * capture).
     *
     * @maps autoCapture
     */
    public function setAutoCapture(?bool $autoCapture): void
    {
        $this->autoCapture = $autoCapture;
    }

    /**
     * Returns Dispute Email.
     * The email address for disputes.
     */
    public function getDisputeEmail(): ?string
    {
        return $this->disputeEmail;
    }

    /**
     * Sets Dispute Email.
     * The email address for disputes.
     *
     * @maps disputeEmail
     */
    public function setDisputeEmail(?string $disputeEmail): void
    {
        $this->disputeEmail = $disputeEmail;
    }

    /**
     * Returns Region.
     * The region of operation.
     */
    public function getRegion(): ?string
    {
        return $this->region;
    }

    /**
     * Sets Region.
     * The region of operation.
     *
     * @maps region
     * @factory \AdyenLib\Models\Region1Enum::checkValue
     */
    public function setRegion(?string $region): void
    {
        $this->region = $region;
    }

    /**
     * Returns Support Email.
     * The email address of merchant support.
     */
    public function getSupportEmail(): ?string
    {
        return $this->supportEmail;
    }

    /**
     * Sets Support Email.
     * The email address of merchant support.
     *
     * @maps supportEmail
     */
    public function setSupportEmail(?string $supportEmail): void
    {
        $this->supportEmail = $supportEmail;
    }

    /**
     * Converts the KlarnaResponseInfo1 object to a human-readable string representation.
     *
     * @return string The string representation of the KlarnaResponseInfo1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'KlarnaResponseInfo1',
            [
                'autoCapture' => $this->autoCapture,
                'disputeEmail' => $this->disputeEmail,
                'region' => $this->region,
                'supportEmail' => $this->supportEmail
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->autoCapture)) {
            $json['autoCapture']  = $this->autoCapture;
        }
        if (isset($this->disputeEmail)) {
            $json['disputeEmail'] = $this->disputeEmail;
        }
        if (isset($this->region)) {
            $json['region']       = Region1Enum::checkValue($this->region);
        }
        if (isset($this->supportEmail)) {
            $json['supportEmail'] = $this->supportEmail;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
