<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The form of legal arrangement. Required if `type` is **Trust** or **Partnership**.
 *
 * The possible values depend on the `type`.
 *
 * - For `type` **Trust**:  **CashManagementTrust**, **CorporateUnitTrust**, **DeceasedEstate**,
 * **DiscretionaryInvestmentTrust**, **DiscretionaryServicesManagementTrust**,
 * **DiscretionaryTradingTrust**, **FirstHomeSaverAccountsTrust**, **FixedTrust**, **FixedUnitTrust**,
 * **HybridTrust**, **ListedPublicUnitTrust**, **OtherTrust**, **PooledSuperannuationTrust**,
 * **PublicTradingTrust**, or **UnlistedPublicUnitTrust**.
 *
 * - For `type` **Partnership**: **LimitedPartnership**, **FamilyPartnership**, or
 * **OtherPartnership**
 */
class LegalFormEnum
{
    public const CASHMANAGEMENTTRUST = 'CashManagementTrust';

    public const CORPORATEUNITTRUST = 'CorporateUnitTrust';

    public const DECEASEDESTATE = 'DeceasedEstate';

    public const DISCRETIONARYINVESTMENTTRUST = 'DiscretionaryInvestmentTrust';

    public const DISCRETIONARYSERVICESMANAGEMENTTRUST = 'DiscretionaryServicesManagementTrust';

    public const DISCRETIONARYTRADINGTRUST = 'DiscretionaryTradingTrust';

    public const FIRSTHOMESAVERACCOUNTSTRUST = 'FirstHomeSaverAccountsTrust';

    public const FIXEDTRUST = 'FixedTrust';

    public const FIXEDUNITTRUST = 'FixedUnitTrust';

    public const HYBRIDTRUST = 'HybridTrust';

    public const LISTEDPUBLICUNITTRUST = 'ListedPublicUnitTrust';

    public const OTHERTRUST = 'OtherTrust';

    public const POOLEDSUPERANNUATIONTRUST = 'PooledSuperannuationTrust';

    public const PUBLICTRADINGTRUST = 'PublicTradingTrust';

    public const UNLISTEDPUBLICUNITTRUST = 'UnlistedPublicUnitTrust';

    public const LIMITEDPARTNERSHIP = 'LimitedPartnership';

    public const FAMILYPARTNERSHIP = 'FamilyPartnership';

    public const OTHERPARTNERSHIP = 'OtherPartnership';

    private const _ALL_VALUES = [
        self::CASHMANAGEMENTTRUST,
        self::CORPORATEUNITTRUST,
        self::DECEASEDESTATE,
        self::DISCRETIONARYINVESTMENTTRUST,
        self::DISCRETIONARYSERVICESMANAGEMENTTRUST,
        self::DISCRETIONARYTRADINGTRUST,
        self::FIRSTHOMESAVERACCOUNTSTRUST,
        self::FIXEDTRUST,
        self::FIXEDUNITTRUST,
        self::HYBRIDTRUST,
        self::LISTEDPUBLICUNITTRUST,
        self::OTHERTRUST,
        self::POOLEDSUPERANNUATIONTRUST,
        self::PUBLICTRADINGTRUST,
        self::UNLISTEDPUBLICUNITTRUST,
        self::LIMITEDPARTNERSHIP,
        self::FAMILYPARTNERSHIP,
        self::OTHERPARTNERSHIP
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for LegalFormEnum.");
    }
}
