<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class PatchableFraudInfo implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $cardDoesNotBelongToCardholder;

    /**
     * @var bool|null
     */
    private $cardWasCounterfeited;

    /**
     * @var string|null
     */
    private $descriptionOfIssue;

    /**
     * @var array
     */
    private $reportOnly = [];

    /**
     * Returns Card Does Not Belong to Cardholder.
     * The card is no longer in the cardholder's possession. Set to **true** if the card is lost or stolen.
     */
    public function getCardDoesNotBelongToCardholder(): ?bool
    {
        return $this->cardDoesNotBelongToCardholder;
    }

    /**
     * Sets Card Does Not Belong to Cardholder.
     * The card is no longer in the cardholder's possession. Set to **true** if the card is lost or stolen.
     *
     * @maps cardDoesNotBelongToCardholder
     */
    public function setCardDoesNotBelongToCardholder(?bool $cardDoesNotBelongToCardholder): void
    {
        $this->cardDoesNotBelongToCardholder = $cardDoesNotBelongToCardholder;
    }

    /**
     * Returns Card Was Counterfeited.
     * The card was counterfeited.
     */
    public function getCardWasCounterfeited(): ?bool
    {
        return $this->cardWasCounterfeited;
    }

    /**
     * Sets Card Was Counterfeited.
     * The card was counterfeited.
     *
     * @maps cardWasCounterfeited
     */
    public function setCardWasCounterfeited(?bool $cardWasCounterfeited): void
    {
        $this->cardWasCounterfeited = $cardWasCounterfeited;
    }

    /**
     * Returns Description of Issue.
     * Your description of the issue for raising a dispute of `type` **fraud**.
     */
    public function getDescriptionOfIssue(): ?string
    {
        return $this->descriptionOfIssue;
    }

    /**
     * Sets Description of Issue.
     * Your description of the issue for raising a dispute of `type` **fraud**.
     *
     * @maps descriptionOfIssue
     */
    public function setDescriptionOfIssue(?string $descriptionOfIssue): void
    {
        $this->descriptionOfIssue = $descriptionOfIssue;
    }

    /**
     * Returns Report Only.
     * Set to **true** to report fraud to Adyen with no further action, such as a request for a chargeback
     * or fee reversal. The default value is **false**.
     */
    public function getReportOnly(): ?bool
    {
        if (count($this->reportOnly) == 0) {
            return null;
        }
        return $this->reportOnly['value'];
    }

    /**
     * Sets Report Only.
     * Set to **true** to report fraud to Adyen with no further action, such as a request for a chargeback
     * or fee reversal. The default value is **false**.
     *
     * @maps reportOnly
     */
    public function setReportOnly(?bool $reportOnly): void
    {
        $this->reportOnly['value'] = $reportOnly;
    }

    /**
     * Unsets Report Only.
     * Set to **true** to report fraud to Adyen with no further action, such as a request for a chargeback
     * or fee reversal. The default value is **false**.
     */
    public function unsetReportOnly(): void
    {
        $this->reportOnly = [];
    }

    /**
     * Converts the PatchableFraudInfo object to a human-readable string representation.
     *
     * @return string The string representation of the PatchableFraudInfo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PatchableFraudInfo',
            [
                'cardDoesNotBelongToCardholder' => $this->cardDoesNotBelongToCardholder,
                'cardWasCounterfeited' => $this->cardWasCounterfeited,
                'descriptionOfIssue' => $this->descriptionOfIssue,
                'reportOnly' => $this->getReportOnly()
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cardDoesNotBelongToCardholder)) {
            $json['cardDoesNotBelongToCardholder'] = $this->cardDoesNotBelongToCardholder;
        }
        if (isset($this->cardWasCounterfeited)) {
            $json['cardWasCounterfeited']          = $this->cardWasCounterfeited;
        }
        if (isset($this->descriptionOfIssue)) {
            $json['descriptionOfIssue']            = $this->descriptionOfIssue;
        }
        if (!empty($this->reportOnly)) {
            $json['reportOnly']                    = $this->reportOnly['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
