<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class PaymentAmountUpdateRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $adjustAuthType;

    /**
     * @var string|null
     */
    private $adjustAuthorisationData;

    /**
     * @var Amount29
     */
    private $amount;

    /**
     * @var ApplicationInfo|null
     */
    private $applicationInfo;

    /**
     * @var string|null
     */
    private $industryUsage;

    /**
     * @var LineItem[]|null
     */
    private $lineItems;

    /**
     * @var string
     */
    private $merchantAccount;

    /**
     * @var ThreeDSecureData3|null
     */
    private $mpiData;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var Split[]|null
     */
    private $splits;

    /**
     * @param Amount29 $amount
     * @param string $merchantAccount
     */
    public function __construct(Amount29 $amount, string $merchantAccount)
    {
        $this->amount = $amount;
        $this->merchantAccount = $merchantAccount;
    }

    /**
     * Returns Adjust Auth Type.
     * The type of adjustment. Possible values:
     *
     * * **cardholderInitiatedTransaction**
     *
     * * **merchantInitiatedTransaction**
     */
    public function getAdjustAuthType(): ?string
    {
        return $this->adjustAuthType;
    }

    /**
     * Sets Adjust Auth Type.
     * The type of adjustment. Possible values:
     *
     * * **cardholderInitiatedTransaction**
     *
     * * **merchantInitiatedTransaction**
     *
     * @maps adjustAuthType
     * @factory \AdyenLib\Models\AdjustAuthTypeEnum::checkValue
     */
    public function setAdjustAuthType(?string $adjustAuthType): void
    {
        $this->adjustAuthType = $adjustAuthType;
    }

    /**
     * Returns Adjust Authorisation Data.
     * The required data to make a [synchronous authorization adjustment](https://docs.adyen.com/online-
     * payments/adjust-authorisation). Pass the corresponding value from the `/payments` response or
     * webhook message.
     */
    public function getAdjustAuthorisationData(): ?string
    {
        return $this->adjustAuthorisationData;
    }

    /**
     * Sets Adjust Authorisation Data.
     * The required data to make a [synchronous authorization adjustment](https://docs.adyen.com/online-
     * payments/adjust-authorisation). Pass the corresponding value from the `/payments` response or
     * webhook message.
     *
     * @maps adjustAuthorisationData
     */
    public function setAdjustAuthorisationData(?string $adjustAuthorisationData): void
    {
        $this->adjustAuthorisationData = $adjustAuthorisationData;
    }

    /**
     * Returns Amount.
     * The updated amount. The `currency` must match the currency used in authorisation.
     */
    public function getAmount(): Amount29
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * The updated amount. The `currency` must match the currency used in authorisation.
     *
     * @required
     * @maps amount
     */
    public function setAmount(Amount29 $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Application Info.
     * Information about your application. For more details, see [Building Adyen solutions](https://docs.
     * adyen.com/development-resources/building-adyen-solutions).
     */
    public function getApplicationInfo(): ?ApplicationInfo
    {
        return $this->applicationInfo;
    }

    /**
     * Sets Application Info.
     * Information about your application. For more details, see [Building Adyen solutions](https://docs.
     * adyen.com/development-resources/building-adyen-solutions).
     *
     * @maps applicationInfo
     */
    public function setApplicationInfo(?ApplicationInfo $applicationInfo): void
    {
        $this->applicationInfo = $applicationInfo;
    }

    /**
     * Returns Industry Usage.
     * The reason for the amount update. Possible values:
     * * **delayedCharge**
     * * **noShow**
     * * **installment**
     */
    public function getIndustryUsage(): ?string
    {
        return $this->industryUsage;
    }

    /**
     * Sets Industry Usage.
     * The reason for the amount update. Possible values:
     * * **delayedCharge**
     * * **noShow**
     * * **installment**
     *
     * @maps industryUsage
     * @factory \AdyenLib\Models\IndustryUsage1Enum::checkValue
     */
    public function setIndustryUsage(?string $industryUsage): void
    {
        $this->industryUsage = $industryUsage;
    }

    /**
     * Returns Line Items.
     * Price and product information of the refunded items, required for [partial refunds](https://docs.
     * adyen.com/online-payments/refund#refund-a-payment).
     * > This field is required for partial refunds with 3x 4x Oney, Affirm, Afterpay, Atome, Clearpay,
     * Klarna, Ratepay, Walley, and Zip.
     *
     * @return LineItem[]|null
     */
    public function getLineItems(): ?array
    {
        return $this->lineItems;
    }

    /**
     * Sets Line Items.
     * Price and product information of the refunded items, required for [partial refunds](https://docs.
     * adyen.com/online-payments/refund#refund-a-payment).
     * > This field is required for partial refunds with 3x 4x Oney, Affirm, Afterpay, Atome, Clearpay,
     * Klarna, Ratepay, Walley, and Zip.
     *
     * @maps lineItems
     *
     * @param LineItem[]|null $lineItems
     */
    public function setLineItems(?array $lineItems): void
    {
        $this->lineItems = $lineItems;
    }

    /**
     * Returns Merchant Account.
     * The merchant account that is used to process the payment.
     */
    public function getMerchantAccount(): string
    {
        return $this->merchantAccount;
    }

    /**
     * Sets Merchant Account.
     * The merchant account that is used to process the payment.
     *
     * @required
     * @maps merchantAccount
     */
    public function setMerchantAccount(string $merchantAccount): void
    {
        $this->merchantAccount = $merchantAccount;
    }

    /**
     * Returns Mpi Data.
     * Authentication data from a [merchant plug-in (MPI)](https://en.wikipedia.org/wiki/Merchant_plug-in)
     * like Mastercard SecureCode, Visa Secure, or Cartes Bancaires. Required for cardholder-initiated
     * transaction (CIT) adjustments.
     */
    public function getMpiData(): ?ThreeDSecureData3
    {
        return $this->mpiData;
    }

    /**
     * Sets Mpi Data.
     * Authentication data from a [merchant plug-in (MPI)](https://en.wikipedia.org/wiki/Merchant_plug-in)
     * like Mastercard SecureCode, Visa Secure, or Cartes Bancaires. Required for cardholder-initiated
     * transaction (CIT) adjustments.
     *
     * @maps mpiData
     */
    public function setMpiData(?ThreeDSecureData3 $mpiData): void
    {
        $this->mpiData = $mpiData;
    }

    /**
     * Returns Reference.
     * Your reference for the amount update request. Maximum length: 80 characters.
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * Your reference for the amount update request. Maximum length: 80 characters.
     *
     * @maps reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Splits.
     * An array of objects specifying how the amount should be split between accounts when using Adyen for
     * Platforms. For more information, see how to process payments for [marketplaces](https://docs.adyen.
     * com/marketplaces/process-payments) or [platforms](https://docs.adyen.com/platforms/process-payments).
     *
     * @return Split[]|null
     */
    public function getSplits(): ?array
    {
        return $this->splits;
    }

    /**
     * Sets Splits.
     * An array of objects specifying how the amount should be split between accounts when using Adyen for
     * Platforms. For more information, see how to process payments for [marketplaces](https://docs.adyen.
     * com/marketplaces/process-payments) or [platforms](https://docs.adyen.com/platforms/process-payments).
     *
     * @maps splits
     *
     * @param Split[]|null $splits
     */
    public function setSplits(?array $splits): void
    {
        $this->splits = $splits;
    }

    /**
     * Converts the PaymentAmountUpdateRequest object to a human-readable string representation.
     *
     * @return string The string representation of the PaymentAmountUpdateRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PaymentAmountUpdateRequest',
            [
                'adjustAuthType' => $this->adjustAuthType,
                'adjustAuthorisationData' => $this->adjustAuthorisationData,
                'amount' => $this->amount,
                'applicationInfo' => $this->applicationInfo,
                'industryUsage' => $this->industryUsage,
                'lineItems' => $this->lineItems,
                'merchantAccount' => $this->merchantAccount,
                'mpiData' => $this->mpiData,
                'reference' => $this->reference,
                'splits' => $this->splits
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->adjustAuthType)) {
            $json['adjustAuthType']          = AdjustAuthTypeEnum::checkValue($this->adjustAuthType);
        }
        if (isset($this->adjustAuthorisationData)) {
            $json['adjustAuthorisationData'] = $this->adjustAuthorisationData;
        }
        $json['amount']                      = $this->amount;
        if (isset($this->applicationInfo)) {
            $json['applicationInfo']         = $this->applicationInfo;
        }
        if (isset($this->industryUsage)) {
            $json['industryUsage']           = IndustryUsage1Enum::checkValue($this->industryUsage);
        }
        if (isset($this->lineItems)) {
            $json['lineItems']               = $this->lineItems;
        }
        $json['merchantAccount']             = $this->merchantAccount;
        if (isset($this->mpiData)) {
            $json['mpiData']                 = $this->mpiData;
        }
        if (isset($this->reference)) {
            $json['reference']               = $this->reference;
        }
        if (isset($this->splits)) {
            $json['splits']                  = $this->splits;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
