<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class PermitResult implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $resultKey;

    /**
     * @var string|null
     */
    private $token;

    /**
     * Returns Result Key.
     * The key to link permit requests to permit results.
     */
    public function getResultKey(): ?string
    {
        return $this->resultKey;
    }

    /**
     * Sets Result Key.
     * The key to link permit requests to permit results.
     *
     * @maps resultKey
     */
    public function setResultKey(?string $resultKey): void
    {
        $this->resultKey = $resultKey;
    }

    /**
     * Returns Token.
     * The permit token which is used to make payments by the partner company.
     */
    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
     * Sets Token.
     * The permit token which is used to make payments by the partner company.
     *
     * @maps token
     */
    public function setToken(?string $token): void
    {
        $this->token = $token;
    }

    /**
     * Converts the PermitResult object to a human-readable string representation.
     *
     * @return string The string representation of the PermitResult object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('PermitResult', ['resultKey' => $this->resultKey, 'token' => $this->token]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->resultKey)) {
            $json['resultKey'] = $this->resultKey;
        }
        if (isset($this->token)) {
            $json['token']     = $this->token;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
