<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class Policy implements \JsonSerializable
{
    /**
     * @var Resource2[]|null
     */
    private $resources;

    /**
     * @var string[]|null
     */
    private $roles;

    /**
     * Returns Resources.
     * An object containing the type and the unique identifier of the user of the component.
     *
     * For [Onboarding components](https://docs.adyen.com/platforms/onboard-users/components), this is the
     * ID of the legal entity that has a contractual relationship with your platform. For sole
     * proprietorships, use the ID of the legal entity of the individual owner.
     *
     * For [Platform Experience components](https://docs.adyen.com/platforms/build-user-dashboards), this
     * is the ID of the account holder that is associated with the balance account shown in the component.
     *
     * @return Resource2[]|null
     */
    public function getResources(): ?array
    {
        return $this->resources;
    }

    /**
     * Sets Resources.
     * An object containing the type and the unique identifier of the user of the component.
     *
     * For [Onboarding components](https://docs.adyen.com/platforms/onboard-users/components), this is the
     * ID of the legal entity that has a contractual relationship with your platform. For sole
     * proprietorships, use the ID of the legal entity of the individual owner.
     *
     * For [Platform Experience components](https://docs.adyen.com/platforms/build-user-dashboards), this
     * is the ID of the account holder that is associated with the balance account shown in the component.
     *
     * @maps resources
     *
     * @param Resource2[]|null $resources
     */
    public function setResources(?array $resources): void
    {
        $this->resources = $resources;
    }

    /**
     * Returns Roles.
     * The name of the role required to use the component.
     *
     * @return string[]|null
     */
    public function getRoles(): ?array
    {
        return $this->roles;
    }

    /**
     * Sets Roles.
     * The name of the role required to use the component.
     *
     * @maps roles
     *
     * @param string[]|null $roles
     */
    public function setRoles(?array $roles): void
    {
        $this->roles = $roles;
    }

    /**
     * Converts the Policy object to a human-readable string representation.
     *
     * @return string The string representation of the Policy object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Policy', ['resources' => $this->resources, 'roles' => $this->roles]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->resources)) {
            $json['resources'] = $this->resources;
        }
        if (isset($this->roles)) {
            $json['roles']     = $this->roles;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
