<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Indicates if the printer is working and usable.
 * Possible values:
 * * **OK**
 * * **PaperLow**
 * * **NoPaper**
 * * **PaperJam**
 * * **OutOfOrder**
 */
class PrinterStatusEnum
{
    public const OK = 'OK';

    public const PAPERLOW = 'PaperLow';

    public const NOPAPER = 'NoPaper';

    public const PAPERJAM = 'PaperJam';

    public const OUTOFORDER = 'OutOfOrder';

    private const _ALL_VALUES = [self::OK, self::PAPERLOW, self::NOPAPER, self::PAPERJAM, self::OUTOFORDER];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for PrinterStatusEnum.");
    }
}
