<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

/**
 * Metadata about the selected provider, including the name and company logo. You can use this
 * information to inform the user about the provider they will be redirected to when they select the
 * link.
 */
class Provider2 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $logoURL;

    /**
     * @var string
     */
    private $name;

    /**
     * @param string $logoURL
     * @param string $name
     */
    public function __construct(string $logoURL, string $name)
    {
        $this->logoURL = $logoURL;
        $this->name = $name;
    }

    /**
     * Returns Logo URL.
     * The URL of the organization's or brand's logo. This URL typically points to an image file (e.g., .
     * png, .jpg, .svg) that can be displayed to visually represent the entity.
     */
    public function getLogoURL(): string
    {
        return $this->logoURL;
    }

    /**
     * Sets Logo URL.
     * The URL of the organization's or brand's logo. This URL typically points to an image file (e.g., .
     * png, .jpg, .svg) that can be displayed to visually represent the entity.
     *
     * @required
     * @maps logoURL
     */
    public function setLogoURL(string $logoURL): void
    {
        $this->logoURL = $logoURL;
    }

    /**
     * Returns Name.
     * The official or commonly used name of the organization, brand, or entity.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The official or commonly used name of the organization, brand, or entity.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Converts the Provider2 object to a human-readable string representation.
     *
     * @return string The string representation of the Provider2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Provider2', ['logoURL' => $this->logoURL, 'name' => $this->name]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['logoURL'] = $this->logoURL;
        $json['name']    = $this->name;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
