<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class PulseResponseInfo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $processingType;

    /**
     * @var TransactionDescriptionResponseInfo1|null
     */
    private $transactionDescription;

    /**
     * Returns Processing Type.
     * The type of transactions processed over this payment method.
     * Allowed values:
     * - **pos** for in-person payments.
     * - **billpay** for subscription payments, both the initial payment and the later recurring payments.
     * These transactions have `recurringProcessingModel` **Subscription**.
     * - **ecom** for all other card not present transactions. This includes non-recurring transactions and
     * transactions with `recurringProcessingModel` **CardOnFile** or **UnscheduledCardOnFile**.
     */
    public function getProcessingType(): ?string
    {
        return $this->processingType;
    }

    /**
     * Sets Processing Type.
     * The type of transactions processed over this payment method.
     * Allowed values:
     * - **pos** for in-person payments.
     * - **billpay** for subscription payments, both the initial payment and the later recurring payments.
     * These transactions have `recurringProcessingModel` **Subscription**.
     * - **ecom** for all other card not present transactions. This includes non-recurring transactions and
     * transactions with `recurringProcessingModel` **CardOnFile** or **UnscheduledCardOnFile**.
     *
     * @maps processingType
     * @factory \AdyenLib\Models\ProcessingTypeEnum::checkValue
     */
    public function setProcessingType(?string $processingType): void
    {
        $this->processingType = $processingType;
    }

    /**
     * Returns Transaction Description.
     * Information regarding the transaction description.
     */
    public function getTransactionDescription(): ?TransactionDescriptionResponseInfo1
    {
        return $this->transactionDescription;
    }

    /**
     * Sets Transaction Description.
     * Information regarding the transaction description.
     *
     * @maps transactionDescription
     */
    public function setTransactionDescription(?TransactionDescriptionResponseInfo1 $transactionDescription): void
    {
        $this->transactionDescription = $transactionDescription;
    }

    /**
     * Converts the PulseResponseInfo object to a human-readable string representation.
     *
     * @return string The string representation of the PulseResponseInfo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PulseResponseInfo',
            ['processingType' => $this->processingType, 'transactionDescription' => $this->transactionDescription]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->processingType)) {
            $json['processingType']         = ProcessingTypeEnum::checkValue($this->processingType);
        }
        if (isset($this->transactionDescription)) {
            $json['transactionDescription'] = $this->transactionDescription;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
