<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

/**
 * Content of the Reconciliation Response message.
 */
class ReconciliationResponse2 implements \JsonSerializable
{
    /**
     * @var Response11
     */
    private $response;

    /**
     * @var string
     */
    private $reconciliationType;

    /**
     * @var int|null
     */
    private $pOIReconciliationID;

    /**
     * @var TransactionTotals[]|null
     */
    private $transactionTotals;

    /**
     * @param Response11 $response
     * @param string $reconciliationType
     */
    public function __construct(Response11 $response, string $reconciliationType)
    {
        $this->response = $response;
        $this->reconciliationType = $reconciliationType;
    }

    /**
     * Returns Response.
     * Result of a message request processing.
     */
    public function getResponse(): Response11
    {
        return $this->response;
    }

    /**
     * Sets Response.
     * Result of a message request processing.
     *
     * @required
     * @maps Response
     */
    public function setResponse(Response11 $response): void
    {
        $this->response = $response;
    }

    /**
     * Returns Reconciliation Type.
     * Type of Reconciliation requested by the Sale to the POI.
     * Possible values:
     * * **AcquirerReconciliation**
     * * **AcquirerSynchronisation**
     * * **PreviousReconciliation**
     * * **SaleReconciliation**
     */
    public function getReconciliationType(): string
    {
        return $this->reconciliationType;
    }

    /**
     * Sets Reconciliation Type.
     * Type of Reconciliation requested by the Sale to the POI.
     * Possible values:
     * * **AcquirerReconciliation**
     * * **AcquirerSynchronisation**
     * * **PreviousReconciliation**
     * * **SaleReconciliation**
     *
     * @required
     * @maps ReconciliationType
     * @factory \AdyenLib\Models\ReconciliationType1Enum::checkValue
     */
    public function setReconciliationType(string $reconciliationType): void
    {
        $this->reconciliationType = $reconciliationType;
    }

    /**
     * Returns P OI Reconciliation ID.
     * Identification of the reconciliation period between Sale and POI.
     * Absent if ReconciliationType is `AcquirerReconciliation`.
     */
    public function getPOIReconciliationID(): ?int
    {
        return $this->pOIReconciliationID;
    }

    /**
     * Sets P OI Reconciliation ID.
     * Identification of the reconciliation period between Sale and POI.
     * Absent if ReconciliationType is `AcquirerReconciliation`.
     *
     * @maps POIReconciliationID
     */
    public function setPOIReconciliationID(?int $pOIReconciliationID): void
    {
        $this->pOIReconciliationID = $pOIReconciliationID;
    }

    /**
     * Returns Transaction Totals.
     * Result of the Sale to POI Reconciliation processing.
     * If `Response.Result` is Success.
     *
     * @return TransactionTotals[]|null
     */
    public function getTransactionTotals(): ?array
    {
        return $this->transactionTotals;
    }

    /**
     * Sets Transaction Totals.
     * Result of the Sale to POI Reconciliation processing.
     * If `Response.Result` is Success.
     *
     * @maps TransactionTotals
     *
     * @param TransactionTotals[]|null $transactionTotals
     */
    public function setTransactionTotals(?array $transactionTotals): void
    {
        $this->transactionTotals = $transactionTotals;
    }

    /**
     * Converts the ReconciliationResponse2 object to a human-readable string representation.
     *
     * @return string The string representation of the ReconciliationResponse2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ReconciliationResponse2',
            [
                'response' => $this->response,
                'reconciliationType' => $this->reconciliationType,
                'pOIReconciliationID' => $this->pOIReconciliationID,
                'transactionTotals' => $this->transactionTotals
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Response']                = $this->response;
        $json['ReconciliationType']      = ReconciliationType1Enum::checkValue($this->reconciliationType);
        if (isset($this->pOIReconciliationID)) {
            $json['POIReconciliationID'] = $this->pOIReconciliationID;
        }
        if (isset($this->transactionTotals)) {
            $json['TransactionTotals']   = $this->transactionTotals;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
