<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class RegisterSCARequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string
     */
    private $paymentInstrumentId;

    /**
     * @var DelegatedAuthenticationData1
     */
    private $strongCustomerAuthentication;

    /**
     * @param string $paymentInstrumentId
     * @param DelegatedAuthenticationData1 $strongCustomerAuthentication
     */
    public function __construct(
        string $paymentInstrumentId,
        DelegatedAuthenticationData1 $strongCustomerAuthentication
    ) {
        $this->paymentInstrumentId = $paymentInstrumentId;
        $this->strongCustomerAuthentication = $strongCustomerAuthentication;
    }

    /**
     * Returns Name.
     * The name of the SCA device that you are registering. You can use it to help your users identify the
     * device.
     *
     * If you do not specify a `name`, Adyen automatically generates one.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of the SCA device that you are registering. You can use it to help your users identify the
     * device.
     *
     * If you do not specify a `name`, Adyen automatically generates one.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Payment Instrument Id.
     * The unique identifier of the payment instrument for which you are registering the SCA device.
     */
    public function getPaymentInstrumentId(): string
    {
        return $this->paymentInstrumentId;
    }

    /**
     * Sets Payment Instrument Id.
     * The unique identifier of the payment instrument for which you are registering the SCA device.
     *
     * @required
     * @maps paymentInstrumentId
     */
    public function setPaymentInstrumentId(string $paymentInstrumentId): void
    {
        $this->paymentInstrumentId = $paymentInstrumentId;
    }

    /**
     * Returns Strong Customer Authentication.
     * Contains information required to register the SCA device.
     */
    public function getStrongCustomerAuthentication(): DelegatedAuthenticationData1
    {
        return $this->strongCustomerAuthentication;
    }

    /**
     * Sets Strong Customer Authentication.
     * Contains information required to register the SCA device.
     *
     * @required
     * @maps strongCustomerAuthentication
     */
    public function setStrongCustomerAuthentication(DelegatedAuthenticationData1 $strongCustomerAuthentication): void
    {
        $this->strongCustomerAuthentication = $strongCustomerAuthentication;
    }

    /**
     * Converts the RegisterSCARequest object to a human-readable string representation.
     *
     * @return string The string representation of the RegisterSCARequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RegisterSCARequest',
            [
                'name' => $this->name,
                'paymentInstrumentId' => $this->paymentInstrumentId,
                'strongCustomerAuthentication' => $this->strongCustomerAuthentication
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['name']                     = $this->name;
        }
        $json['paymentInstrumentId']          = $this->paymentInstrumentId;
        $json['strongCustomerAuthentication'] = $this->strongCustomerAuthentication;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
