<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class RevealPinResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $encryptedPinBlock;

    /**
     * @var string
     */
    private $token;

    /**
     * @param string $encryptedPinBlock
     * @param string $token
     */
    public function __construct(string $encryptedPinBlock, string $token)
    {
        $this->encryptedPinBlock = $encryptedPinBlock;
        $this->token = $token;
    }

    /**
     * Returns Encrypted Pin Block.
     * The encrypted [PIN block](https://www.pcisecuritystandards.org/glossary/pin-block).
     */
    public function getEncryptedPinBlock(): string
    {
        return $this->encryptedPinBlock;
    }

    /**
     * Sets Encrypted Pin Block.
     * The encrypted [PIN block](https://www.pcisecuritystandards.org/glossary/pin-block).
     *
     * @required
     * @maps encryptedPinBlock
     */
    public function setEncryptedPinBlock(string $encryptedPinBlock): void
    {
        $this->encryptedPinBlock = $encryptedPinBlock;
    }

    /**
     * Returns Token.
     * The 16-digit token that you need to extract the `encryptedPinBlock`.
     */
    public function getToken(): string
    {
        return $this->token;
    }

    /**
     * Sets Token.
     * The 16-digit token that you need to extract the `encryptedPinBlock`.
     *
     * @required
     * @maps token
     */
    public function setToken(string $token): void
    {
        $this->token = $token;
    }

    /**
     * Converts the RevealPinResponse object to a human-readable string representation.
     *
     * @return string The string representation of the RevealPinResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RevealPinResponse',
            ['encryptedPinBlock' => $this->encryptedPinBlock, 'token' => $this->token]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['encryptedPinBlock'] = $this->encryptedPinBlock;
        $json['token']             = $this->token;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
