<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class SEPADirectDebit implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $checkoutAttemptId;

    /**
     * @var string|null
     */
    private $dueDate;

    /**
     * @var string
     */
    private $iban;

    /**
     * @var string
     */
    private $ownerName;

    /**
     * @var string|null
     */
    private $recurringDetailReference;

    /**
     * @var string|null
     */
    private $sdkData;

    /**
     * @var string|null
     */
    private $storedPaymentMethodId;

    /**
     * @var string|null
     */
    private $transferInstrumentId;

    /**
     * @var string|null
     */
    private $type = Type51Enum::SEPADIRECTDEBIT;

    /**
     * @param string $iban
     * @param string $ownerName
     */
    public function __construct(string $iban, string $ownerName)
    {
        $this->iban = $iban;
        $this->ownerName = $ownerName;
    }

    /**
     * Returns Checkout Attempt Id.
     * The checkout attempt identifier.
     */
    public function getCheckoutAttemptId(): ?string
    {
        return $this->checkoutAttemptId;
    }

    /**
     * Sets Checkout Attempt Id.
     * The checkout attempt identifier.
     *
     * @maps checkoutAttemptId
     */
    public function setCheckoutAttemptId(?string $checkoutAttemptId): void
    {
        $this->checkoutAttemptId = $checkoutAttemptId;
    }

    /**
     * Returns Due Date.
     * The date that the the shopper's bank account is charged.
     */
    public function getDueDate(): ?string
    {
        return $this->dueDate;
    }

    /**
     * Sets Due Date.
     * The date that the the shopper's bank account is charged.
     *
     * @maps dueDate
     */
    public function setDueDate(?string $dueDate): void
    {
        $this->dueDate = $dueDate;
    }

    /**
     * Returns Iban.
     * The International Bank Account Number (IBAN).
     */
    public function getIban(): string
    {
        return $this->iban;
    }

    /**
     * Sets Iban.
     * The International Bank Account Number (IBAN).
     *
     * @required
     * @maps iban
     */
    public function setIban(string $iban): void
    {
        $this->iban = $iban;
    }

    /**
     * Returns Owner Name.
     * The name of the bank account holder.
     */
    public function getOwnerName(): string
    {
        return $this->ownerName;
    }

    /**
     * Sets Owner Name.
     * The name of the bank account holder.
     *
     * @required
     * @maps ownerName
     */
    public function setOwnerName(string $ownerName): void
    {
        $this->ownerName = $ownerName;
    }

    /**
     * Returns Recurring Detail Reference.
     * This is the `recurringDetailReference` returned in the response when you created the token.
     */
    public function getRecurringDetailReference(): ?string
    {
        return $this->recurringDetailReference;
    }

    /**
     * Sets Recurring Detail Reference.
     * This is the `recurringDetailReference` returned in the response when you created the token.
     *
     * @maps recurringDetailReference
     */
    public function setRecurringDetailReference(?string $recurringDetailReference): void
    {
        $this->recurringDetailReference = $recurringDetailReference;
    }

    /**
     * Returns Sdk Data.
     * Base64-encoded JSON object containing SDK related parameters required by the SDK
     */
    public function getSdkData(): ?string
    {
        return $this->sdkData;
    }

    /**
     * Sets Sdk Data.
     * Base64-encoded JSON object containing SDK related parameters required by the SDK
     *
     * @maps sdkData
     */
    public function setSdkData(?string $sdkData): void
    {
        $this->sdkData = $sdkData;
    }

    /**
     * Returns Stored Payment Method Id.
     * This is the `recurringDetailReference` returned in the response when you created the token.
     */
    public function getStoredPaymentMethodId(): ?string
    {
        return $this->storedPaymentMethodId;
    }

    /**
     * Sets Stored Payment Method Id.
     * This is the `recurringDetailReference` returned in the response when you created the token.
     *
     * @maps storedPaymentMethodId
     */
    public function setStoredPaymentMethodId(?string $storedPaymentMethodId): void
    {
        $this->storedPaymentMethodId = $storedPaymentMethodId;
    }

    /**
     * Returns Transfer Instrument Id.
     * The unique identifier of your user's verified transfer instrument, which you can use to top up their
     * balance accounts.
     */
    public function getTransferInstrumentId(): ?string
    {
        return $this->transferInstrumentId;
    }

    /**
     * Sets Transfer Instrument Id.
     * The unique identifier of your user's verified transfer instrument, which you can use to top up their
     * balance accounts.
     *
     * @maps transferInstrumentId
     */
    public function setTransferInstrumentId(?string $transferInstrumentId): void
    {
        $this->transferInstrumentId = $transferInstrumentId;
    }

    /**
     * Returns Type.
     * **sepadirectdebit**
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * **sepadirectdebit**
     *
     * @maps type
     * @factory \AdyenLib\Models\Type51Enum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the SEPADirectDebit object to a human-readable string representation.
     *
     * @return string The string representation of the SEPADirectDebit object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SEPADirectDebit',
            [
                'checkoutAttemptId' => $this->checkoutAttemptId,
                'dueDate' => $this->dueDate,
                'iban' => $this->iban,
                'ownerName' => $this->ownerName,
                'recurringDetailReference' => $this->recurringDetailReference,
                'sdkData' => $this->sdkData,
                'storedPaymentMethodId' => $this->storedPaymentMethodId,
                'transferInstrumentId' => $this->transferInstrumentId,
                'type' => $this->type
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->checkoutAttemptId)) {
            $json['checkoutAttemptId']        = $this->checkoutAttemptId;
        }
        if (isset($this->dueDate)) {
            $json['dueDate']                  = $this->dueDate;
        }
        $json['iban']                         = $this->iban;
        $json['ownerName']                    = $this->ownerName;
        if (isset($this->recurringDetailReference)) {
            $json['recurringDetailReference'] = $this->recurringDetailReference;
        }
        if (isset($this->sdkData)) {
            $json['sdkData']                  = $this->sdkData;
        }
        if (isset($this->storedPaymentMethodId)) {
            $json['storedPaymentMethodId']    = $this->storedPaymentMethodId;
        }
        if (isset($this->transferInstrumentId)) {
            $json['transferInstrumentId']     = $this->transferInstrumentId;
        }
        if (isset($this->type)) {
            $json['type']                     = Type51Enum::checkValue($this->type);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
