<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class SofortResponseInfo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $currencyCode;

    /**
     * @var string|null
     */
    private $logo;

    /**
     * Returns Currency Code.
     * Sofort currency code. For example, **EUR**.
     */
    public function getCurrencyCode(): ?string
    {
        return $this->currencyCode;
    }

    /**
     * Sets Currency Code.
     * Sofort currency code. For example, **EUR**.
     *
     * @maps currencyCode
     */
    public function setCurrencyCode(?string $currencyCode): void
    {
        $this->currencyCode = $currencyCode;
    }

    /**
     * Returns Logo.
     * Sofort logo. Format: Base64-encoded string.
     */
    public function getLogo(): ?string
    {
        return $this->logo;
    }

    /**
     * Sets Logo.
     * Sofort logo. Format: Base64-encoded string.
     *
     * @maps logo
     */
    public function setLogo(?string $logo): void
    {
        $this->logo = $logo;
    }

    /**
     * Converts the SofortResponseInfo object to a human-readable string representation.
     *
     * @return string The string representation of the SofortResponseInfo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SofortResponseInfo',
            ['currencyCode' => $this->currencyCode, 'logo' => $this->logo]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->currencyCode)) {
            $json['currencyCode'] = $this->currencyCode;
        }
        if (isset($this->logo)) {
            $json['logo']         = $this->logo;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
