<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The status you want to change to, The status of the sweep. If not provided, by default, this is set
 * to **active**.
 *
 * Possible values:
 *
 * * **active**:  the sweep is enabled and funds will be pulled in or pushed out based on the defined
 * configuration.
 *
 * * **inactive**: the sweep is disabled and cannot be triggered., The status of the transaction rule.
 * If you provide a `startDate` in the request, the rule is automatically created
 * with an **active** status.
 *
 * Possible values: **active**, **inactive**., The status of the webhook setting. Possible values:
 *
 * * **active**: You receive a balance webhook if any of the conditions in this setting are met.
 * * **inactive**: You do not receive a balance webhook even if the conditions in this settings are met.
 * , The status of the recurring top-up. If not provided, by default, this is set to **active**.
 *
 * Possible values:
 *
 * * **active**:  the top up is enabled and funds will be pulled in.
 *
 * * **inactive**: the top up is disabled and cannot be triggered.
 */
class Status6Enum
{
    public const ACTIVE = 'active';

    public const INACTIVE = 'inactive';

    private const _ALL_VALUES = [self::ACTIVE, self::INACTIVE];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Status6Enum.");
    }
}
