<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class SubjectErasureByPspReferenceRequest implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $forceErasure;

    /**
     * @var string|null
     */
    private $merchantAccount;

    /**
     * @var string|null
     */
    private $pspReference;

    /**
     * Returns Force Erasure.
     * Set this to **true** if you want to delete shopper-related data, even if the shopper has an existing
     * recurring transaction. This only deletes the shopper-related data for the specific payment, but does
     * not cancel the existing recurring transaction.
     */
    public function getForceErasure(): ?bool
    {
        return $this->forceErasure;
    }

    /**
     * Sets Force Erasure.
     * Set this to **true** if you want to delete shopper-related data, even if the shopper has an existing
     * recurring transaction. This only deletes the shopper-related data for the specific payment, but does
     * not cancel the existing recurring transaction.
     *
     * @maps forceErasure
     */
    public function setForceErasure(?bool $forceErasure): void
    {
        $this->forceErasure = $forceErasure;
    }

    /**
     * Returns Merchant Account.
     * Your merchant account
     */
    public function getMerchantAccount(): ?string
    {
        return $this->merchantAccount;
    }

    /**
     * Sets Merchant Account.
     * Your merchant account
     *
     * @maps merchantAccount
     */
    public function setMerchantAccount(?string $merchantAccount): void
    {
        $this->merchantAccount = $merchantAccount;
    }

    /**
     * Returns Psp Reference.
     * The PSP reference of the payment. We will delete all shopper-related data for this payment.
     */
    public function getPspReference(): ?string
    {
        return $this->pspReference;
    }

    /**
     * Sets Psp Reference.
     * The PSP reference of the payment. We will delete all shopper-related data for this payment.
     *
     * @maps pspReference
     */
    public function setPspReference(?string $pspReference): void
    {
        $this->pspReference = $pspReference;
    }

    /**
     * Converts the SubjectErasureByPspReferenceRequest object to a human-readable string representation.
     *
     * @return string The string representation of the SubjectErasureByPspReferenceRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SubjectErasureByPspReferenceRequest',
            [
                'forceErasure' => $this->forceErasure,
                'merchantAccount' => $this->merchantAccount,
                'pspReference' => $this->pspReference
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->forceErasure)) {
            $json['forceErasure']    = $this->forceErasure;
        }
        if (isset($this->merchantAccount)) {
            $json['merchantAccount'] = $this->merchantAccount;
        }
        if (isset($this->pspReference)) {
            $json['pspReference']    = $this->pspReference;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
