<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use AdyenLib\Utils\DateTimeHelper;
use stdClass;

class SubmitRequest implements \JsonSerializable
{
    /**
     * @var array<string,string>|null
     */
    private $additionalData;

    /**
     * @var Amount
     */
    private $amount;

    /**
     * @var \DateTime|null
     */
    private $dateOfBirth;

    /**
     * @var string|null
     */
    private $entityType;

    /**
     * @var int|null
     */
    private $fraudOffset;

    /**
     * @var string
     */
    private $merchantAccount;

    /**
     * @var string|null
     */
    private $nationality;

    /**
     * @var Recurring
     */
    private $recurring;

    /**
     * @var string
     */
    private $reference;

    /**
     * @var string
     */
    private $selectedRecurringDetailReference;

    /**
     * @var string
     */
    private $shopperEmail;

    /**
     * @var Name|null
     */
    private $shopperName;

    /**
     * @var string
     */
    private $shopperReference;

    /**
     * @var string|null
     */
    private $shopperStatement;

    /**
     * @var string|null
     */
    private $socialSecurityNumber;

    /**
     * @param Amount $amount
     * @param string $merchantAccount
     * @param Recurring $recurring
     * @param string $reference
     * @param string $selectedRecurringDetailReference
     * @param string $shopperEmail
     * @param string $shopperReference
     */
    public function __construct(
        Amount $amount,
        string $merchantAccount,
        Recurring $recurring,
        string $reference,
        string $selectedRecurringDetailReference,
        string $shopperEmail,
        string $shopperReference
    ) {
        $this->amount = $amount;
        $this->merchantAccount = $merchantAccount;
        $this->recurring = $recurring;
        $this->reference = $reference;
        $this->selectedRecurringDetailReference = $selectedRecurringDetailReference;
        $this->shopperEmail = $shopperEmail;
        $this->shopperReference = $shopperReference;
    }

    /**
     * Returns Additional Data.
     * This field contains additional data, which may be required for a particular request.
     *
     * @return array<string,string>|null
     */
    public function getAdditionalData(): ?array
    {
        return $this->additionalData;
    }

    /**
     * Sets Additional Data.
     * This field contains additional data, which may be required for a particular request.
     *
     * @maps additionalData
     *
     * @param array<string,string>|null $additionalData
     */
    public function setAdditionalData(?array $additionalData): void
    {
        $this->additionalData = $additionalData;
    }

    /**
     * Returns Amount.
     * A container object for the payable amount information of the transaction.
     */
    public function getAmount(): Amount
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * A container object for the payable amount information of the transaction.
     *
     * @required
     * @maps amount
     */
    public function setAmount(Amount $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Date of Birth.
     * The date of birth.
     * Format: ISO-8601; example: YYYY-MM-DD
     *
     * For Paysafecard it must be the same as used when registering the Paysafecard account.
     *
     * > This field is mandatory for natural persons.
     * > This field is required to update the existing `dateOfBirth` that is associated with this recurring
     * contract.
     */
    public function getDateOfBirth(): ?\DateTime
    {
        return $this->dateOfBirth;
    }

    /**
     * Sets Date of Birth.
     * The date of birth.
     * Format: ISO-8601; example: YYYY-MM-DD
     *
     * For Paysafecard it must be the same as used when registering the Paysafecard account.
     *
     * > This field is mandatory for natural persons.
     * > This field is required to update the existing `dateOfBirth` that is associated with this recurring
     * contract.
     *
     * @maps dateOfBirth
     * @factory \AdyenLib\Utils\DateTimeHelper::fromSimpleDate
     */
    public function setDateOfBirth(?\DateTime $dateOfBirth): void
    {
        $this->dateOfBirth = $dateOfBirth;
    }

    /**
     * Returns Entity Type.
     * The type of the entity the payout is processed for.
     *
     * Allowed values:
     * * NaturalPerson
     * * Company
     * > This field is required to update the existing `entityType` that is associated with this recurring
     * contract.
     */
    public function getEntityType(): ?string
    {
        return $this->entityType;
    }

    /**
     * Sets Entity Type.
     * The type of the entity the payout is processed for.
     *
     * Allowed values:
     * * NaturalPerson
     * * Company
     * > This field is required to update the existing `entityType` that is associated with this recurring
     * contract.
     *
     * @maps entityType
     * @factory \AdyenLib\Models\EntityType2Enum::checkValue
     */
    public function setEntityType(?string $entityType): void
    {
        $this->entityType = $entityType;
    }

    /**
     * Returns Fraud Offset.
     * An integer value that is added to the normal fraud score. The value can be either positive or
     * negative.
     */
    public function getFraudOffset(): ?int
    {
        return $this->fraudOffset;
    }

    /**
     * Sets Fraud Offset.
     * An integer value that is added to the normal fraud score. The value can be either positive or
     * negative.
     *
     * @maps fraudOffset
     */
    public function setFraudOffset(?int $fraudOffset): void
    {
        $this->fraudOffset = $fraudOffset;
    }

    /**
     * Returns Merchant Account.
     * The merchant account identifier you want to process the transaction request with.
     */
    public function getMerchantAccount(): string
    {
        return $this->merchantAccount;
    }

    /**
     * Sets Merchant Account.
     * The merchant account identifier you want to process the transaction request with.
     *
     * @required
     * @maps merchantAccount
     */
    public function setMerchantAccount(string $merchantAccount): void
    {
        $this->merchantAccount = $merchantAccount;
    }

    /**
     * Returns Nationality.
     * The shopper's nationality.
     *
     * A valid value is an ISO 2-character country code (e.g. 'NL').
     *
     * > This field is required to update the existing nationality that is associated with this recurring
     * contract.
     */
    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    /**
     * Sets Nationality.
     * The shopper's nationality.
     *
     * A valid value is an ISO 2-character country code (e.g. 'NL').
     *
     * > This field is required to update the existing nationality that is associated with this recurring
     * contract.
     *
     * @maps nationality
     */
    public function setNationality(?string $nationality): void
    {
        $this->nationality = $nationality;
    }

    /**
     * Returns Recurring.
     * A container for the type of recurring contract to be retrieved.
     *
     * The `recurring.contract` must be set to "PAYOUT".
     */
    public function getRecurring(): Recurring
    {
        return $this->recurring;
    }

    /**
     * Sets Recurring.
     * A container for the type of recurring contract to be retrieved.
     *
     * The `recurring.contract` must be set to "PAYOUT".
     *
     * @required
     * @maps recurring
     */
    public function setRecurring(Recurring $recurring): void
    {
        $this->recurring = $recurring;
    }

    /**
     * Returns Reference.
     * The merchant reference for this payout. This reference will be used in all communication to the
     * merchant about the status of the payout. Although it is a good idea to make sure it is unique, this
     * is not a requirement.
     */
    public function getReference(): string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * The merchant reference for this payout. This reference will be used in all communication to the
     * merchant about the status of the payout. Although it is a good idea to make sure it is unique, this
     * is not a requirement.
     *
     * @required
     * @maps reference
     */
    public function setReference(string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Selected Recurring Detail Reference.
     * This is the `recurringDetailReference` you want to use for this payout.
     *
     * You can use the value LATEST to select the most recently used recurring detail.
     */
    public function getSelectedRecurringDetailReference(): string
    {
        return $this->selectedRecurringDetailReference;
    }

    /**
     * Sets Selected Recurring Detail Reference.
     * This is the `recurringDetailReference` you want to use for this payout.
     *
     * You can use the value LATEST to select the most recently used recurring detail.
     *
     * @required
     * @maps selectedRecurringDetailReference
     */
    public function setSelectedRecurringDetailReference(string $selectedRecurringDetailReference): void
    {
        $this->selectedRecurringDetailReference = $selectedRecurringDetailReference;
    }

    /**
     * Returns Shopper Email.
     * The shopper's email address.
     */
    public function getShopperEmail(): string
    {
        return $this->shopperEmail;
    }

    /**
     * Sets Shopper Email.
     * The shopper's email address.
     *
     * @required
     * @maps shopperEmail
     */
    public function setShopperEmail(string $shopperEmail): void
    {
        $this->shopperEmail = $shopperEmail;
    }

    /**
     * Returns Shopper Name.
     * The shopper's name.
     *
     * In case the `entityType` is `Company`, the `shopperName.lastName` must contain the company name.
     *
     * > This field is required to update the existing `shopperName` associated with a recurring contract.
     */
    public function getShopperName(): ?Name
    {
        return $this->shopperName;
    }

    /**
     * Sets Shopper Name.
     * The shopper's name.
     *
     * In case the `entityType` is `Company`, the `shopperName.lastName` must contain the company name.
     *
     * > This field is required to update the existing `shopperName` associated with a recurring contract.
     *
     * @maps shopperName
     */
    public function setShopperName(?Name $shopperName): void
    {
        $this->shopperName = $shopperName;
    }

    /**
     * Returns Shopper Reference.
     * The shopper's reference for the payout transaction.
     */
    public function getShopperReference(): string
    {
        return $this->shopperReference;
    }

    /**
     * Sets Shopper Reference.
     * The shopper's reference for the payout transaction.
     *
     * @required
     * @maps shopperReference
     */
    public function setShopperReference(string $shopperReference): void
    {
        $this->shopperReference = $shopperReference;
    }

    /**
     * Returns Shopper Statement.
     * The description of this payout. This description is shown on the bank statement of the shopper (if
     * this is supported by the chosen payment method).
     */
    public function getShopperStatement(): ?string
    {
        return $this->shopperStatement;
    }

    /**
     * Sets Shopper Statement.
     * The description of this payout. This description is shown on the bank statement of the shopper (if
     * this is supported by the chosen payment method).
     *
     * @maps shopperStatement
     */
    public function setShopperStatement(?string $shopperStatement): void
    {
        $this->shopperStatement = $shopperStatement;
    }

    /**
     * Returns Social Security Number.
     * The shopper's social security number.
     */
    public function getSocialSecurityNumber(): ?string
    {
        return $this->socialSecurityNumber;
    }

    /**
     * Sets Social Security Number.
     * The shopper's social security number.
     *
     * @maps socialSecurityNumber
     */
    public function setSocialSecurityNumber(?string $socialSecurityNumber): void
    {
        $this->socialSecurityNumber = $socialSecurityNumber;
    }

    /**
     * Converts the SubmitRequest object to a human-readable string representation.
     *
     * @return string The string representation of the SubmitRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SubmitRequest',
            [
                'additionalData' => $this->additionalData,
                'amount' => $this->amount,
                'dateOfBirth' => $this->dateOfBirth,
                'entityType' => $this->entityType,
                'fraudOffset' => $this->fraudOffset,
                'merchantAccount' => $this->merchantAccount,
                'nationality' => $this->nationality,
                'recurring' => $this->recurring,
                'reference' => $this->reference,
                'selectedRecurringDetailReference' => $this->selectedRecurringDetailReference,
                'shopperEmail' => $this->shopperEmail,
                'shopperName' => $this->shopperName,
                'shopperReference' => $this->shopperReference,
                'shopperStatement' => $this->shopperStatement,
                'socialSecurityNumber' => $this->socialSecurityNumber
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->additionalData)) {
            $json['additionalData']               = $this->additionalData;
        }
        $json['amount']                           = $this->amount;
        if (isset($this->dateOfBirth)) {
            $json['dateOfBirth']                  = DateTimeHelper::toSimpleDate($this->dateOfBirth);
        }
        if (isset($this->entityType)) {
            $json['entityType']                   = EntityType2Enum::checkValue($this->entityType);
        }
        if (isset($this->fraudOffset)) {
            $json['fraudOffset']                  = $this->fraudOffset;
        }
        $json['merchantAccount']                  = $this->merchantAccount;
        if (isset($this->nationality)) {
            $json['nationality']                  = $this->nationality;
        }
        $json['recurring']                        = $this->recurring;
        $json['reference']                        = $this->reference;
        $json['selectedRecurringDetailReference'] = $this->selectedRecurringDetailReference;
        $json['shopperEmail']                     = $this->shopperEmail;
        if (isset($this->shopperName)) {
            $json['shopperName']                  = $this->shopperName;
        }
        $json['shopperReference']                 = $this->shopperReference;
        if (isset($this->shopperStatement)) {
            $json['shopperStatement']             = $this->shopperStatement;
        }
        if (isset($this->socialSecurityNumber)) {
            $json['socialSecurityNumber']         = $this->socialSecurityNumber;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
