<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class TransactionEventViolation implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $reason;

    /**
     * @var TransactionRuleReference2|null
     */
    private $transactionRule;

    /**
     * @var TransactionRuleSource2|null
     */
    private $transactionRuleSource;

    /**
     * Returns Reason.
     * An explanation about why the transaction rule failed.
     */
    public function getReason(): ?string
    {
        return $this->reason;
    }

    /**
     * Sets Reason.
     * An explanation about why the transaction rule failed.
     *
     * @maps reason
     */
    public function setReason(?string $reason): void
    {
        $this->reason = $reason;
    }

    /**
     * Returns Transaction Rule.
     * Contains information about the transaction rule.
     */
    public function getTransactionRule(): ?TransactionRuleReference2
    {
        return $this->transactionRule;
    }

    /**
     * Sets Transaction Rule.
     * Contains information about the transaction rule.
     *
     * @maps transactionRule
     */
    public function setTransactionRule(?TransactionRuleReference2 $transactionRule): void
    {
        $this->transactionRule = $transactionRule;
    }

    /**
     * Returns Transaction Rule Source.
     * Contains information about the resource to which the transaction rule applies.
     */
    public function getTransactionRuleSource(): ?TransactionRuleSource2
    {
        return $this->transactionRuleSource;
    }

    /**
     * Sets Transaction Rule Source.
     * Contains information about the resource to which the transaction rule applies.
     *
     * @maps transactionRuleSource
     */
    public function setTransactionRuleSource(?TransactionRuleSource2 $transactionRuleSource): void
    {
        $this->transactionRuleSource = $transactionRuleSource;
    }

    /**
     * Converts the TransactionEventViolation object to a human-readable string representation.
     *
     * @return string The string representation of the TransactionEventViolation object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TransactionEventViolation',
            [
                'reason' => $this->reason,
                'transactionRule' => $this->transactionRule,
                'transactionRuleSource' => $this->transactionRuleSource
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->reason)) {
            $json['reason']                = $this->reason;
        }
        if (isset($this->transactionRule)) {
            $json['transactionRule']       = $this->transactionRule;
        }
        if (isset($this->transactionRuleSource)) {
            $json['transactionRuleSource'] = $this->transactionRuleSource;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
