<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class TransactionRuleInfo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $aggregationLevel;

    /**
     * @var string
     */
    private $description;

    /**
     * @var string|null
     */
    private $endDate;

    /**
     * @var TransactionRuleEntityKey2
     */
    private $entityKey;

    /**
     * @var TransactionRuleInterval1
     */
    private $interval;

    /**
     * @var string|null
     */
    private $outcomeType;

    /**
     * @var string|null
     */
    private $overridesRule;

    /**
     * @var string|null
     */
    private $purpose;

    /**
     * @var string
     */
    private $reference;

    /**
     * @var string|null
     */
    private $requestType;

    /**
     * @var TransactionRuleRestrictions1
     */
    private $ruleRestrictions;

    /**
     * @var int|null
     */
    private $score;

    /**
     * @var string|null
     */
    private $startDate;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string
     */
    private $type;

    /**
     * @param string $description
     * @param TransactionRuleEntityKey2 $entityKey
     * @param TransactionRuleInterval1 $interval
     * @param string $reference
     * @param TransactionRuleRestrictions1 $ruleRestrictions
     * @param string $type
     */
    public function __construct(
        string $description,
        TransactionRuleEntityKey2 $entityKey,
        TransactionRuleInterval1 $interval,
        string $reference,
        TransactionRuleRestrictions1 $ruleRestrictions,
        string $type
    ) {
        $this->description = $description;
        $this->entityKey = $entityKey;
        $this->interval = $interval;
        $this->reference = $reference;
        $this->ruleRestrictions = $ruleRestrictions;
        $this->type = $type;
    }

    /**
     * Returns Aggregation Level.
     * The level at which data must be accumulated, used in rules with `type` **velocity** or **maxUsage**.
     * The level must be the [same or lower in hierarchy](https://docs.adyen.com/issuing/transaction-
     * rules#accumulate-data) than the `entityKey`.
     *
     * If not provided, by default, the rule will accumulate data at the **paymentInstrument** level.
     *
     * Possible values: **paymentInstrument**, **paymentInstrumentGroup**, **balanceAccount**,
     * **accountHolder**, **balancePlatform**.
     */
    public function getAggregationLevel(): ?string
    {
        return $this->aggregationLevel;
    }

    /**
     * Sets Aggregation Level.
     * The level at which data must be accumulated, used in rules with `type` **velocity** or **maxUsage**.
     * The level must be the [same or lower in hierarchy](https://docs.adyen.com/issuing/transaction-
     * rules#accumulate-data) than the `entityKey`.
     *
     * If not provided, by default, the rule will accumulate data at the **paymentInstrument** level.
     *
     * Possible values: **paymentInstrument**, **paymentInstrumentGroup**, **balanceAccount**,
     * **accountHolder**, **balancePlatform**.
     *
     * @maps aggregationLevel
     */
    public function setAggregationLevel(?string $aggregationLevel): void
    {
        $this->aggregationLevel = $aggregationLevel;
    }

    /**
     * Returns Description.
     * Your description for the transaction rule.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Your description for the transaction rule.
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns End Date.
     * The date when the rule will stop being evaluated, in ISO 8601 extended offset date-time format. For
     * example, **2025-03-19T10:15:30+01:00**.
     *
     * If not provided, the rule will be evaluated until the rule status is set to **inactive**.
     */
    public function getEndDate(): ?string
    {
        return $this->endDate;
    }

    /**
     * Sets End Date.
     * The date when the rule will stop being evaluated, in ISO 8601 extended offset date-time format. For
     * example, **2025-03-19T10:15:30+01:00**.
     *
     * If not provided, the rule will be evaluated until the rule status is set to **inactive**.
     *
     * @maps endDate
     */
    public function setEndDate(?string $endDate): void
    {
        $this->endDate = $endDate;
    }

    /**
     * Returns Entity Key.
     * The type and unique identifier of the resource to which the rule applies.
     */
    public function getEntityKey(): TransactionRuleEntityKey2
    {
        return $this->entityKey;
    }

    /**
     * Sets Entity Key.
     * The type and unique identifier of the resource to which the rule applies.
     *
     * @required
     * @maps entityKey
     */
    public function setEntityKey(TransactionRuleEntityKey2 $entityKey): void
    {
        $this->entityKey = $entityKey;
    }

    /**
     * Returns Interval.
     * The [time interval](https://docs.adyen.com/issuing/transaction-rules#time-intervals) when the rule
     * conditions apply.
     */
    public function getInterval(): TransactionRuleInterval1
    {
        return $this->interval;
    }

    /**
     * Sets Interval.
     * The [time interval](https://docs.adyen.com/issuing/transaction-rules#time-intervals) when the rule
     * conditions apply.
     *
     * @required
     * @maps interval
     */
    public function setInterval(TransactionRuleInterval1 $interval): void
    {
        $this->interval = $interval;
    }

    /**
     * Returns Outcome Type.
     * The [outcome](https://docs.adyen.com/issuing/transaction-rules#outcome) that will be applied when a
     * transaction meets the conditions of the rule.
     *
     * Possible values:
     * * **hardBlock** (default): the transaction is declined.
     * * **scoreBased**: the transaction is assigned the `score` you specified. Adyen calculates the total
     * score and if it exceeds 100, the transaction is declined. This value is not allowed when
     * `requestType` is **bankTransfer**.
     *
     * * **enforceSCA**: your user is prompted to verify their identity using [3D Secure
     * authentication](https://docs.adyen.com/issuing/3d-secure/). If the authentication fails or times out,
     * the transaction is declined. This value is only allowed when `requestType` is **authentication**.
     */
    public function getOutcomeType(): ?string
    {
        return $this->outcomeType;
    }

    /**
     * Sets Outcome Type.
     * The [outcome](https://docs.adyen.com/issuing/transaction-rules#outcome) that will be applied when a
     * transaction meets the conditions of the rule.
     *
     * Possible values:
     * * **hardBlock** (default): the transaction is declined.
     * * **scoreBased**: the transaction is assigned the `score` you specified. Adyen calculates the total
     * score and if it exceeds 100, the transaction is declined. This value is not allowed when
     * `requestType` is **bankTransfer**.
     *
     * * **enforceSCA**: your user is prompted to verify their identity using [3D Secure
     * authentication](https://docs.adyen.com/issuing/3d-secure/). If the authentication fails or times out,
     * the transaction is declined. This value is only allowed when `requestType` is **authentication**.
     *
     * @maps outcomeType
     * @factory \AdyenLib\Models\OutcomeTypeEnum::checkValue
     */
    public function setOutcomeType(?string $outcomeType): void
    {
        $this->outcomeType = $outcomeType;
    }

    /**
     * Returns Overrides Rule.
     * The `id` of the transaction rule you want to override or skip for the specified `entityKey`.
     */
    public function getOverridesRule(): ?string
    {
        return $this->overridesRule;
    }

    /**
     * Sets Overrides Rule.
     * The `id` of the transaction rule you want to override or skip for the specified `entityKey`.
     *
     * @maps overridesRule
     */
    public function setOverridesRule(?string $overridesRule): void
    {
        $this->overridesRule = $overridesRule;
    }

    /**
     * Returns Purpose.
     * Specifies the reason for creating the rule.
     *
     * Possible values:
     * * **fraud**: the rule is created to regulate fraudulent activity.
     * * **policy**: the rule is created to ensure that the transaction adheres to your business' policies.
     * For example, if your business has policies about the Merchant Category Codes (MCCs) allowed on a
     * transaction, you can create a rule to block transactions that have specific MCCs.
     */
    public function getPurpose(): ?string
    {
        return $this->purpose;
    }

    /**
     * Sets Purpose.
     * Specifies the reason for creating the rule.
     *
     * Possible values:
     * * **fraud**: the rule is created to regulate fraudulent activity.
     * * **policy**: the rule is created to ensure that the transaction adheres to your business' policies.
     * For example, if your business has policies about the Merchant Category Codes (MCCs) allowed on a
     * transaction, you can create a rule to block transactions that have specific MCCs.
     *
     * @maps purpose
     * @factory \AdyenLib\Models\PurposeEnum::checkValue
     */
    public function setPurpose(?string $purpose): void
    {
        $this->purpose = $purpose;
    }

    /**
     * Returns Reference.
     * Your reference for the transaction rule.
     */
    public function getReference(): string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * Your reference for the transaction rule.
     *
     * @required
     * @maps reference
     */
    public function setReference(string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Request Type.
     * Indicates the type of request to which the rule applies. If not provided, by default, this is set to
     * **authorization**.
     *
     * Possible values: **authorization**, **authentication**, **tokenization**, **bankTransfer**.
     */
    public function getRequestType(): ?string
    {
        return $this->requestType;
    }

    /**
     * Sets Request Type.
     * Indicates the type of request to which the rule applies. If not provided, by default, this is set to
     * **authorization**.
     *
     * Possible values: **authorization**, **authentication**, **tokenization**, **bankTransfer**.
     *
     * @maps requestType
     * @factory \AdyenLib\Models\RequestTypeEnum::checkValue
     */
    public function setRequestType(?string $requestType): void
    {
        $this->requestType = $requestType;
    }

    /**
     * Returns Rule Restrictions.
     * Contains one or more objects that define the [rule conditions](https://docs.adyen.
     * com/issuing/transaction-rules#conditions). Each object must have a value and an operation which
     * determines how the values must be evaluated.
     *
     * For example, a `countries` object can have a list of country codes **["US", "CA"]** in the `value`
     * field and **anyMatch** in the `operation` field.
     */
    public function getRuleRestrictions(): TransactionRuleRestrictions1
    {
        return $this->ruleRestrictions;
    }

    /**
     * Sets Rule Restrictions.
     * Contains one or more objects that define the [rule conditions](https://docs.adyen.
     * com/issuing/transaction-rules#conditions). Each object must have a value and an operation which
     * determines how the values must be evaluated.
     *
     * For example, a `countries` object can have a list of country codes **["US", "CA"]** in the `value`
     * field and **anyMatch** in the `operation` field.
     *
     * @required
     * @maps ruleRestrictions
     */
    public function setRuleRestrictions(TransactionRuleRestrictions1 $ruleRestrictions): void
    {
        $this->ruleRestrictions = $ruleRestrictions;
    }

    /**
     * Returns Score.
     * A positive or negative score applied to the transaction if it meets the conditions of the rule.
     * Required when `outcomeType` is **scoreBased**.  The value must be between **-100** and **100**.
     */
    public function getScore(): ?int
    {
        return $this->score;
    }

    /**
     * Sets Score.
     * A positive or negative score applied to the transaction if it meets the conditions of the rule.
     * Required when `outcomeType` is **scoreBased**.  The value must be between **-100** and **100**.
     *
     * @maps score
     */
    public function setScore(?int $score): void
    {
        $this->score = $score;
    }

    /**
     * Returns Start Date.
     * The date when the rule will start to be evaluated, in ISO 8601 extended offset date-time format. For
     * example, **2025-03-19T10:15:30+01:00**.
     *
     * If not provided when creating a transaction rule, the `startDate` is set to the date when the rule
     * status is set to **active**.
     */
    public function getStartDate(): ?string
    {
        return $this->startDate;
    }

    /**
     * Sets Start Date.
     * The date when the rule will start to be evaluated, in ISO 8601 extended offset date-time format. For
     * example, **2025-03-19T10:15:30+01:00**.
     *
     * If not provided when creating a transaction rule, the `startDate` is set to the date when the rule
     * status is set to **active**.
     *
     * @maps startDate
     */
    public function setStartDate(?string $startDate): void
    {
        $this->startDate = $startDate;
    }

    /**
     * Returns Status.
     * The status of the transaction rule. If you provide a `startDate` in the request, the rule is
     * automatically created
     * with an **active** status.
     *
     * Possible values: **active**, **inactive**.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status of the transaction rule. If you provide a `startDate` in the request, the rule is
     * automatically created
     * with an **active** status.
     *
     * Possible values: **active**, **inactive**.
     *
     * @maps status
     * @factory \AdyenLib\Models\Status6Enum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Type.
     * The [type of rule](https://docs.adyen.com/issuing/transaction-rules#rule-types), which defines if a
     * rule blocks transactions based on individual characteristics or accumulates data.
     *
     * Possible values:
     * * **blockList**: decline a transaction when the conditions are met.
     * * **maxUsage**: add the amount or number of transactions for the lifetime of a payment instrument,
     * and then decline a transaction when the specified limits are met.
     * * **velocity**: add the amount or number of transactions based on a specified time interval, and
     * then decline a transaction when the specified limits are met.
     * * **bypass**: bypass or skip a rule for the specified `entityKey`. Transactions processed to that
     * entity are no longer evaluated by the bypassed rule.  You must provide the `id` of the rule to
     * bypass in `overridesRule` and leave the `ruleRestrictions` object empty.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The [type of rule](https://docs.adyen.com/issuing/transaction-rules#rule-types), which defines if a
     * rule blocks transactions based on individual characteristics or accumulates data.
     *
     * Possible values:
     * * **blockList**: decline a transaction when the conditions are met.
     * * **maxUsage**: add the amount or number of transactions for the lifetime of a payment instrument,
     * and then decline a transaction when the specified limits are met.
     * * **velocity**: add the amount or number of transactions based on a specified time interval, and
     * then decline a transaction when the specified limits are met.
     * * **bypass**: bypass or skip a rule for the specified `entityKey`. Transactions processed to that
     * entity are no longer evaluated by the bypassed rule.  You must provide the `id` of the rule to
     * bypass in `overridesRule` and leave the `ruleRestrictions` object empty.
     *
     * @required
     * @maps type
     * @factory \AdyenLib\Models\Type141Enum::checkValue
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the TransactionRuleInfo object to a human-readable string representation.
     *
     * @return string The string representation of the TransactionRuleInfo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TransactionRuleInfo',
            [
                'aggregationLevel' => $this->aggregationLevel,
                'description' => $this->description,
                'endDate' => $this->endDate,
                'entityKey' => $this->entityKey,
                'interval' => $this->interval,
                'outcomeType' => $this->outcomeType,
                'overridesRule' => $this->overridesRule,
                'purpose' => $this->purpose,
                'reference' => $this->reference,
                'requestType' => $this->requestType,
                'ruleRestrictions' => $this->ruleRestrictions,
                'score' => $this->score,
                'startDate' => $this->startDate,
                'status' => $this->status,
                'type' => $this->type
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->aggregationLevel)) {
            $json['aggregationLevel'] = $this->aggregationLevel;
        }
        $json['description']          = $this->description;
        if (isset($this->endDate)) {
            $json['endDate']          = $this->endDate;
        }
        $json['entityKey']            = $this->entityKey;
        $json['interval']             = $this->interval;
        if (isset($this->outcomeType)) {
            $json['outcomeType']      = OutcomeTypeEnum::checkValue($this->outcomeType);
        }
        if (isset($this->overridesRule)) {
            $json['overridesRule']    = $this->overridesRule;
        }
        if (isset($this->purpose)) {
            $json['purpose']          = PurposeEnum::checkValue($this->purpose);
        }
        $json['reference']            = $this->reference;
        if (isset($this->requestType)) {
            $json['requestType']      = RequestTypeEnum::checkValue($this->requestType);
        }
        $json['ruleRestrictions']     = $this->ruleRestrictions;
        if (isset($this->score)) {
            $json['score']            = $this->score;
        }
        if (isset($this->startDate)) {
            $json['startDate']        = $this->startDate;
        }
        if (isset($this->status)) {
            $json['status']           = Status6Enum::checkValue($this->status);
        }
        $json['type']                 = Type141Enum::checkValue($this->type);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
