<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class TransferInstrumentReference implements \JsonSerializable
{
    /**
     * @var string
     */
    private $accountIdentifier;

    /**
     * @var string
     */
    private $id;

    /**
     * @var string|null
     */
    private $realLastFour;

    /**
     * @var bool|null
     */
    private $trustedSource;

    /**
     * @param string $accountIdentifier
     * @param string $id
     */
    public function __construct(string $accountIdentifier, string $id)
    {
        $this->accountIdentifier = $accountIdentifier;
        $this->id = $id;
    }

    /**
     * Returns Account Identifier.
     * The masked IBAN or bank account number.
     */
    public function getAccountIdentifier(): string
    {
        return $this->accountIdentifier;
    }

    /**
     * Sets Account Identifier.
     * The masked IBAN or bank account number.
     *
     * @required
     * @maps accountIdentifier
     */
    public function setAccountIdentifier(string $accountIdentifier): void
    {
        $this->accountIdentifier = $accountIdentifier;
    }

    /**
     * Returns Id.
     * The unique identifier of the resource.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The unique identifier of the resource.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Real Last Four.
     * Four last digits of the bank account number. If the transfer instrument is created using [instant
     * bank account verification](https://docs.adyen.com/release-notes/platforms-and-financial-
     * products#releaseNote=2023-05-08-hosted-onboarding), and it is a virtual bank account, these digits
     * may be different from the last four digits of the masked account number.
     */
    public function getRealLastFour(): ?string
    {
        return $this->realLastFour;
    }

    /**
     * Sets Real Last Four.
     * Four last digits of the bank account number. If the transfer instrument is created using [instant
     * bank account verification](https://docs.adyen.com/release-notes/platforms-and-financial-
     * products#releaseNote=2023-05-08-hosted-onboarding), and it is a virtual bank account, these digits
     * may be different from the last four digits of the masked account number.
     *
     * @maps realLastFour
     */
    public function setRealLastFour(?string $realLastFour): void
    {
        $this->realLastFour = $realLastFour;
    }

    /**
     * Returns Trusted Source.
     * Identifies if the bank account was created through [instant bank verification](https://docs.adyen.
     * com/release-notes/platforms-and-financial-products#releaseNote=2023-05-08-hosted-onboarding).
     */
    public function getTrustedSource(): ?bool
    {
        return $this->trustedSource;
    }

    /**
     * Sets Trusted Source.
     * Identifies if the bank account was created through [instant bank verification](https://docs.adyen.
     * com/release-notes/platforms-and-financial-products#releaseNote=2023-05-08-hosted-onboarding).
     *
     * @maps trustedSource
     */
    public function setTrustedSource(?bool $trustedSource): void
    {
        $this->trustedSource = $trustedSource;
    }

    /**
     * Converts the TransferInstrumentReference object to a human-readable string representation.
     *
     * @return string The string representation of the TransferInstrumentReference object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TransferInstrumentReference',
            [
                'accountIdentifier' => $this->accountIdentifier,
                'id' => $this->id,
                'realLastFour' => $this->realLastFour,
                'trustedSource' => $this->trustedSource
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['accountIdentifier'] = $this->accountIdentifier;
        $json['id']                = $this->id;
        if (isset($this->realLastFour)) {
            $json['realLastFour']  = $this->realLastFour;
        }
        if (isset($this->trustedSource)) {
            $json['trustedSource'] = $this->trustedSource;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
