<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class TransactionSearchResponse implements \JsonSerializable
{
    /**
     * @var Links21|null
     */
    private $links;

    /**
     * @var Transaction[]|null
     */
    private $data;

    /**
     * Returns Links.
     * Contains links to the next and previous page whenever applicable.
     */
    public function getLinks(): ?Links21
    {
        return $this->links;
    }

    /**
     * Sets Links.
     * Contains links to the next and previous page whenever applicable.
     *
     * @maps _links
     */
    public function setLinks(?Links21 $links): void
    {
        $this->links = $links;
    }

    /**
     * Returns Data.
     * Contains the transactions that match the query parameters.
     *
     * @return Transaction[]|null
     */
    public function getData(): ?array
    {
        return $this->data;
    }

    /**
     * Sets Data.
     * Contains the transactions that match the query parameters.
     *
     * @maps data
     *
     * @param Transaction[]|null $data
     */
    public function setData(?array $data): void
    {
        $this->data = $data;
    }

    /**
     * Converts the TransactionSearchResponse object to a human-readable string representation.
     *
     * @return string The string representation of the TransactionSearchResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('TransactionSearchResponse', ['links' => $this->links, 'data' => $this->data]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->links)) {
            $json['_links'] = $this->links;
        }
        if (isset($this->data)) {
            $json['data']   = $this->data;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
