<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class TransactionRuleResponse implements \JsonSerializable
{
    /**
     * @var TransactionRule1|null
     */
    private $transactionRule;

    /**
     * Returns Transaction Rule.
     * The transaction rule.
     */
    public function getTransactionRule(): ?TransactionRule1
    {
        return $this->transactionRule;
    }

    /**
     * Sets Transaction Rule.
     * The transaction rule.
     *
     * @maps transactionRule
     */
    public function setTransactionRule(?TransactionRule1 $transactionRule): void
    {
        $this->transactionRule = $transactionRule;
    }

    /**
     * Converts the TransactionRuleResponse object to a human-readable string representation.
     *
     * @return string The string representation of the TransactionRuleResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('TransactionRuleResponse', ['transactionRule' => $this->transactionRule]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->transactionRule)) {
            $json['transactionRule'] = $this->transactionRule;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
