<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Type of organization.
 *
 * Possible values: **associationIncorporated**, **governmentalOrganization**, **listedPublicCompany**,
 * **nonProfit**, **partnershipIncorporated**, **privateCompany**.
 */
class Type161Enum
{
    public const ASSOCIATIONINCORPORATED = 'associationIncorporated';

    public const GOVERNMENTALORGANIZATION = 'governmentalOrganization';

    public const LISTEDPUBLICCOMPANY = 'listedPublicCompany';

    public const NONPROFIT = 'nonProfit';

    public const PARTNERSHIPINCORPORATED = 'partnershipIncorporated';

    public const PRIVATECOMPANY = 'privateCompany';

    private const _ALL_VALUES = [
        self::ASSOCIATIONINCORPORATED,
        self::GOVERNMENTALORGANIZATION,
        self::LISTEDPUBLICCOMPANY,
        self::NONPROFIT,
        self::PARTNERSHIPINCORPORATED,
        self::PRIVATECOMPANY
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Type161Enum.");
    }
}
