<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The type of transfer.
 *
 * Possible values:
 *
 * - **bankTransfer**: for push transfers to a transfer instrument or a bank account. The `category`
 * must be **bank**.
 * - **internalTransfer**: for push transfers between balance accounts. The `category` must be
 * **internal**.
 * - **internalDirectDebit**: for pull transfers (direct debits) between balance accounts. The
 * `category` must be **internal**.
 */
class Type113Enum
{
    public const BANKTRANSFER = 'bankTransfer';

    public const INTERNALTRANSFER = 'internalTransfer';

    public const INTERNALDIRECTDEBIT = 'internalDirectDebit';

    private const _ALL_VALUES = [self::BANKTRANSFER, self::INTERNALTRANSFER, self::INTERNALDIRECTDEBIT];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Type113Enum.");
    }
}
