<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Defines the relationship of the legal entity to the current legal entity.
 *
 * Possible value for individuals: **legalRepresentative**.
 *
 * Possible values for organizations: **director**, **signatory**, **trustOwnership**,
 * **uboThroughOwnership**, **uboThroughControl**, **ultimateParentCompany**, or
 * **immediateParentCompany**.
 *
 * Possible values for sole proprietorships: **soleProprietorship**.
 *
 * Possible value for trusts: **trust**.
 *
 * Possible values for trust members: **definedBeneficiary**, **protector**, **secondaryTrustee**,
 * **settlor**, **uboThroughControl**, or **uboThroughOwnership**.
 *
 * Possible value for unincorporated partnership: **unincorporatedPartnership**.
 *
 * Possible values for unincorporated partnership members: **secondaryPartner**, **uboThroughControl**,
 * **uboThroughOwnership**
 */
class Type142Enum
{
    public const DEFINEDBENEFICIARY = 'definedBeneficiary';

    public const DIRECTOR = 'director';

    public const IMMEDIATEPARENTCOMPANY = 'immediateParentCompany';

    public const LEGALREPRESENTATIVE = 'legalRepresentative';

    public const PCISIGNATORY = 'pciSignatory';

    public const PROTECTOR = 'protector';

    public const SECONDARYPARTNER = 'secondaryPartner';

    public const SECONDARYTRUSTEE = 'secondaryTrustee';

    public const SETTLOR = 'settlor';

    public const SIGNATORY = 'signatory';

    public const SOLEPROPRIETORSHIP = 'soleProprietorship';

    public const TRUST = 'trust';

    public const TRUSTOWNERSHIP = 'trustOwnership';

    public const UBOTHROUGHCONTROL = 'uboThroughControl';

    public const UBOTHROUGHOWNERSHIP = 'uboThroughOwnership';

    public const ULTIMATEPARENTCOMPANY = 'ultimateParentCompany';

    public const UNDEFINEDBENEFICIARY = 'undefinedBeneficiary';

    public const UNINCORPORATEDPARTNERSHIP = 'unincorporatedPartnership';

    private const _ALL_VALUES = [
        self::DEFINEDBENEFICIARY,
        self::DIRECTOR,
        self::IMMEDIATEPARENTCOMPANY,
        self::LEGALREPRESENTATIVE,
        self::PCISIGNATORY,
        self::PROTECTOR,
        self::SECONDARYPARTNER,
        self::SECONDARYTRUSTEE,
        self::SETTLOR,
        self::SIGNATORY,
        self::SOLEPROPRIETORSHIP,
        self::TRUST,
        self::TRUSTOWNERSHIP,
        self::UBOTHROUGHCONTROL,
        self::UBOTHROUGHOWNERSHIP,
        self::ULTIMATEPARENTCOMPANY,
        self::UNDEFINEDBENEFICIARY,
        self::UNINCORPORATEDPARTNERSHIP
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Type142Enum.");
    }
}
