<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class UKFpsTracingData implements \JsonSerializable
{
    /**
     * @var string
     */
    private $fpid;

    /**
     * @var string
     */
    private $type;

    /**
     * @param string $fpid
     */
    public function __construct(string $fpid)
    {
        $this->fpid = $fpid;
    }

    /**
     * Returns Fpid.
     * The FPS trace number. This is a unique identifier assigned to transfers processed by [FPS](https:
     * //www.bankofengland.co.uk/payment-systems/services/faster-payments-service).
     */
    public function getFpid(): string
    {
        return $this->fpid;
    }

    /**
     * Sets Fpid.
     * The FPS trace number. This is a unique identifier assigned to transfers processed by [FPS](https:
     * //www.bankofengland.co.uk/payment-systems/services/faster-payments-service).
     *
     * @required
     * @maps fpid
     */
    public function setFpid(string $fpid): void
    {
        $this->fpid = $fpid;
    }

    /**
     * Returns Type.
     * **ukFps**
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * **ukFps**
     *
     * @maps type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the UKFpsTracingData object to a human-readable string representation.
     *
     * @return string The string representation of the UKFpsTracingData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('UKFpsTracingData', ['fpid' => $this->fpid, 'type' => $this->type]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['fpid'] = $this->fpid;
        $json['type'] = $this->type;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
