<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

/**
 * @discriminator type
 * @discriminatorType ukLocal
 */
class UKLocalAccountIdentification1 extends BankAccountIdentification implements \JsonSerializable
{
    /**
     * @var string
     */
    private $accountNumber;

    /**
     * @var string
     */
    private $sortCode;

    /**
     * @param string $accountNumber
     * @param string $sortCode
     */
    public function __construct(string $accountNumber, string $sortCode)
    {
        $this->accountNumber = $accountNumber;
        $this->sortCode = $sortCode;
    }

    /**
     * Returns Account Number.
     * The 8-digit bank account number, without separators or whitespace.
     */
    public function getAccountNumber(): string
    {
        return $this->accountNumber;
    }

    /**
     * Sets Account Number.
     * The 8-digit bank account number, without separators or whitespace.
     *
     * @required
     * @maps accountNumber
     */
    public function setAccountNumber(string $accountNumber): void
    {
        $this->accountNumber = $accountNumber;
    }

    /**
     * Returns Sort Code.
     * The 6-digit [sort code](https://en.wikipedia.org/wiki/Sort_code), without separators or whitespace.
     */
    public function getSortCode(): string
    {
        return $this->sortCode;
    }

    /**
     * Sets Sort Code.
     * The 6-digit [sort code](https://en.wikipedia.org/wiki/Sort_code), without separators or whitespace.
     *
     * @required
     * @maps sortCode
     */
    public function setSortCode(string $sortCode): void
    {
        $this->sortCode = $sortCode;
    }

    /**
     * Converts the UKLocalAccountIdentification1 object to a human-readable string representation.
     *
     * @return string The string representation of the UKLocalAccountIdentification1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UKLocalAccountIdentification1',
            ['accountNumber' => $this->accountNumber, 'sortCode' => $this->sortCode],
            parent::__toString()
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['accountNumber'] = $this->accountNumber;
        $json['sortCode']      = $this->sortCode;
        $json = array_merge($json, parent::jsonSerialize(true));
        $json['type'] = $this->getType() ?? 'ukLocal';

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
