<?php

declare(strict_types=1);

/*
 * Adyen
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenLib\Models;

use AdyenLib\ApiHelper;
use stdClass;

class Unreferenced implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $enableUnreferencedRefunds;

    /**
     * Returns Enable Unreferenced Refunds.
     * Indicates whether unreferenced refunds are enabled on the terminal.
     *
     * > You're fully liable for losses resulting from fraudulent or duplicate unreferenced refunds. We
     * recommend that you [set an unreferenced refund limit and a refund delay](https://docs.adyen.
     * com/point-of-sale/basic-tapi-integration/refund-payment/unreferenced/#risk-with-unreferenced-
     * refunds) to reduce this risk.
     */
    public function getEnableUnreferencedRefunds(): ?bool
    {
        return $this->enableUnreferencedRefunds;
    }

    /**
     * Sets Enable Unreferenced Refunds.
     * Indicates whether unreferenced refunds are enabled on the terminal.
     *
     * > You're fully liable for losses resulting from fraudulent or duplicate unreferenced refunds. We
     * recommend that you [set an unreferenced refund limit and a refund delay](https://docs.adyen.
     * com/point-of-sale/basic-tapi-integration/refund-payment/unreferenced/#risk-with-unreferenced-
     * refunds) to reduce this risk.
     *
     * @maps enableUnreferencedRefunds
     */
    public function setEnableUnreferencedRefunds(?bool $enableUnreferencedRefunds): void
    {
        $this->enableUnreferencedRefunds = $enableUnreferencedRefunds;
    }

    /**
     * Converts the Unreferenced object to a human-readable string representation.
     *
     * @return string The string representation of the Unreferenced object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Unreferenced',
            ['enableUnreferencedRefunds' => $this->enableUnreferencedRefunds]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->enableUnreferencedRefunds)) {
            $json['enableUnreferencedRefunds'] = $this->enableUnreferencedRefunds;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
